### ISSUE TITLE
setting multiple stages for add_instances example

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.entk#137]
I tried to set multiple stages for add_instances example and this gives me the following error:

```
================================================================================
 EnsembleMD (0.4-RC0)                                                           
================================================================================

Starting Allocation                                                           ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
--------------------------------------------------------------------------------
Executing 16 instances of 4 stages on 16 allocated core(s) on 'xsede.stampede'  

Job waiting on queue...
Job is now running !
Waiting for stage_1 to complete.                                            done2016-05-13 16:46:49,026: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during execution: 'MyApp' object has no attribute 'stage_2'.

        Fatal error during execution: 'MyApp' object has no attribute 'stage_2'.
Starting Deallocation..
2016-05-13 16:46:49,027: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during execution: 'MyApp' object has no attribute 'stage_2'.
Fatal error: 'MyApp' object has no attribute 'stage_2'.  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 312, in run
    plugin.execute_pattern(pattern, self)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/bag_of_tasks/static.py", line 131, in execute_pattern
    s_meth = getattr(pattern, 'stage_{0}'.format(stage))
Resource allocation cancelled.
        done 
```

I understand that only stage_1 is defined, but when you encourage the user to "play around" this would be one of the first things to do. It would be nice if specification of multiple stages would be handled in a cleaner way

**Comment by vivek-bala** [comment]
Have you defined stage_2 in the pattern ? By default there is just stage_1 defined. This looks like an error that would stem from that.

**Comment by antonst** [comment]
>Have you defined stage_2 in the pattern ?

No I haven't, but since you have encouraged me "to play around" I have specified multiple stages! I don't see any reason why this should result in an error.

**Comment by vivek-bala** [comment]
Yes, but you have just defined that there are 4 stages. Not what each of those stages do. You also have to specify what needs to be performed in those stages.

```
def stage_1(self, instance):
                k = Kernel(name="misc.hello")
                k.upload_input_data = ['./input_file.txt > temp.txt']
                k.arguments = ["--file=temp.txt"]
                k.download_output_data = ['./temp.txt > output_file_{0}.txt'.format(instance)]
                return k
```

This defined what needs to be performed in stage_1. You need similar definitions for the other stages.

**Comment by antonst** [comment]
I understand that, but instead of seeing a bunch of error messages, (which is not helpful at all) application could simply terminate displaying the text saying exactly what you said above!

**Comment by antonst** [comment]
In such scenario it should not run at all.

**Comment by vivek-bala** [comment]
```
Fatal error during execution: 'MyApp' object has no attribute 'stage_2'.
Starting Deallocation..
``` 
I think that is the gist of what I said. But I suppose you mean it should start if the stages are defined before starting to execute.

**Comment by antonst** [comment]
The code should not run at all. Also things like:
```
File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 312, in run
    plugin.execute_pattern(pattern, self)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/bag_of_tasks/static.py", line 131, in execute_pattern
    s_meth = getattr(pattern, 'stage_{0}'.format(stage))
```

should not be exposed in this case. I think this can easily be avoided.

**Comment by vivek-bala** [comment]
I think checking if the parameters like number of stages, stages are correct before execution is a good idea. But I'll be hesitant to make this change for the workshop. I'll leave this ticket open to be picked up after the workshop.

**Comment by vivek-bala** [comment]
No longer applicable.
