### ISSUE TITLE
(non fatal?) error on ccount.py towards stampede

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.entk#148]
```
$ RADICAL_ENTK_VERBOSE=REPORT python ccount.py xsede.stampede

================================================================================
 EnsembleMD (0.4-RC0-23-g7974c73)                                               
================================================================================

Starting Allocation2016-05-14 14:54:47,634: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : Couldn't call manager callback (no pilot instance)
                                                           ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
```

Seems to continue fine though.

**Comment by andre-merzky** [comment]
That is also a RP level problem, cause by a race: a pilot state is triggering the callback in a thread which does not know anything about that pilot, yet.  Antons also mentioned that, I'll downgrade the log to a warning, then it will not mess with the reporter output, and it is indeed not a fatal error anymore (it was at some point in the past).

**Comment by vivek-bala** [comment]
Yes, I think this might be a case some race condition when the callback is triggered before the pilot is created (?).

**Comment by vivek-bala** [comment]
I believe this was addressed. Will have a round of testing for the current examples.
