### ISSUE TITLE
reduce a level of ...

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.entk#153]
we have 5.1.1.1 at
http://radicalensemblemd.readthedocs.io/en/devel/examples/poe/index.html

we can remove the first level on this page, " Pipeline of Ensembles (PoE) Example"

to then just have three levels of

**Comment by vivek-bala** [comment]
layout change needs discussion.

**Comment by vivek-bala** [comment]
Old but the current documentation should have correct number of levels.
