### ISSUE TITLE
minor --- consistency

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.entk#154]
5.1.1.2. Run on a Remote Cluster

has an example:

SingleClusterEnvironment(
    resource="localhost",

but code is actually:

SingleClusterEnvironment(
resource=resource,

Minor minor issue, but we should make consistent.

**Comment by vivek-bala** [comment]
added a note with an explanation. the scripts are customized for the tutorial and hence the difference.

**Comment by vivek-bala** [comment]
NA for current docs
