### ISSUE TITLE
documentation for getting started

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.entk#166]
in subsection http://radicalensemblemd.readthedocs.io/en/tutorial-xsede_2016/user_guide/getstarted.html#using-the-kernel-plugin

in first code snippet argument is specified as: `k.arguments = ["--file=output_{0}.txt".format(instance)]` but in code as: `k.arguments = ["--file=output.txt"]`

**Comment by vivek-bala** [comment]
NA for 0.6 docs.
