### ISSUE TITLE
stage_2 function declaration

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.entk#169]
The function `stage_2` is declared as `def stage_2(self, instances):`, but `instances is never used`. Is `instances` actually required?

**Comment by vivek-bala** [comment]
You can use the "instance" to index things. 

Example:
```
k.download_output_data = [" temp.txt > temp_{0}.txt".format(instance)]
```

The following will overwrite the same file:
```
k.download_output_data = [" temp.txt > temp.txt"]
```
