### ISSUE TITLE
Change get_output to get the output of the current iteration

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.entk#170]
`get_output` currently requires a specific iteration be specified. It would be nice to be able to specify the current iteration by default. Requesting this feature plz.

**Comment by vivek-bala** [comment]
in eop pattern, there is no "iteration" as such. You can now remove "iteration" from the argument list, it automatically points to the "currect iteration".
in poe pattern, if you don't specify iteration it assumes you are referring to the current iteration or you can specify which iteration you want to refer to.

I changed this in "new_arch" branch. You might want to make a new branch of it and use as I will be making changes to "new_arch".
