### ISSUE TITLE
Errors in AppManager

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.entk#172]
Hey, I've encountered a bunch of Indentation and Syntax Errors when trying to import the AppManager. I would fix it myself, but your editor settings for tabs is different than mine, so I don't want to mess it up.

**Comment by vivek-bala** [comment]
Hmmm.. I think as long as the entire script is tabbed the same way it shouldn't matter (i use tabs instead of spaces, but I will be changing to spaces everywhere). Will take a look at the commit.

Could you post the syntax errors though. Should be quick fixes.

**Comment by vivek-bala** [comment]
I'm assuming you tried the usecase_msm example. The ebola example is not ready yet.

**Comment by vivek-bala** [comment]
Hey @mingtaiha I will leave this ticket open for now and revisit this once I send around a testing matrix before the next entk release.

**Comment by vivek-bala** [comment]
NA
