### ISSUE TITLE
Resolve non-responding thread in EoP pattern

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#182]

**Comment by vivek-bala** [comment]
This issue doesn't pop up with usecase/vivek branch of the RP. It does with master of RP.

**Comment by vivek-bala** [comment]
Also works with split_module_2!

**Comment by andre-merzky** [comment]
Vivek, 

I would suggest to continue work on the `feature/split_module_2` branch then.  State and notification races in the devel and master branches are notoriously hard to debug -- that is why we have the split branches in the first place, really.  All changes from devel are merged into split at the moment, FWIW.

Would that work out for you?  We should discuss how to proceed with the partitioning scheduler, that one is not yet merged.  Any opinion?

**Comment by vivek-bala** [comment]
Yes, I think that works for me for now. The idea is to have a release of entk in the near future since: (i) There have been quite a few changes since the last release (ii) Release of a new repex version is expected (this version would use entk and hence requires entk's release)

I might have missed this in the earlier meetings but could you remind me when is the split_module2 planned to be released?

> We should discuss how to proceed with the partitioning scheduler, that one is not yet merged. Any opinion?

I think if you feel it is stable, we can go ahead and merge as appropriate. For me, this is a useful feature to support (although currently not critical).

**Comment by ibethune** [comment]
Note that the current RP devel now contains the split_module (and split_termination) branches.  Please test as this may resolve this issue.  Note that the partitioned scheduler will not be in the RP 0.46 release, although could make it into the next one.

**Comment by vivek-bala** [comment]
Thanks @ibethune . Will test this against devel.

**Comment by vivek-bala** [comment]
This issue doesn't apply for 0.6. Closing
