### ISSUE TITLE
pipeline example undocumented dependency on wget

### ISSUE THREAD

**Issue by sjzasada** [radical-cybertools/radical.entk#183]
While trying to run the Pipeline of Ensembles (PoE) Example in section 5.1.1. of the ensemblemd documentation, I encountered a problem with the script presented in the documentation. The script shells out to wget to download a file. Wget has been largely superseded by curl and my not be present on a system. This example fails if a system doesn't have wget installed. 

I'd suggest using a pure python solution to download the file to minimise the likelihood of the example failing, e.g.:

```
		r = requests.get('http://gist.githubusercontent.com/oleweidner/6084b9d56b04389717b9/raw/611dd0c184be5f35d75f876b13604c86c470872f/gistfile1.txt', stream=True)

		if r.status_code == 200:
			with open('UTF-8-demo.txt', 'wb') as f:
				r.raw.decode_content = True
				shutil.copyfileobj(r.raw, f)
```

**Comment by sjzasada** [comment]
I've noticed a further discrepancy in the example script. According to the documentation, the script depends on the RADICAL_PILOT_DBURL variable. However, in the example script, the database url is hard coded and the environment variable is seemingly never read.

**Comment by shantenujha** [comment]
@sjzasada Thanks for all your comments/input. 

[](https://github.com/radical-cybertools/radical.ensemblemd/issues/184)

**Comment by vivek-bala** [comment]
Thank you @sjzasada for the feedback and the fix suggestion.

**Comment by vivek-bala** [comment]
This was addressed but not closed. Does not apply to 0.6 docs.
