### ISSUE TITLE
Iterate on the main page of the repository's wiki

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.entk#188]

**Comment by vivek-bala** [comment]
Hey Matteo, please take a look at https://github.com/radical-cybertools/radical.entk/wiki. I haven't added MSKCC since their use case study is still ongoing. If you are ok with the content, please close this ticket.

**Comment by mturilli** [comment]
Looks good to me. 

I would fix the following:
* Change the name of the documentation on readthedocs to EnTK? At the moment I see:
  ```
  From: http://radicalensemblemd.readthedocs.io/en/latest/
  to:   http://entk.readthedocs.io/en/latest/
  ```
* Link users to their github repository
* Add latest meetings to the list (2018) and possibly rename all of them to just the date (as we do for the HPC workflow project)
* Create a custom sidebar with: home, releases, users, meetings

**Comment by vivek-bala** [comment]
Fixed. Reorganized wiki structure.
