### ISSUE TITLE
mpi on localhost: host list issue

### ISSUE THREAD

**Issue by mpbl** [radical-cybertools/radical.entk#192]
Hi,

When trying to use more than 1 MPI process on my local machine (os x --but I don't believe that matters), I run into *slots* issues.

In the generated ```radical_pilot_cu_launch_script.sh```, there is the following:
```
/usr/local/bin/mpiexec -n 4 -host localhost sleep 2
```
which gives:
```
There are not enough slots available in the system to satisfy the 4 slots
that were requested by the application:
  sleep

Either request fewer slots for your application, or make more slots available
for use.
```

(Hand) modifying to:
```
 /usr/local/bin/mpiexec -n 4 -host localhost,localhost,localhost,localhost sleep 2```
```
or to
```
/usr/local/bin/mpiexec -n 4 -host localhost:4 sleep 2
```
works.

Cheers.

**Comment by vivek-bala** [comment]
Thanks Matthieu. I think this would require changes in the RP layer but might possibly be addressed in other branches of RP. @andre-merzky do you think this issue will be fixed in the GPU stack or would the fix for this be different?

**Comment by andre-merzky** [comment]
hi Matthieu, 

how many cores does your mac have?  RP in general does not oversubscribe cores, so I would naively assume that this is the problem.  However, please try setting `RADICAL_DEBUG` in your environment, and run again - that will turn off some relates sanity checks.  If that still fails, please post a tarball of the client and pilot side session sandboxes.

Thanks, Andre.

**Comment by mpbl** [comment]
Hi, Andre,

Here is the info about mpiexec:
```
└─▪ mpiexec --version
mpiexec (OpenRTE) 3.0.0
└─▪ brew info openmpi
open-mpi: stable 3.0.0 (bottled), HEAD
  Built from source on 2017-11-29 at 16:24:13 with: --c++11 --with-java --with-mpi-thread-multiple
```

and about my system:
```
└─▪ sysctl hw.ncpu
hw.ncpu: 8
```
```
└─▪ system_profiler | grep Processor
    Apple: AUVoiceProcessor:
      Processor Name: Intel Core i7
      Processor Speed: 2.5 GHz
      Number of Processors: 1
```

Thanks,
Matthieu

**Comment by vivek-bala** [comment]
Hey Matthieu, Andre, I remember there were some issue due to some version mis-matches in the radical stack. Is this issue related to that? @andre-merzky let me know if I can help resolving this issue.

**Comment by vivek-bala** [comment]
Closing for now. Please reopen if this is still an issue.
