### ISSUE TITLE
long running entk scripts are failing at the pika layer

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#193]
Might be related to https://github.com/pika/pika/issues/397. Currently, execution time of simulations in the UCL use case is around 48 hours and we get the following error: https://github.com/vivek-bala/radical.entk/issues/40

Definitely needs an integration test. (at least to monitor the upper limit of the execution duration if this issue is not resolvable quickly).

**Comment by vivek-bala** [comment]
This issue is not reproducible for me. Upon discussion with Jumana, this issue has not popped up since cleaning the machine of stale docker instances. Closing for now.

**Comment by andre-merzky** [comment]
Was that related to : vivek-bala/radical.entk#40 after all?  Because I did not make progress on that, yet... :/

**Comment by vivek-bala** [comment]
@jdakka was actually facing pika #397 for long running tasks. I believe she does not exactly get that error (```Error: Error: (404, "NOT_FOUND - no queue 'enq-to-sync' in vhost '/'")```) again.

vivek-bala/radical.entk#40 is because of the 92nd task being stuck at UMGR_STAGING_OUTPUT IIUC. 

I'll let Jumana confirm.

**Comment by jdakka** [comment]
Correct. The very last CU is hanging long after the application completes. The UMGR does not update that CU to the final state.

**Comment by vivek-bala** [comment]
@andre-merzky I'll try to reproduce radical.entk#40 as well this evening.

**Comment by andre-merzky** [comment]
@vivek-bala thank you!
