### ISSUE TITLE
potential typo

### ISSUE THREAD

**Issue by mpbl** [radical-cybertools/radical.entk#194]
https://github.com/radical-cybertools/radical.entk/blob/bea1ecd8d01f5cb6c68d3612b038f4d98cce8e52/src/radical/entk/appman/appmanager.py#L557

is supposed to be:
```
            self._mq_channel = self._mq_connection.channel()
```
isn't it?

**Comment by vivek-bala** [comment]
Fixed in rc/0.6 and devel. Thanks Matthieu!
