### ISSUE TITLE
add radical.entk to the radical-stack cmd in utils

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#198]

**Comment by andre-merzky** [comment]
Oops, there is a typo in https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/misc.py#L487 - otherwise its already supported...  Will you test and create a PR?

**Comment by vivek-bala** [comment]
I tested that locally, I don't see it because there is no version_detail() method in entk (only entk.version). Will add, test and create a PR

**Comment by andre-merzky** [comment]
You may want to consider using the `ru.get_version()` method to dig the version and git commit details out.  Let me know if you need any help with that...

**Comment by vivek-bala** [comment]
fixed in rc/0.6.
