### ISSUE TITLE
Pilot reaches active state, but units are not created.

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#201]
Resource: Comet.

`radical-stack` output:
```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/EnTK0.6_env

  radical.pilot        : 0.47-0.47-5-g3a9eb84a@feature-create_ve
  radical.utils        : 0.47-v0.47-4-gcca43d5@devel
  saga                 : 0.47-v0.46-36-g307daeb7@devel

```

Logfiles attached: 
[comet_logfiles.gz](https://github.com/radical-cybertools/radical.entk/files/1695838/comet_logfiles.gz)

**Comment by vivek-bala** [comment]
Can you add the script that is executed as well as the client side logs as well?

**Comment by SrinivasMushnoori** [comment]
Clientside logs are in comet_logs.gz: perhaps I should have named it better.
Script:
[runme.py.tar.gz](https://github.com/radical-cybertools/radical.entk/files/1696035/runme.py.tar.gz)

**Comment by vivek-bala** [comment]
I don't see any units submitted from the umgr. Can you send the EnTK logs as well? You can redirect the EnTK log msgs to a file and attach it here.

**Comment by SrinivasMushnoori** [comment]
Hi, 
attached:
[debug.log](https://github.com/radical-cybertools/radical.entk/files/1696164/debug.log)

**Comment by vivek-bala** [comment]
```
2018-02-05 18:22:50,797: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Task Manager process started
2018-02-05 18:22:50,823: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : Received radical.entk.pipeline.0000 with state SCHEDULING
2018-02-05 18:22:50,823: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : Found pipeline radical.entk.pipeline.0000, state SCHEDULING, completed False
```
Seems like the synchronizer is receiving some objects before the enqueue-thread even sends them?

Can you clean your docker RabbitMQ instance or use a new instance and try again?
If that doesn't work, please add all the input data for runme.py. I will give it a try on Comet.

**Comment by SrinivasMushnoori** [comment]
Creating a fresh RMQ instance has solved this.
