### ISSUE TITLE
Units assigned to the same node on Titan

### ISSUE THREAD

**Issue by kristofarkas** [radical-cybertools/radical.entk#204]
I am having an issue with running NAMD on more than one (1) node on Titan. _This might be a problem on a lower level of the RP stack._

**In short**: all `Task` instances end up running consecutively instead of concurrently, even though there is enough nodes requested.

**`Task` configuration**: `.executable='namd2'`, `.cores=1`, `.mpi=True`, `.arguments=['+ppn', '15', '+pemap', '0-14','sim.conf'` etc. Note how we request 1 core (actually 1 processing element) and specify the process count as arguments to `namd2`. This translates to `aprun -n 1 namd2 ++ppn 15 ...`, which is the correct way to run this version of NAMD.

One possible reason could be that radical places all the CUs onto the same node (for some reason), so they end up running one after another. Maybe because we request only 1 core for the task?

In the `unit.XXX.sh` files the `aprun` calls have the flag `-L #ID` set to be the *same* node id! Is this okay?

Running with the master stack.

@jdakka @vivek-bala

**Comment by andre-merzky** [comment]
kristof, could you please upload a tarball of the pilot sandbox?  Thanks!

**Comment by kristofarkas** [comment]
This is a 1 Pipeline, 4 Stage, 2 Task per stage job. All tasks finished successfully.

[rp.session.titan.tar.gz](https://www.dropbox.com/s/b42qowazf6qy7ho/rp.session.titan.tar.gz?dl=0)

**Comment by vivek-bala** [comment]
It indeed does land on the same node. But you said your task configuration is:

> Task configuration: .executable='namd2', .cores=1, .mpi=True, .arguments=['+ppn', '15', '+pemap', '0-14','sim.conf' etc. Note how we request 1 core (actually 1 processing element) and specify the process count as arguments to namd2. This translates to aprun -n 1 namd2 ++ppn 15 ..., which is the correct way to run this version of NAMD.

You have specified that each task use 1 core. The ppn argument I assume is for NAMD, but EnTK/RP 
understands that your task needs to use 1 core. Let me know if I am missing something.

**Comment by kristofarkas** [comment]
That is correct.

**Comment by jdakka** [comment]
I'm afraid this is why the`gpu` stack conversation came up...because we need to specify the core pinning at the `aprun` level.

**Comment by vivek-bala** [comment]
Hmm okay. Then I am confused. Your current configuration runs one NAMD task on each core. If you need NAMD to use the entire node node I think you would have to use the gpu stack as you did on BW. With the GPU stack, each task needs to be with 1 process and 16 threads_per_process (assuming this NAMD is not MPI enabled).

**Comment by kristofarkas** [comment]
FYI submitting this bash script does correctly allocate the runs to separate nodes:
```
...
aprun -n 1 namd2 ++ppn 15 +pemap 0-14 sim.conf >& sim1.log &
aprun -n 1 namd2 ++ppn 15 +pemap 0-14 sim.conf >& sim2.log &

wait
...
```

**Comment by kristofarkas** [comment]
Is there no way to just force different task onto different nodes?

**Comment by jdakka** [comment]
@kristofarkas that would require setting the `aprun` flags, which is currently done using the `feature/gpu` stack

**Comment by kristofarkas** [comment]
[This](http://www.ks.uiuc.edu/Research/namd/2.12/ug/node84.html) is the documentation briefly describing why we have to run namd like this.

> For MPI-based SMP builds one would specify any mpiexec options needed for the required number of processes and pass +ppn to the NAMD binary as: 
> `mpiexec -n 4 namd2 +ppn 3 <configfile>`

**Comment by vivek-bala** [comment]
> FYI submitting this bash script does correctly allocate the runs to separate nodes:

Good point. I think aprun might (by default) attempt to spread it across multiple nodes before oversubscribing a node. I am not entirely that should be the default in RP (as we assume no knowledge of future workload in RP). But currently (from your logs), RP does oversubscribe a single node before going to the next one:

```/sw/xk6/xalt/0.7.5/bin/aprun -L 3734 -n 1 namd2 "+ppn" "15" "+pemap" "0-14" "esmacs-eq1.conf"```

> Is there no way to just force different task onto different nodes?

This should be resolvable in the gpu stack. Changing the default scheduling might be a lot of work within in RP (and possibly not required since we have the same capability if we specify fully)? @andre-merzky

**Comment by jdakka** [comment]
This is somewhat related to a similar issue I had with BW in [ticket 1500](https://github.com/radical-cybertools/radical.pilot/issues/1500)

**Comment by andre-merzky** [comment]
This workload should be able to use the non-gpu branches, but needs `cores=15; mpi=False` in the unit description.  Vivek, am I missing something - do you see why that would not work?

**Comment by vivek-bala** [comment]
Possibly. If we run with cores=15 + mpi=False, I believe the executable will look like the following:
```
/sw/xk6/xalt/0.7.5/bin/aprun -L 3734 -n 15 namd2 <args>
```
This would spawn 15 processes each running namd2 (since the executable is non-MPI) and put it on node 3734 (regardless of how many threads each process uses). 

I think what @kristofarkas @jdakka want to do is to spawn 1 namd2 process with 15 threads in it. This means they have to specify both the number of processes and the threads per process, i.e. gpu branch.

My understanding is that they either have to use mpi-enabled NAMD with their current stack or the GPU stack with non-mpi NAMD or mpi NAMD (gpu should be able to specify in more detail, so should be able to support both non-mpi and mpi NAMD). Let me know if you think this wouldn't be the case.

**Comment by jdakka** [comment]
Exactly we need the `-n` processes to remain at `1` however we need to adjust the number of threads, either with `-d` as `aprun -n 1 -N 1 -d 16` or directly in NAMD as `aprun -n 1 namd2 ++ppn 15 +setcpuaffinity +pemap 1-15 +commap 0`

**Comment by andre-merzky** [comment]
the `-n ` value will remain at `1` if mpi is set to false.  The nodelist given to aprun will, however, contain 15 entries.

**Comment by kristofarkas** [comment]
Testing with `mpi=False, cores=15 and 16` behaves differently but has the same problem. In this case it seems that the concurrent Tasks aren't even submitted at the same time, but one after another, as if there weren't enough nodes, i.e. inside the `unit.XXX` folder the `*.sh` etc. files don't appear at the same time. Before these were created at the same time for all concurrent Tasks, but they ended up running one after another. This is a different behaviour.

Do you need the session folder?

**Comment by vivek-bala** [comment]
> the -n value will remain at 1 if mpi is set to false. The nodelist given to aprun will, however, contain 15 entries.

Hmmm okay. That is maybe something to try for now. I wouldn't recommend that as a long term method though.

**Comment by andre-merzky** [comment]
Why not?

**Comment by kristofarkas** [comment]
> The nodelist given to aprun will, however, contain 15 entries

Shouldn't`aprun` get only one node in the node list, as every namd executable runs on 1 node?

**Comment by kristofarkas** [comment]
The `-L` option of `aprun` is a global node id, not some sort of id generated by radical independent of the actual node id? Asking because that number stays the same across units with every possible option combination.

**Comment by vivek-bala** [comment]
> Why not?

My bad. I should have explained better. I wanted to say that I am more in favor of the API we have in the feature/gpu branch (processes, threads_per_process, etc.) but for now what you suggested should work.

**Comment by andre-merzky** [comment]
> Testing with mpi=False, cores=15 and 16 behaves differently but has the same problem. In this case it seems that the concurrent Tasks aren't even submitted at the same time, but one after another, as if there weren't enough nodes, i.e. inside the unit.XXX folder the *.sh etc. files don't appear at the same time. Before these were created at the same time for all concurrent Tasks, but they ended up running one after another. This is a different behaviour.
> 
> Do you need the session folder?

yes, please, I would like to look into the pilot sandbox.  Could you please also dump the database and attach it?  The should work with `radical-pilot-fetch-db <session-id>` (or ` radicalpilot-fetch-db <session-id>`, depending on branch and version).  Thanks!

**Comment by kristofarkas** [comment]
[rp.session.titan.tar.gz](https://www.dropbox.com/s/b42qowazf6qy7ho/rp.session.titan.tar.gz?dl=0)
[rp.session.local.titan.tar.gz](https://github.com/radical-cybertools/radical.entk/files/1721748/rp.session.local.titan.tar.gz)

**Comment by andre-merzky** [comment]
Well, there are not enough nodes: only one node seems to be available for the CUs...  The pilot size is 32 cores, ie. 2 nodes.  1 node is used for the agent, that leaves one node for the CUs, which then *must* run sequentially.

**Comment by vivek-bala** [comment]
Hey Andre, just to be sure. Is that for both aprun and orte launch methods? I remember that was the case for orte.

**Comment by kristofarkas** [comment]
Okay, requesting an additional node for the agent solves the problem. Thanks.

**Comment by jdakka** [comment]
@andre-merzky can you verify whether the launch method needs an entire node/or an additional core? @kristofarkas saw fluctuating performance when using 15 threads vs. 16 threads for each one of his executables. Also, we need this information to modify the resource dictionary for Titan so that it automatically accounts for this added resource.

**Comment by andre-merzky** [comment]
The agent uses a node on crays - no additional cores are reserved on the other compute nodes.

**Comment by andre-merzky** [comment]
I should add that the above holds for the default agent configuration - the agent can be configured to use more nodes.  I assume that this is not relevant for you - but its on of the reasons why we don't automatically add the agent nodes right now: I think the result would be too surprising in many cases...

**Comment by vivek-bala** [comment]
Thanks everyone!
