### ISSUE TITLE
add reporter in entk

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#206]
reporter to provide messages that are meaningful to the user (not developers)

**Comment by andre-merzky** [comment]
[FYI](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/reporter.py) Sorry for the lack of documentation - but a usage example is [here](https://github.com/radical-cybertools/radical.utils/blob/devel/tests/unittests/test_reporter.py)

**Comment by vivek-bala** [comment]
Thanks Andre!

**Comment by vivek-bala** [comment]
Implemented in devel
