### ISSUE TITLE
Support multiple failure handling modes

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#212]
1) Continue on Failure
2) Terminate on Failure
3) Restart on Failure

Currently, 1 and 3 are supported.

Moving ticket from https://github.com/vivek-bala/radical.entk/issues/33

**Comment by iparask** [comment]
@vivek-bala can you add some context in this ticket?

**Comment by iparask** [comment]
@vivek-bala ping

**Comment by lee212** [comment]
Following up, it looks like 2 is only left out to complete. Once I find out the status of 2, this ticket can be updated.

**Comment by mturilli** [comment]
@iparask let's discuss this alongside #255. The goal is to come up with a development roadmap to improve fault-tolerance and resilience in EnTK.

**Comment by iparask** [comment]
PR #538 is merged this can close
