### ISSUE TITLE
RabbitMQ issues for longer running CUs 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.entk#214]
Looping in RP ticket [1560](https://github.com/radical-cybertools/radical.pilot/issues/1560#issuecomment-366992873) 

I attached the docker logs for this docker instance. 
[docker_logs.txt](https://github.com/radical-cybertools/radical.entk/files/1740519/docker_logs.txt)

**Comment by kristofarkas** [comment]
I ran another simulation, with just 30 concurrent CUs, and still get this same error.

**Comment by vivek-bala** [comment]
How long are the simulations? I don't understand which heartbeat is getting missed and why:
```
=ERROR REPORT==== 20-Feb-2018::14:12:03 ===
closing AMQP connection <0.375.0> (160.91.205.200:60454 -> 172.17.0.3:5672):
missed heartbeats from client, timeout: 60s
```

Can you test by setting ```export DISABLE_RMQ_HEARTBEAT=True```? This might quick fix, I'll see which entity is not sending the heartbeat. Can you also tell me the where the docker instance is running and if possible the url?

**Comment by kristofarkas** [comment]
> How long are the simulations?

The first stage is minimisation, around 100 seconds, so quite short.

> Can you also tell me the where the docker instance is running and if possible the url?

The docker instances are at `two.radical-project.org` ports 33040 and 33036.

**Comment by kristofarkas** [comment]
Running it with `export DISABLE_RMQ_HEARTBEAT=True` gives an error during RabbitMQ setup.

**Comment by vivek-bala** [comment]
Ok, thanks for testing! I am trying out a simple example using the same setup. Let's see if I can recreate it. 

Meanwhile can you point to the script+data+instructions so that I can run the same setup as you.

**Comment by vivek-bala** [comment]
Also do specify the version of entk and radical pilot you are using.

**Comment by kristofarkas** [comment]
Stack: 
```
radical.pilot        : 0.47-0.47@master
radical.utils        : 0.47-v0.47-3-g18dab2b@master
saga                 : 0.47-v0.46-34-g0f186f6@master
entk branch devel
```

Is this the/a correct stack?

**Comment by jdakka** [comment]
[script](https://github.com/radical-cybertools/htbac/blob/master/experiments_inspire/esmacs-nilotinib.py)  
@vivek-bala you'll need the systems i.e. the mutations to run this script. I believe those files can be accessed here `/lustre/atlas/scratch/farkaspall/chm126/esmacs-nilotinib` 

@kristofarkas can you verify?

**Comment by vivek-bala** [comment]
Ok, so I should use the above stack that kristof specified and the master branch of htbac?

**Comment by kristofarkas** [comment]
You will also need htbac to be installed.

**Comment by jdakka** [comment]
@vivek-bala yes the `htbac` master branch.

**Comment by shantenujha** [comment]
Is RabbitMQ running in a container?

**Comment by vivek-bala** [comment]
@shantenujha Yes, it is running in a container but on the radical VM.

**Comment by vivek-bala** [comment]
@kristofarkas @jdakka I ran the ht-bac framework for 1 mutation and 10 replicas per mutation. I did get to the 3rd stage. I exited and reduced the simulation duration to be able to test quickly. Although the tasks in the 3rd stage (and consequently 4th stage) failed due to, the execution did complete. 

I have the following suggestions:

* My suggestion would be to start from small number of mutations and replicas per mutation (basically the number of concurrent tasks) and then increase.

* I get the following RabbitMQ error:
```
=WARNING REPORT==== 26-Feb-2018::18:02:40 ===
closing AMQP connection <0.4588.0> (160.91.205.200:34522 -> 172.17.0.6:5672, vhost: '/', user: 'guest'):
client unexpectedly closed TCP connection

=WARNING REPORT==== 26-Feb-2018::18:02:40 ===
closing AMQP connection <0.483.0> (160.91.205.200:34076 -> 172.17.0.6:5672, vhost: '/', user: 'guest'):
client unexpectedly closed TCP connection

=INFO REPORT==== 26-Feb-2018::18:04:48 ===
closing AMQP connection <0.441.0> (160.91.205.200:34039 -> 172.17.0.6:5672, vhost: '/', user: 'guest')
```

I suspect there might be throttling on the frequency of interaction between EnTK running on the login node and the RMQ instance running on the VM. Please try invoking a RMQ instance within Titan. On Titan, you will have to install erlang (http://erlang.org/doc/installation_guide/INSTALL.html section 2.4) and RMQ from source (https://www.rabbitmq.com/install-generic-unix.html)

* @kristofarkas Regarding the rmq error, you should be able to set ```DISABLE_RMQ_HEARTBEAT=True``` using the latest master branch or released version. Try this after the 2nd point above.

**Comment by vivek-bala** [comment]
I tried again with RMQ on Titan itself. The htbac script was configured to run 4 mutations with 2 replicas per mutation (# of concurrent tasks < 13 for now, see https://github.com/radical-cybertools/radical.pilot/issues/1567). The execution completes, i.e. no RMQ errors as before, but the namd tasks failed with a runtime error. I am running the script one more time to be sure this rmq error doesn't show up but this would be a good point for @jdakka and @kristofarkas to give it a go and look at the namd level issues.

**Comment by vivek-bala** [comment]
I can reproduce the same NAMD error. No RMQ issues. If you want access to the NAMD logs/error files, let me know I'll put in a shared location on Titan.

**Comment by kristofarkas** [comment]
Okay, can I see the logs?

**Comment by vivek-bala** [comment]
I put them in "/lustre/atlas/world-shared/bip149/rp.session.titan-ext3.vivekb.017589.0004"

**Comment by jdakka** [comment]
when installing RMQ locally on Titan, need to set $PATH:

`export PATH=/ccs/home/jdakka/rabbitmq_server-3.7.3/sbin:$PATH`
`export PATH=/ccs/home/jdakka/otp_src_20.2/bin:$PATH`

**Comment by vivek-bala** [comment]
You can also set your rabbitmq config with ```hostname="dtn05.ccs.ornl.gov", port=30672```. This should allow multiple users to use the same rmq instance.

**Comment by jdakka** [comment]
I tried using `hostname='dtn05.ccs.ornl.gov', port=30672` from a `tmux` session on Titan in `/lustre/atlas/world-shared/bip149/` but it reports:  
```
Error setting RabbitMQ system: Connection to 160.91.205.4:30672 failed: [Errno 111] Connection refused
```

**Comment by jdakka** [comment]
@vivek-bala, as per instructions from @itomaldonado you need to provide the OpenShift pod's node's hostname. 

For now I'm using @itomaldonado's node hostname: openshift-node1.ccs.ornl.gov:30673 but when you get a chance can you provide yours?

**Comment by jdakka** [comment]
@vivek-bala regarding my local RMQ:

Even after setting the correct $PATH to point to my local `RMQ` it still tries aborts because it's trying to connect to your `RMQ`. You mentioned trying another login node, but this is probably not a long term solution, especially with all the dependencies to keep track of on Titan.  I think once we get OpenShift configured properly we should stick to that option?

**Comment by vivek-bala** [comment]
The one I have setup using openshift is hostname="dtn05.ccs.ornl.gov", port=30672. The same as what I mentioned above. I don't think you need to use the rabbitmq installed on the login nodes anymore.

**Comment by vivek-bala** [comment]
I'll check the status of that container to see why you can't connect to it.

**Comment by jdakka** [comment]
@vivek-bala I'm still connecting to `host=openshift-node1.ccs.ornl.gov, port=30673` in the meanwhile to run on Titan.

**Comment by vivek-bala** [comment]
Hey Jumana, continue to use the one you have right now. The RMQ container that I initially setup seems to have been deleted.

**Comment by itomaldonado** [comment]
@mturilli maybe they do, but I have one running on Openshift.ccs.ornl.gov:8443 that I created about a week after @vivek-bala and it is still running. I gave vivek access to my project/instance.

**Comment by vivek-bala** [comment]
@mturilli possibly, but it looked more like a glitch as the service was running but not the pod. The pod+service that @itomaldonado started has been up and seems to be stable for jumana. @jdakka can you confirm?

**Comment by vivek-bala** [comment]
> ORNL has deployed the production infrastructure at marble.ccs.ornl.gov

That's good to know though. Will keep that in mind.

**Comment by vivek-bala** [comment]
@jdakka Please close if this is no longer an issue.
