### ISSUE TITLE
EnTK Profiler throws "no attribute 'split'" error

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#218]
Error is below:

```
Traceback (most recent call last):
  File "run.py", line 89, in <module>
    print 'Workflow Execution time: ', profiler.duration(objects = Exchange, states=['SCHEDULING', 'EXECUTED'])
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/utils/profiler.py", line 157, in duration
    extracted_dict[obj][states[0]] = self._states_dict[states[0]][obj.split('.')[2].strip()][obj]
AttributeError: 'Pipeline' object has no attribute 'split'
```
[RE_Session.tar.gz](https://github.com/radical-cybertools/radical.entk/files/1768748/RE_Session.tar.gz)

Happy to help debug, let me know if you need further input

**Comment by vivek-bala** [comment]
IIRC Exchange is a Pipeline, right? You have 3 states for a pipeline: DESCRIBED, SCHEDULING and DONE. You are trying to specify a state that doesn't exist. See the list of states for each object here: http://radicalentk.readthedocs.io/en/latest/dev_docs/uml.html#state-diagram.

I agree the error can be improved though. If the issue is fixed for you, please leave the ticket open so that I remember to improve the error msg.

**Comment by SrinivasMushnoori** [comment]
Yes it is. However, running the following:

`print 'MD Execution time: ', profiler.duration(objects = mdtasks, states=['SCHEDULING', 'EXECUTED'])`

results in 
```
MD Execution time: 
Traceback (most recent call last):
  File "run.py", line 90, in <module>
    print 'MD Execution time: ', profiler.duration(objects = mdtasks, states=['SCHEDULING', 'EXECUTED'])
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/utils/profiler.py", line 157, in duration
    extracted_dict[obj][states[0]] = self._states_dict[states[0]][obj.split('.')[2].strip()][obj]
AttributeError: 'function' object has no attribute 'split'
```

`mdtasks` is a list of task UIDs. I believe `SCHEDULING` and `EXECUTED` are the correct states for tasks?
Running the `SCHEDULING` and `DONE` test now.

**Comment by andre-merzky** [comment]
this should be implemented in radical.analytics!

**Comment by SrinivasMushnoori** [comment]
@andre-merzky Apologies, but do you mean that I should be running this in analytics? I'm not clear on how I should be doing that...

**Comment by vivek-bala** [comment]
Hey Andre, the integration between EnTK and analytics is not yet complete so I have asked Srinivas to use the EnTK profiler for now. Once it is complete, everyone should be using analytics, I agree.

**Comment by vivek-bala** [comment]
@SrinivasMushnoori thanks for testing that. The profiler constructs a tree with all the objects and the methods of the profiler parse this tree to provide you the durations. The construction seems to be correct but the parsing is incorrect. I should be able to get to it in a few hours. I'll keep you posted.

**Comment by vivek-bala** [comment]
Hey Srinivas, try the fix/issue_218 branch. The multiple proc files were not being read while constructing the tree. 

> print p.duration(objects=['radical.entk.task.0000','radical.entk.task.0020','radical.entk.task.0040'],states=['SCHEDULING','DONE'])
63.7525000572

**Comment by SrinivasMushnoori** [comment]
I still get this message:
```
MD Execution time: 
Traceback (most recent call last):
  File "run.py", line 90, in <module>
    print 'MD Execution time: ', profiler.duration(objects = mdtasks, states=['SCHEDULING', 'EXECUTED'])
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/utils/profiler.py", line 157, in duration
    extracted_dict[obj][states[0]] = self._states_dict[states[0]][obj.split('.')[2].strip()][obj]
AttributeError: 'function' object has no attribute 'split'

```

`entk-version` shows:

```
0.6.0-entk-0.5-289-g74e2b97@fix-issue_218
```

**Comment by vivek-bala** [comment]
Can you add the value of mdtasks here, I'll test it too.

**Comment by SrinivasMushnoori** [comment]
This is odd...
`print mdtasks` prints the following:
```
<function mdtasklist at 0x7f19c2791ed8>
```

**Comment by vivek-bala** [comment]
objects only accepts a list of uids. These should be the uids of the objects that you want to profile.

**Comment by SrinivasMushnoori** [comment]
This has fixed the issue, thank you.
Leaving ticket open as requested.

**Comment by SrinivasMushnoori** [comment]
@vivek-bala Hi, despite us having addressed this yesterday, I now see this error:

```
MD Execution time: 
Traceback (most recent call last):
  File "run.py", line 91, in <module>
    print 'MD Execution time: ', profiler.duration(objects = mdtasks, states=['SCHEDULING', 'EXECUTED'])
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/utils/profiler.py", line 157, in duration
    extracted_dict[obj][states[0]] = self._states_dict[states[0]][obj.split('.')[2].strip()][obj]
KeyError: 'radical.entk.task.0006'
```

The `print mdtasks` statement gives the following output:

```
['radical.entk.task.0001', 'radical.entk.task.0002', 'radical.entk.task.0003', 'radical.entk.task.0004', 'radical.entk.task.0000', 'radical.entk.task.0001', 'radical.entk.task.0002', 'radical.entk.task.0003', 'radical.entk.task.0005', 'radical.entk.task.0006', 'radical.entk.task.0007', 'radical.entk.task.0008']
```

As evident from the print output, `radical.entk.task.0006` is very much present, unsure why Profiler is taking issue with that specific task. 

I can replicate this error for runs that are more than 1 cycle. 

RE session is [here](https://github.com/radical-cybertools/radical.entk/files/1775844/RE_Session.tar.gz)

**Comment by SrinivasMushnoori** [comment]
Upon further examination I notice that `radical.entk.task.0001` to `radical.entk.task.0003` occur multiple times in the above list. Unsure if this detail is relevant.

**Comment by vivek-bala** [comment]
This should be fixed in the devel branch. Can you test it out please?

**Comment by SrinivasMushnoori** [comment]
Just tested, it fails with 
```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from radical.entk import AppManager, ResourceManager, Profiler
ImportError: cannot import name Profiler
```

**Comment by vivek-bala** [comment]
Apologies for the confusion. There is no Profiler in EnTK anymore. You will have to use radical.analytics (feature/entk-integration branch). You can create a Session similar to how you do for RP only difference being the ``stype`` argument of the constructor. You can do the following:

```
entk_session = ra.Session(sid=<sid of the entk run, starts as re.session.*>, 
                                           stype='radical.entk', 
                                           src=<location of the folder(starts with re.session.*) containing the profiles>)
```

**Comment by SrinivasMushnoori** [comment]
The following:
```
sessionRE = ra.Session(sid   = 're.session.two.scm177.017611.0026',
                                       stype = 'radical.entk',
                                       src   = 're.session.two.scm177.017611.0026')
```

fails with

```
WARNING: profile "rp.session.two.scm177.017611.0027/umgr.0000.prof" not correctly closed.
Traceback (most recent call last):
 File "duration.py", line 35, in <module>
   src   = 're.session.two.scm177.017611.0026')
 File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/analytics/session.py", line 91, in __init__
   self._profile, accuracy, hostmap = re.utils.get_profile(src=self._src)
AttributeError: 'module' object has no attribute 'get_profile'
```

**Comment by vivek-bala** [comment]
I think your analytics version is not updated since that is not the name of the method: https://github.com/radical-cybertools/radical.analytics/blob/feature/entk-integration/src/radical/analytics/session.py#L91-L92. It needs to be:
```
self._profile, accuracy, hostmap = re.utils.get_session_profile(sid=sid, src=self._src)
self._description = re.utils.get_session_description(sid=sid, src=self._src)
```

**Comment by SrinivasMushnoori** [comment]
My `radical-stack` is:

```
python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/EnTK0.6_env

  radical.analytics    : v0.45.2-101-g8358b08@devel
  radical.entk         : 0.6.1-entk-0.5-306-ga1887fc@devel
  radical.pilot        : 0.47.1
  radical.utils        : 0.47.3
  saga                 : 0.47-v0.46-36-g307daeb7@devel

```

I believe this is the latest?

**Comment by vivek-bala** [comment]
You have to use the feature/entk-integration/ branch of analytics.

**Comment by SrinivasMushnoori** [comment]
I see. Using that branch gives me the following:

```
Traceback (most recent call last):
  File "session_duration_latest.py", line 35, in <module>
    src   = 're.session.two.scm177.017611.0026')
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/analytics/session.py", line 91, in __init__
    self._profile, accuracy, hostmap = re.utils.get_session_profile(sid=sid, src=self._src)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/utils/prof_utils.py", line 77, in get_session_profile
    raise Error(text='No profiles found at %s' % src)
NameError: global name 'Error' is not defined

```

It appears that it cannot find the profiles in the directory, but I can verify that the profiles are there and are non empty.

**Comment by vivek-bala** [comment]
I believe 'src' should point to the **path** of the folder with the profiles, i.e. excluding the name of the folder. Can you try that please?

**Comment by SrinivasMushnoori** [comment]
Alright, that worked. 

I'm doing the following:
```
    tasks=sessionRE.filter(etype='task', inplace=False)
    task_durations = tasks.duration([re.states.SCHEDULED, re.states.EXECUTED])
    pprint.pprint(task_durations)

```


Fails with:
```
    task_durations = tasks.duration([re.states.SCHEDULED, re.states.EXECUTED])
AttributeError: 'module' object has no attribute 'EXECUTED'
```

Does the state no longer exist? The documentation seems to imply that it does...
http://radicalentk.readthedocs.io/en/latest/dev_docs/uml.html#state-diagram

**Comment by SrinivasMushnoori** [comment]
Running this with `re.states.COMPLETED` appears to work.

My RA script is as follows:
```
    sessionRE = ra.Session(sid   = str(sys.argv[1]),
                           stype = 'radical.entk',
                           src   = pwd)


    tasks=sessionRE.filter(etype='task', inplace=False)
    task_durations = tasks.duration([re.states.SCHEDULED, re.states.COMPLETED])
    pprint.pprint(task_durations)

```
If I am to provide the above with UID's to filter, I need to be able to output the task UID's to a list or other data structure. However, when I try the following (Line 203):
https://github.com/SrinivasMushnoori/RepEx_3.0/blob/master/src/radical/repex/SyncEx.py#L203

What I find is a large list of "None" entries like so:

```
None
None
None
None
...
...
```
It appears that the units do not have UID's at all...

**Comment by vivek-bala** [comment]
All the UIDs are assigned during execution. So you can get the uids of the tasks once you get control back after execution. This was the reason you had to switch to using object names (on which you have control prior to execution) as opposed to object uids. 

So post execution, you can do something like the following:
```
task_uid_map = dict()
for task in md_tasks:
    task_uid_map[task.name] = task.uid

def get_task_uids(task_names_list):
    return [task_uid_map[name] for name in task_names_list]
   
tasks=sessionRE.filter(etype='task', inplace=False, uid=get_task_list(my_filtered_task_names)
```

Hope that helps.

**Comment by vivek-bala** [comment]
All of this (and the issue with the underscore) will be covered in documentation in the next point release.

**Comment by SrinivasMushnoori** [comment]
Here's what I'm doing:

```
    mdtasks  = synchronousExchange.mdtasklist
    extasks  = synchronousExchange.extasklist

    #print mdtasks                                                                                                                                                         
    #print extasks                                                                                                                                                         

    pwd = os.getcwd()
    session = ra.Session(sid   = './%s'%appman.sid,
                         stype = 'radical.entk',
                         src   = pwd)
    task_uid_map = dict()
    for task in mdtasks:
        task_uid_map[task.name] = task.uid

    def get_task_uids(task_names_list):
        return [task_uid_map[name] for name in task_names_list]



    tasks=session.filter(etype='task', inplace=False, uid=get_task_uids(mdtasks))
    task_durations = tasks.duration([re.states.SUBMITTED, re.states.COMPLETED])
    pprint.pprint(task_durations)
```

It fails at `task_uid_map[task.name] = task.uid` with the following error:


`AttributeError: 'str' object has no attribute 'uid'`

It appears that it's reading task names as strings rather than task objects?

**Comment by vivek-bala** [comment]
I think that is because mdtasklist stores the name of the tasks (https://github.com/SrinivasMushnoori/RepEx_3.0/blob/master/src/radical/repex/SyncEx.py#L202). You can expect ```task.name``` to fail as well since task is a a string not an object.

**Comment by vivek-bala** [comment]
Yea, that will give you access to all the task attributes.

**Comment by SrinivasMushnoori** [comment]
Just tested it:

```
Traceback (most recent call last):
  File "run.py", line 143, in <module>
    tasks=session.filter(etype='task', inplace=False,  uid=get_task_uids(mdtasks))
  File "run.py", line 139, in get_task_uids
    return [task_uid_map[name] for name in task_names_list]
KeyError: <SyncEx.AMBERTask object at 0x7f6b00c94c90>

```

**Comment by SrinivasMushnoori** [comment]
This works!
Closing this ticket now. Thank you!
