### ISSUE TITLE
Symlinks break if using devel branch 

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#221]
So initially I thought this was related to https://github.com/radical-cybertools/radical.entk/issues/213 because this involves links behaving incorrectly, but now it has become a bit more clear that they are probably not related. 

Running with branch `0.6.0-entk-0.5-289-g74e2b97@master` runs the job to completion. The logfiles/pilot sandbox are:
[RE session](https://github.com/radical-cybertools/radical.entk/files/1816498/symlinks_breaking_re_session.tar.gz)
[RP Session](https://github.com/radical-cybertools/radical.entk/files/1816499/symlinks_breaking_rp_session.tar.gz)
[Pilot Sandbox](https://drive.google.com/open?id=10xjU06j-rgqbhTmzMfyH85UGnaut8-vc)

Running with branch `0.6.1-entk-0.5-306-ga1887fc@devel` causes the job to fail because links in the Exchange stage are broken. Logs/sandboxes are below:

[RE Session](https://github.com/radical-cybertools/radical.entk/files/1816561/symlinks_now_breaking_re_session.tar.gz)
[RP Session](https://github.com/radical-cybertools/radical.entk/files/1816566/symlinks_now_breaking_rp_session.tar.gz)
[Pilot Sandbox](https://github.com/radical-cybertools/radical.entk/files/1816569/sandbox_broken_symlinks.tar.gz)

Please let me know if anything else is needed from me, happy to help investigate/debug.

**Comment by vivek-bala** [comment]
Can you add the link to the repex script(+branch) as well.

**Comment by SrinivasMushnoori** [comment]
https://github.com/SrinivasMushnoori/RepEx_3.0/tree/master/src/radical/repex
This is the RepEx script. run.py and SyncEx.py.

As for the links pointing to the incorrect places, if I understand correctly, I cannot control what units they point to, I can only control what pipeline/stage/task UID it points to....How does it work with the older branch, though?

**Comment by andre-merzky** [comment]
@vivek-bala: just to make sure we are on the same page: right now the fix is expected to happen on the EnTK level, is that correct?

**Comment by vivek-bala** [comment]
Yup, I think I know what the fix is. Srinivas, not sure if you remember from our discussion during the adaptivity call. In devel (basically EnTK version >=0.6.2), you need to set Pipeline, Stage and Task names and use them while referring the data within tasks. Something like the following:

```
p = Pipeline()
p.name = 'p1'
s = Stage()
s.name = 's1'
t = Task()
t.name = 't1'
s.add_tasks(t)
p.add_stages(s)
task_ref = '$Pipeline_%s_Stage_%s_Task_%s'%(p.name, s.name, t.name) # instead of the uids
```

What I am surprised on is that this did not report any error and mapped to the first task. Let me check the unit tests again.

**Comment by SrinivasMushnoori** [comment]
Doing that gives me the following:
```
2018-03-19 00:07:05,621: radical.entk.task_processor: task-manager                    : MainThread     : ERROR   : Failed to resolve placeholder $Pipeline_init_pipeline_Stage_untar_stg_Task_untar_tsk/inpcrd, error: Value for attribute pl
aceholder of object length incorrect. Expected value $Pipeline_{pipeline.uid}_Stage_{stage.uid}_Task_{task.uid} or $SHARED, but got ['$Pipeline', 'init', 'pipeline', 'Stage', 'untar', 'stg', 'Task', 'untar', 'tsk'].
2018-03-19 00:07:05,621: radical.entk.task_processor: task-manager                    : MainThread     : ERROR   : Failed to get input list of files from task, error: Value for attribute placeholder of object length incorrect. Expected v
alue $Pipeline_{pipeline.uid}_Stage_{stage.uid}_Task_{task.uid} or $SHARED, but got ['$Pipeline', 'init', 'pipeline', 'Stage', 'untar', 'stg', 'Task', 'untar', 'tsk'].
2018-03-19 00:07:05,621: radical.entk.task_processor: task-manager                    : MainThread     : ERROR   : CU creation failed, error: Value for attribute placeholder of object length incorrect. Expected value $Pipeline_{pipeline.
uid}_Stage_{stage.uid}_Task_{task.uid} or $SHARED, but got ['$Pipeline', 'init', 'pipeline', 'Stage', 'untar', 'stg', 'Task', 'untar', 'tsk'].
2018-03-19 00:07:05,621: radical.entk.task_manager.0000: task-manager                    : MainThread     : ERROR   : Task task.0001 submission failed, error: Value for attribute placeholder of object length incorrect. Expected value $Pi
peline_{pipeline.uid}_Stage_{stage.uid}_Task_{task.uid} or $SHARED, but got ['$Pipeline', 'init', 'pipeline', 'Stage', 'untar', 'stg', 'Task', 'untar', 'tsk'].
```

My task description is as follows:

```
        p = Pipeline()
        p.name = 'init_pipeline'

        md_dict    = dict() #Bookkeeping
        tar_dict   = dict() #Bookkeeping
         #Create Tarball of input data
        tar = tarfile.open("Input_Files.tar","w")
        for name in ["prmtop", "inpcrd", "mdin"]:
            tar.add(name)
        tar.close()
        #Create Untar Stage
        untar_stg = Stage()
        untar_stg.name = 'untar_stg'
        #Untar Task
        untar_tsk                        = Task()
        untar_tsk.name              = 'untar_tsk'
        untar_tsk.executable      = ['python']
        untar_tsk.upload_input_data = ['untar_input_files.py','Input_Files.tar']
        untar_tsk.arguments         = ['untar_input_files.py','Input_Files.tar']
        untar_tsk.cores             = 1
        untar_stg.add_tasks(untar_tsk)
        p.add_stages(untar_stg)
        tar_dict[0] = '$Pipeline_%s_Stage_%s_Task_%s'%(p.name, untar_stg.name, untar_tsk.name)

 ```
All other stages/tasks are defined in an identical manner. 

The error suggests to me that it expects UIDs and not names.

**Comment by vivek-bala** [comment]
Thanks for checking this Srinivas! The objects cannot have an underscore in the name.  This needs to be documented for now. Need to think of alternative naming schemes.

**Comment by vivek-bala** [comment]
This is documented in devel. Also raises an error when creating an object with a separator in the name. In 0.7.0 onwards, internal separators will be ',' and '_'. Thanks Srinivas.
