### ISSUE TITLE
Check performance of EnTK with RabbitMQ running as a user process vs docker

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#222]

**Comment by lee212** [comment]
Not sure this is in our milestone as we don't provide entk in docker images.

**Comment by mturilli** [comment]
This was about comparing the performance of EnTK when running RabbitMQ either as a system-wide server or in a container. While we still use RabbitMQ in a container on `two.radical-project`, I don't think such a performance comparison is particularly useful anymore.
