### ISSUE TITLE
states different between documentation and log files

### ISSUE THREAD

**Issue by jonatanYanovsky** [radical-cybertools/radical.entk#223]
I'm looking at the pst states here:
https://github.com/radical-cybertools/radical.entk/blob/master/src/radical/entk/states.py#L82

These are not the same as the ones in appmanager. Specifically, there is no "INITIAL" "SYNCHRONIZING" "SYNCHRONIZED" and "COMPLETED" shows up as executed.

**Comment by vivek-bala** [comment]
Fixed and added for the next release.
