### ISSUE TITLE
EnTK error on get_started.py

### ISSUE THREAD

**Issue by lewandowskijake1123** [radical-cybertools/radical.entk#227]
I have a virtual environment with the ensemble toolkit installed. However, I cannot run "get_started.py" or even the example from the basic example page. I get the following error for each of the programs :

File "get_started.py", line 61, in <module>
    cluster.allocate()
  File "/home/jake/venv/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 198, in allocate
    self._session = radical.pilot.Session(database_url=self._database_url)
TypeError: __init__() got an unexpected keyword argument 'database_url'

I have been trying to debug this, but can't find out the solution. Would you happen to know how I can fix this?

I am using version 0.4.6 and running on Ubuntu.
[verbose.log](https://github.com/radical-cybertools/radical.entk/files/1958191/verbose.log)

**Comment by vivek-bala** [comment]
Hey Jake, apologies for the delay. I think you might be using an old version of EnTK.
Please use/follow the instructions at http://radicalentk.readthedocs.io/en/latest/.
