### ISSUE TITLE
EnTK does not show clean weak scalability in the RepEx use case (python notebook inside)

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#229]
Hi folks:

https://github.com/SrinivasMushnoori/RepEx_3.0/blob/master/scaling/md_scheduling_improved/EnTK_Profiles.ipynb

This is the python notebook detailing the scaling behaviour of RepEx/EnTK. Weak scaling is not at all clean, and we are trying to suss out why. It is not immediately clear where the bottleneck is, but all the raw data is right there in that directory. 

My `radical-stack` is:

```
                                                                                                                                                                           │·································································
  python               : 2.7.12                                                                                                                                            │·································································
  pythonpath           :                                                                                                                                                   │·································································
  virtualenv           : /home/scm177/VirtualEnvs/EnTK0.6_env                                                                                                              │·································································
                                                                                                                                                                           │·································································
  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration                                                                                                     │·································································
  radical.entk         : 0.6.2-0.6.2-1-g81da461@master                                                                                                                     │·································································
  radical.pilot        : 0.47.10                                                                                                                                           │·································································
  radical.utils        : 0.47.4-merge-pre_gpu-14-ga2181d6@devel                                                                                                            │·································································
  saga                 : 0.47.3-merge-pre_gpu@master                                                                                                                       │·································································
                                                          
```
Feel free to let me know if you need more info.

**Comment by SrinivasMushnoori** [comment]
Update:
https://github.com/SrinivasMushnoori/RepEx_3.0/blob/master/scaling/stage_exec_times/EnTK_Profiles.ipynb

@vivek-bala as you suggested, here are the stage TX's plotted. This is interesting. Stragglers?
@andre-merzky comments?

All profiles, as usual, are in the parent directory.

**Comment by shantenujha** [comment]
There is a lot more to unpack before you go looking for (or talking about) stragglers.

**Comment by SrinivasMushnoori** [comment]
Granted, not looking for stragglers. 
Here's what I find with Bag of Tasks mode: https://github.com/SrinivasMushnoori/RepEx_3.0/blob/master/scaling/BoT_2/Profiles.ipynb

As seen, there is a slight uptick at a replica count as low as 128. Now in BoT mode since the slope is significant, doing multiple exchanges (10 to 100), in light of this data, I'm not surprised that the TTX shoots up from 8-128 replicas. I'm doing some more digging. In the interim, please give me your thoughts?

**Comment by vivek-bala** [comment]
I think we discussed the notebook in person or on slack. Do you have the required understanding? Let me know. If this issue is resolved, please do close it.

**Comment by SrinivasMushnoori** [comment]
I believe we do have an understanding of the issue. The difference between the 8 and 128 replica systems is ~50 seconds. In the same notebook, if you scroll down, we find from the distribution of MD_TX that min-max is about 50 seconds. This strongly implies that the apparent "loss" in performance is due to heterogeneity in execution times of the MD tasks in a given stage.
