### ISSUE TITLE
Adding data example has typo

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#234]
The `adding_data.py` example as well as the [documentation](http://radicalentk.readthedocs.io/en/latest/user_guide/adding_data.html) has a typo.

Instead of writing `$Pipeline_%s_Stage_%s_Task_%s/output.txt'%(p.uid, s1.uid, t1.uid)`, it writes: `$Pipline_%s_Stage_%s_Task_%s/output.txt'%(p.uid, s1.uid, t1.uid)`

**Comment by vivek-bala** [comment]
Fixed in devel. Thanks!
