### ISSUE TITLE
Custom EnTK application namings

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#238]
I would like to request the ability to use the `AppManager`  name as part of the folders created by EnTK during execution.

This way, I will be able to quickly distinguish folders on the client and remote resource that belong to the same run without having to parse a file and try to remember everything.

**Comment by vivek-bala** [comment]
I am moving this to the next point release. Requires more discussion in terms of application names, session ids, location of profiles.

**Comment by vivek-bala** [comment]
https://github.com/radical-cybertools/radical.entk/pull/248

**Comment by vivek-bala** [comment]
Thanks Giannis! Reviewed and merged the PR.
