### ISSUE TITLE
output of logging

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.entk#24]
What is the intended audience for the logging? It seems to be more of a debug log than informative to users whats going on.

**Comment by andre-merzky** [comment]
I would like to remind folx that we have a radical.utils.reporter class for structured output targeted at user consumption.  For a usage example, see

https://github.com/radical-cybertools/radical.utils/blob/master/radical/utils/reporter.py#L266

**Comment by oleweidner** [comment]
Hm, I thought this would actually help users to understand what's going on:

```
2015:01:19 20:48:50 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Pre_loop completed.
2015:01:19 20:48:53 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for simulation iteration 1.
2015:01:19 20:48:53 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for simulations in iteration 1 to complete.
2015:01:19 20:49:00 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Simulations in iteration 1 completed.
2015:01:19 20:49:04 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for analysis iteration 1.
2015:01:19 20:49:04 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for analysis tasks in iteration 1 to complete.
2015:01:19 20:49:21 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Analysis in iteration 1 completed.
2015:01:19 20:49:24 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for simulation iteration 2.
2015:01:19 20:49:24 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for simulations in iteration 2 to complete.
2015:01:19 20:49:34 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Simulations in iteration 2 completed.
2015:01:19 20:49:38 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for analysis iteration 2.
2015:01:19 20:49:38 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for analysis tasks in iteration 2 to complete.
2015:01:19 20:49:56 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Analysis in iteration 2 completed.
2015:01:19 20:49:59 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for simulation iteration 3.
2015:01:19 20:49:59 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for simulations in iteration 3 to complete.
2015:01:19 20:50:12 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Simulations in iteration 3 completed.
2015:01:19 20:50:19 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for analysis iteration 3.
2015:01:19 20:50:19 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for analysis tasks in iteration 3 to complete.
2015:01:19 20:50:42 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Analysis in iteration 3 completed.
2015:01:19 20:50:46 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for simulation iteration 4.
2015:01:19 20:50:46 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for simulations in iteration 4 to complete.
2015:01:19 20:50:58 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Simulations in iteration 4 completed.
2015:01:19 20:51:04 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for analysis iteration 4.
2015:01:19 20:51:04 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for analysis tasks in iteration 4 to complete.
2015:01:19 20:51:31 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Analysis in iteration 4 completed.
2015:01:19 20:51:31 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Deallocating resource.
```

Could you give me some pointers how would you change the log messages in order to make them more useful?

**Comment by marksantcroos** [comment]
> On 19 Jan 2015, at 20:57 , Ole Weidner <notifications@github.com> wrote:
> Hm, I thought this would actually help users to understand what's going on:
> 
> 2015:01:19 20:48:50 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Pre_loop completed.
> 2015:01:19 20:48:53 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for simulation iteration 1.
> 2015:01:19 20:48:53 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for simulations in iteration 1 to complete.
> 2015:01:19 20:49:00 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Simulations in iteration 1 completed.
> 2015:01:19 20:49:04 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for analysis iteration 1.
> 2015:01:19 20:49:04 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for analysis tasks in iteration 1 to complete.
> 2015:01:19 20:49:21 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Analysis in iteration 1 completed.
> 2015:01:19 20:49:24 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for simulation iteration 2.
> 2015:01:19 20:49:24 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for simulations in iteration 2 to complete.
> 2015:01:19 20:49:34 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Simulations in iteration 2 completed.
> 2015:01:19 20:49:38 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for analysis iteration 2.
> 2015:01:19 20:49:38 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for analysis tasks in iteration 2 to complete.
> 2015:01:19 20:49:56 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Analysis in iteration 2 completed.
> 2015:01:19 20:49:59 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for simulation iteration 3.
> 2015:01:19 20:49:59 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for simulations in iteration 3 to complete.
> 2015:01:19 20:50:12 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Simulations in iteration 3 completed.
> 2015:01:19 20:50:19 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for analysis iteration 3.
> 2015:01:19 20:50:19 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for analysis tasks in iteration 3 to complete.
> 2015:01:19 20:50:42 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Analysis in iteration 3 completed.
> 2015:01:19 20:50:46 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for simulation iteration 4.
> 2015:01:19 20:50:46 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for simulations in iteration 4 to complete.
> 2015:01:19 20:50:58 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Simulations in iteration 4 completed.
> 2015:01:19 20:51:04 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Submitted tasks for analysis iteration 4.
> 2015:01:19 20:51:04 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Waiting for analysis tasks in iteration 4 to complete.
> 2015:01:19 20:51:31 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Analysis in iteration 4 completed.
> 2015:01:19 20:51:31 7183   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Deallocating resource.
> 
> Could you give me some pointers how would you change the log messages in order to make them more useful?

These look not too bad indeed, I guess my experience was based on the pipeline/bag pattern.

Regardless, I think there should be more focus on the last "column", and less on the initial ones.
For end-users, SNR is rather low.

**Comment by vivek-bala** [comment]
Old. We have a reporter for user level verbosity.
