### ISSUE TITLE
Insufficient system resources: read from process failed

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.entk#241]
Hello All, I was trying to submit a job to xsede.comet and the following error popped up :
```

: Thread-1       : ERROR   : Exception in job monitoring thread: Insufficient system resources: Insufficient system resources: read from process failed '[Errno 5] Input/output error' : (0:RUNNING:
29020.0:DONE:0
15374.0:RUNNING:
15374.0:DONE:0
3263.0:RUNNING:
3263.0:DONE:0
20801.0:RUNNING:
20801.0:DONE:0
4893.0:RUNNING:
4893.0:DONE:0
17674.0:RUNNING:
17674.0:DONE:0
Shared connection to comet.sdsc.xsede.org closed.
) (()) (/home/aymen/.local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +64 (translate_exception)  :  e = se.NoSuccess ("Insufficient system resources: %s" % cmsg))
2018-06-14 23:58:58,704: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : ERROR   : Cancel job monitoring for ssh://comet.sdsc.xsede.org/ 
```

radical-stack:
```
  python        : 2.7.12
  pythonpath    :
  virtualenv    :

  radical.entk        : 0.6.2
  radical.pilot       : 0.47.12
  radical.utils       : 0.47.4
  saga                : 0.47.5
```

**Comment by andre-merzky** [comment]
Hi @AymenFJA - is the problem reproducible on repeated runs?  For how long is your application active when the error pops up?

**Comment by AymenFJA** [comment]
Hi @andre-merzky , actually yes the problem is reproducible, the application stays active for the unknown amount of time until I force the application to stop (Ctrl+C).

**Comment by AymenFJA** [comment]
Sorry, it runs for (40 sec to 1 min.)  and then it fails. 
I am using :
Jetstream cloud VM 
OS: Ubuntu 16.04.4

'''res_dict = {

            'resource': 'xsede.comet',
            'walltime': 10,
            'cores': 1,
            'project': 'unc100',
            'queue':'debug',
            'schema': 'gsissh'
    }
'''
Also i used 
```
res_dict = {

            'resource': 'xsede.comet',
            'walltime': 10,
            'cores': 1,
            'project': 'unc100',
            'queue':'debug',
            'schema': 'ssh'
    }
```
and i am getting the same error .

**Comment by vivek-bala** [comment]
Can you run ```ps faux | grep rp``` on your VM and share the output here please?

**Comment by AymenFJA** [comment]
'''
$ ps faux | grep rp
aymen    16971  0.0  0.0  12948  1024 pts/3    S+   12:58   0:00              \_ grep --color=auto rp
'''

**Comment by vivek-bala** [comment]
Thanks. I think Andre might know the source of the error, can you provide him the complete EnTK script that you are running. Feel free to paste the link in gist.github.com and share the link here.

In the meanwhile, can you delete ```$HOME/.saga``` and try again? It has worked on a few occasions for me.

**Comment by AymenFJA** [comment]
This is the link for the script 

[https://gist.github.com/AymenFJA/f275e315b2aa3790f4517b8acfceda6f](url)

**Comment by vivek-bala** [comment]
Is this issue resolved or are you still facing this error?

**Comment by AymenFJA** [comment]
The issue is solved, I will close it now thanks.
