### ISSUE TITLE
RTS default never read from config file

### ISSUE THREAD

**Issue by kristofarkas** [radical-cybertools/radical.entk#244]
https://github.com/radical-cybertools/radical.entk/blob/3a6ad841a8bd3a11e8dafdf8352cf5fcf235b70a/src/radical/entk/appman/appmanager.py#L105-L107

The last line indicates that an `rts` default can be read in from the config file, therefore leaving it (`rts`) `None` is okay. But the line above checks if it is in that list, and if it isn't (which is the case if we leave it `None`) then it raises an error. Is this the desired behaviour?

**Comment by vivek-bala** [comment]
You are right on that! I fixed it locally, but the fix didn't get pushed. Thanks!
