### ISSUE TITLE
Submit EnTK and ICEBERG projects to the Earthcube tools inventory

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#252]
Dropped an email to Lynne asking about the status and if any additional information is required for both projects.

**Comment by vivek-bala** [comment]
EnTK is up on the tools inventory (https://www.earthcube.org/tools-inventory). Giannis, if/when the ICEBERG project is uploaded, please close this ticket.

**Comment by iparask** [comment]
It's right next to EnTK. Closing

**Comment by vivek-bala** [comment]
Ah okay. I thought there was something that you were submitting in addition to what Heather submitted. I think the question was in my email :)
