### ISSUE TITLE
filter method in analytics-feature-entk 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.entk#253]
In the analytics [example](https://github.com/radical-cybertools/radical.entk/blob/master/examples/analytics/02_session_get.py#L36) is incorrect. It should be `session.filter(etype = 'stage', uid = 'stage.0000')`

**Comment by vivek-bala** [comment]
Thanks! Will patch it in the next release.

**Comment by vivek-bala** [comment]
Added whole new examples with new data set. Updated RTD as well.
