### ISSUE TITLE
inconsistency between copy_input_data and shared_data

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.entk#258]
rman.shared_data copies as expected only the file, not the full path:
example: './inp_files/file.pdb' to staging_area/file.pdb

But using that full path further doesn't work:
entk.task.link_input_data=['$SHARED/inp_files/file.pdb > file.pdb']
I understand the logic, but if I use  './inp_files/file.pdb' as a variable, then it's an misleading. Maybe can there be a warning in the documentation?

**Comment by euhruska** [comment]
this leads to non-fatal errors, so it's harder to debug

**Comment by vivek-bala** [comment]
rman.shared_data when pointing to a file simply copies the file and not the parent data
structure (there is no way of generalizing how many levels of the parent data need to
be transferred).
If you specify rman.shared_data to a folder (in this case './inp_files'), it should copy the 
entire folder into $SHARED and then 
```
entk.task.link_input_data=['$SHARED/inp_files/file.pdb > file.pdb']
```
 can be used.

Does that help?

**Comment by euhruska** [comment]
I adjusted my code to this, so I guess it's ok
