### ISSUE TITLE
How to recover from a failed task?

### ISSUE THREAD

**Issue by kristofarkas** [radical-cybertools/radical.entk#260]
What is the mechanism by which one can recover from a failed task?

**Specific scenario:** some of the tasks in a stage _might_ fail due to some random factor. If they do then all consecutive tasks in the following stages are useless, because they would have used the output of this failed task as input. I would like to at least retry the task, or even better, alter some of the attributes and rerun. 

Is this possible in EnTK?

**Comment by kristofarkas** [comment]
Just noticed the `resubmit_failed` attribute of `AppManager`. Does this resubmit failed tasks once? Or `reattempts` number of times?

This could work, but more fine grained settings would be better? Maybe the adaptive API could be the answer.

**Comment by vivek-bala** [comment]
The default currently: resubmit_failed resubmits tasks indefinitely till they succeed. The ```reattempts``` is for component and pilot failures only. What kind of settings are you looking for? If they are not covered and minor we can try to include it in one of the next releases.

**Comment by kristofarkas** [comment]
The idea is to build some kind of fault tolerance into htbac. Simulations fail sometimes seemingly at random, and usually retrying is enough.

There are multiple ways to go about this, but here is the case for NAMD:

During equilibration the volume of the system changes to accommodate to the pressure. If the volume changes too much relative to the start of the simulation NAMD just fails and exists. That is why we have 5 steps to incrementally decrease the volume until equilibrated. Then we can run the long simulation without worry that the volume will change and NAMD fail. What I had in one of my runs recently is that the simulation still failed and needed more than 5 steps to equilibrate. Usually this was enough, not in this case for this physical system. 

There is another completely different source of failure. During simulation the system can get into a state where the energy blows up. Then the solution is to backtrack X steps and retry. This is harder and would require implementation on the htbac level. 

Anyways to answer your question: a nice feature would be for EnTK to replace a failed task with a new one, that is provided by the user. For example if taks x failed the run this other task y instead or something like this.

**Comment by kristofarkas** [comment]
Then we could implement arbitrary fault tolerance depending on what the state of the failed task is.

**Comment by vivek-bala** [comment]
Great, thanks for the context. You're right in that you can create a new task if a task fails with the adaptive features. If you want to resubmit the same task as the one that failed, you can just use resubmit_failed.

**Comment by vivek-bala** [comment]
I am closing this ticket since there are no follow up questions. But if there are any more clarifications required, please do reopen the ticket.
