### ISSUE TITLE
Flag that allows to clean sandbox

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#261]
This is a feature request. Can there be a flag that allows the user to clean the sandbox on remote?

My applications create GBs of intermediate data and can easily exceed quotas on resources unless they are cleaned after the execution

**Comment by andre-merzky** [comment]
RP actually has a flag for this - but I am not sure about the current implementation state (see [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/compute_pilot_description.py#L115))

**Comment by vivek-bala** [comment]
Yes, but it needs to be exposed to an EnTK user as well. Currently, the
cleanup is set to False by default.

**Comment by vivek-bala** [comment]
Added capability to specify the cleanup when creating the AppManager object.
```
AppManager(rts_config = {"sandbox_cleanup": false, "db_cleanup": false})
```

Note that the AppManager accepts values from a config file with the following 
default values:
```
{
    "hostname": "localhost",
    "port": 5672,
    "reattempts": 3,
    "resubmit_failed": false,
    "autoterminate": true,
    "write_workflow": false,
    "rts": "radical.pilot",
    "rts_config": {
                    "sandbox_cleanup": false,
                    "db_cleanup": false
                },
    "pending_qs": 1,
    "completed_qs": 1,
    "rmq_cleanup": true
}
```
These values are overwritten with any arguments passed to the AppManager object.
