### ISSUE TITLE
radical utils API change

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#263]

**Comment by vivek-bala** [comment]
https://github.com/radical-cybertools/radical.utils/issues/139

**Comment by andre-merzky** [comment]
I would not mind closing this ticket for the time being, as it will take quite a while until this is addressed in RU (its a low priority item).  When the rename happens, then we'll keep RU backward compatible for a while and will print/log a deprecation warning, which should give sufficient time to the dependent layers to make the switch (the switch will be simple).
