### ISSUE TITLE
Move rp.session into re.session

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#265]
This helps users automatically associate the two and not have to manually keep track of which rp session belongs to which re session.

**Comment by andre-merzky** [comment]
You could still consider using the *same* session ID for RE and RP.

**Comment by vivek-bala** [comment]
Yes true. We could create re.session.X and rp.session.X. Maintaining the folder hierarchy will be useful (and meaningful) as well.

**Comment by vivek-bala** [comment]
The latter suggestion has been incorporated in https://github.com/radical-cybertools/radical.entk/pull/248
