### ISSUE TITLE
Accessing pipeline/stage/task states in an EnTK script

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#273]
Hi, I'm working on an EnTK script with adaptivity. As part of `func_condition` as per [this](https://radicalentk.readthedocs.io/en/latest/adv_examples/adapt_ta.html) section of the documentation, I need to know the states of various entities (mostly stages, but also tasks or pipelines in some cases). The output of `func_condition` depends on the states of these entities. I'm attempting to do something like this:

```
if state=re.states.DONE:
    replica.state = 'W'
    do something 
else

    do something else
```

Assistance is appreciated.

**Comment by vivek-bala** [comment]
You can do task.state, stage.state or pipeline.state to get the states of the entities. Does that help?

**Comment by SrinivasMushnoori** [comment]
And if I want to identify a specific task called `md_tsk` I do:

```
if md_tsk.state = 'DONE':
    so_something()

```

Correct?

**Comment by vivek-bala** [comment]
Assuming md_task is a Task object, yes, that's correct.

**Comment by SrinivasMushnoori** [comment]
Thanks, that helps. Closing
