### ISSUE TITLE
Accessing specific task sandboxes in EnTK

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#274]
Hi,

My EnTK script is [here](https://github.com/SrinivasMushnoori/repex/blob/devel/old_drivers/driver.py)

In lines 78 and 79 I define a replica sandbox, i.e. the sandbox of the task that untars all necessary files on the agent side. Lines 98-105 are where I try to refer to this sandbox. 

Now if you notice line 80 is `print replica_sandbox` where I try to print the string that refers to the sandbox, but it prints `None` 

Essentially, the reference to the first task's sandbox seems to be failing. Thanks!

**Comment by SrinivasMushnoori** [comment]
Update: the same file run in a fresh environment and after a fresh `git pull` makes it so that the `print replica_sandbox` line prints:
`$Pipeline_untarPipe_Stage_untarStg_Task_untarTsk`

Which appears to be the correct placeholder, however the tasks fail with: 
`  Error opening unit    7: File "/mdinfo-3-1" exists (use -O to overwrite)`

The way "/mdinfo-3-1" is written indicates that the file is somehow in a root directory. 
The `.sh` file in the unit sandbox of the agent side has the following run command:

```

# The command to run
prof cu_exec_start
/home/scm177/mantel/AMBER/amber14/bin/sander "-O" "-i" "mdin-3-0" "-p" "prmtop" "-c" "inpcrd" "-o" "out-3-1" "-r" "$Pipeline_untarPipe_Stage_untarStg_Task_untarTsk/restrt-3-1" "-x" "mdcrd-3-1" "-inf" "$Pipeline_untarPipe_Stage_untarStg_Task_untarTsk/mdinfo-3-1" 
```

It looks correct, but unsure where exactly the placeholder points to.

**Comment by vivek-bala** [comment]
Hey, you can currently only use task location references (i.e. replica_sandbox) for data movement
(i.e. link_input_data, copy_input_data, etc.) and not for arguments. If you move the data to the task directory, you can specify the arguments as if the data is in the current location of the task.

Does that help/make sense?

**Comment by SrinivasMushnoori** [comment]
I...think?
So what you're saying is, I cannot use location references to write to the sandbox of another task. Is this correct?

**Comment by vivek-bala** [comment]
What do you mean by 'write to the sandbox' ?

Basically, in your case, you can't use replica_sandbox for specifying task arguments. You can use them only for link_input_data and copy_input_data.

**Comment by SrinivasMushnoori** [comment]
Yes so  I cannot set it up so that the output of task 9 is written to the sandbox of task 0 (which is the replica sandbox), since I have to use the location reference in specifying the path to write to in the arguments. I effectively have to revert to the old method of maintaining a dictionary that keeps track of where each replica's outputs are located and look that up every time in order to link_input_data. I was hoping to avoid that method since it's very, very cumbersome, I suppose I'll just bite the bullet and do it.

**Comment by mturilli** [comment]
This may deserve some more discussion. I do not think I exactly understand what Srinivas is trying to do but, in principle, could EnTK know about all the input/output files for all the units?

**Comment by SrinivasMushnoori** [comment]
Hi @mturilli , what I am trying to do is is to allow the outputs of one unit to be written to the sandbox of another, essentially. Here's why I think it's useful for me:

- Currently, in RepEx, every time a set replicas complete an Exchange stage they communicate back to client side with some information that is required by EnTK to instantiate the next set of MD's
- This information basically consists of the locations of all input files (which are the output files of tasks already completed). 
- This is workable, and in the case of synchronous exchange it is no problem: since an exchange task cannot spawn unless ALL the md tasks in the previous stage are complete, and new MD tasks cannot spawn unless an Exchange stage completes and provides EnTK with the information needed to spawn new MD tasks. But it becomes extremely cumbersome in case of asynchronous exchange.
-   Allowing EnTK to write the outputs of one unit to the sandbox of another unit makes it so that the unit sandbox being written to is now a "global" sandbox. Meaning, the agent side-client side communication to set up the future stages is not necessary. All the files needed by *any* task are in the same "global" sandbox. This way the Exchange task can simply rename the files appropriately to the file names expected by any future MD tasks. 

Does this make sense?
@vivek-bala I believe we have discussed this, feel free to add further comments or ask for clarification.

**Comment by andre-merzky** [comment]
@vivek-bala : 
> Hey, you can currently only use task location references (i.e. replica_sandbox) for data movement (i.e. link_input_data, copy_input_data, etc.) and not for arguments. If you move the data to the task directory, you can specify the arguments as if the data is in the current location of the task.

Would it make sense to add those placeholders to the unit's environment?  That would make Sriniva's command line work...

**Comment by vivek-bala** [comment]
That can make the shell script incredibly big. I have to do the bookkeeping in EnTK anyway so I am parsing them in EnTK. Along with #259, I have added this for the next release.

**Comment by vivek-bala** [comment]
Fixed in 0.7.7. We parse the placeholders in EnTK and expand them before specifying a CUD.

**Comment by vivek-bala** [comment]
This required a hotfix, now in 0.7.8. For example on usage, see https://github.com/radical-cybertools/radical.entk/blob/master/tests/test_issues/test_issue_259.py.

**Comment by vivek-bala** [comment]
I am closing this for now as there hasn't been any further buzz about it. If this issue pops up again, please reopen.
