### ISSUE TITLE
Failure handling in EnTK?

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#277]
While running large jobs (several thousand units), there is significant statistical likelihood of some of those tasks failing during runtime. Since with many workflows (replica exchange included) rely on *all* tasks completing successfully, I'm looking for a way to handle failures at a task level. Is there a `task.resubmit()` method that can be used if the task state returns a failed state? 

One way of doing it is to collect all `task.state()` outputs and if any return a failure, adaptively create a new stage to rerun only failed tasks. But that clearly becomes cumbersome in more complicated workflows. Is there a better way to do this?

**Comment by SrinivasMushnoori** [comment]
I've looked into it further and the failure handling mechanism is addressed in the app manager (and not in the task API as I previously thought. Setting the `resubmit_failed` option is what I was looking for. Closing this ticket now.

**Comment by vivek-bala** [comment]
That's correct. The tasks will get resubmitted for execution till the task is successful. Note that this means that if you have a task that fails every time, it will get resubmitted every time, and that Stage (containing the task) will never get completed. Just an FYI on the caveat.

**Comment by mturilli** [comment]
Should we have a feature request for an optional parameter to specify the number of resubmissions?
