### ISSUE TITLE
Add ORNL use case to RTD

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#290]
Hey Jumana, can you add Arvind's use case to this list: https://radicalentk.readthedocs.io/en/latest/introduction.html#intended-users

**Comment by jdakka** [comment]
I think Arvind is actually moving now to Argonne, but I'm not sure when that takes effect. I've created a pull request that currently shows ORNL but we can change it once we know fo sho

**Comment by vivek-bala** [comment]
Sounds good. Thanks!
