### ISSUE TITLE
API: why is task.executable a list?

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#295]

**Comment by andre-merzky** [comment]
What is the resolution on this?

**Comment by vivek-bala** [comment]
Hey Andre, apologies. I forgot to comment on the ticket. I agree that it shouldn't be a list. I changed back to string. I'm going accept a list for one more release (so that current user's are unaffected), but will remove it in the next release. Does that sound okay?

**Comment by andre-merzky** [comment]
Cool! :-)

**Comment by vivek-bala** [comment]
Fixed and tested in 0.7.14.
