### ISSUE TITLE
strong scalability

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#300]
I don't understand the strong scaling graph at the bottom of https://radicalentk.readthedocs.io/en/latest/entk.html.  The first datapoint is basically running 8k tasks on 512 cores (512 is missing in the caption btw).  Each task runs 500 sec (top caption).  That would be 16 generations * 500s = 8000s - but the y-value (right) shows ~700s.  What am I missing?  And while RP is not great, the 8k tasks should be executed *somewhat* faster with more cores, not slower.

**Comment by vivek-bala** [comment]
Hey Andre, the caption is incorrect and the title of the figure is correct. We varied the number of tasks and kept the number of resources constant. I'll fix that.

We also have the plot where we varied the number of cores keeping the number of tasks constant. I'll add that as well.

**Comment by mturilli** [comment]
Should we update the plots using those published in the linked paper?

**Comment by vivek-bala** [comment]
Yes, that's what I am thinking.
