### ISSUE TITLE
repex code hangs

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#302]
Hi Vivek, 

I am using `fix/issue_296` (with the logger patch, FWIW), with [this repex mockup code](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/misc/experimental_async/experimental_async_am.py).  That script should not depend on any externals - it runs only `echo/sleep` tasks right now.  All works up to the `resume()`, but one of the pipelines does not seem to be able to continue.  Interestingly it is the one which does not need resuming in the first place (you'll see the `try/except` to catch the failing resume).  From the EnTK code I would not expect any side effects of that failing resume (you could make it a NOOP with a log warning IMHO) - but even if I change the code to not issue that unneeded resume, the behavior is the same.

From the EnTK looks it looks to me that the next task in either pipeline is not created.  I can't discern the pipelines cleanly in the logs, apologies - but since I see success messages from the formerly suspended pipeline, I assume that the other one is the problem.

If you have any suggestion on how to debug this further,  please let me know.  I attach some log files - but please be aware that I have fiddled with some log messages, and they might be slightly off.  But, as said, you should be able to run the script.

Thanks, Andre.

[re.session.rivendell.merzky.017933.0013.zip](https://github.com/radical-cybertools/radical.entk/files/2836387/re.session.rivendell.merzky.017933.0013.zip)

**Comment by SrinivasMushnoori** [comment]
I'm trying to understand something. I've implemented the "sliding window" method as discussed with @andre-merzky (@vivek-bala I'm happy to go through it in about 4-5 minutes with you if it's useful to you). Andre: is the issue you are facing in the repex mockup that ALL pipelines are perpetually suspending themselves? Or is it just the one that is supposed to send the `resume` signal? In my RepEx workload [(here)](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/misc/experimental_async/async_sliding_window.py) all pipelines suspend themselves and are unable to recover. This does use actual MD workloads, but I'm happy to move it to `bin/sleep` if that makes it easier for you.

**Comment by andre-merzky** [comment]
I can resume pipelines all right - just not the one which hosts the stage (and its post-exec) which does the resuming, so can't resume `self`.  Don't worry about the workload, I can switch to sleep - but probably won't be able to look into it today :/

**Comment by SrinivasMushnoori** [comment]
That's fine, thanks for confirming. When you can. 
Because the more I look at it the more I find that you and I are not having the same exact problem, but they _might_ be rooted in the same underlying issue. For me, *all* pipelines are getting perpetually suspended.

**Comment by SrinivasMushnoori** [comment]
Hi all,
Has there been any movement on this?

**Comment by andre-merzky** [comment]
No progress yet I am afraid, but we are on it.

**Comment by andre-merzky** [comment]
So, for some reason, the following stack works for my example:
```
$ rs

  python               : 2.7.15rc1
  pythonpath           :
  virtualenv           : /home/merzky/radical/radical.entk/ve

  radical.entk         : 0.7.12-0.7.11-35-gb1925c06@fix-issue_302
  radical.pilot        : 0.50.19-v0.50.19-11-g11c9fd97@devel
  radical.utils        : 0.50.3-v0.50.3-3-gac10748@devel
  saga                 : 0.50.5
```

Its funny because that EnTK branch is identical to devel...  @SrinivasMushnoori , please give that a try.  I'll also try to run your repex code next.

**Comment by SrinivasMushnoori** [comment]
Hi, 
```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.45.2-104-ge615742@feature-entk-integration
  radical.entk         : 0.7.12-0.7.11-35-gb1925c0@fix-issue_302
  radical.pilot        : 0.50.19-v0.50.19@master
  radical.utils        : 0.50.2-v0.50.2-4-gffd777f@devel
  saga                 : 0.50.0-v0.50.0-4-gfc8d2e0@devel
```

The above radical stack causes a failure.

```
Traceback (most recent call last):
  File "async_sliding_window.py", line 409, in <module>
    cores         = 1)
  File "async_sliding_window.py", line 78, in __init__
    exe       = self._executable)
  File "async_sliding_window.py", line 327, in __init__
    self.add_md_stage()
  File "async_sliding_window.py", line 369, in add_md_stage
    stage.post_exec = self.after_md
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/stage/stage.py", line 165, in post_exec
    raise TypeError(expected_type=dict, actual_type=type(value))
radical.entk.exceptions.TypeError: Expected (base) type(s) <type 'dict'>, but got <type 'instancemethod'>.
```

Now this is odd, since it _runs_ with devel, but hangs after all pipelines suspend and cannot resume. 
[This](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_sliding_window.py) is the latest version of the script I am using. I'm doing some more testing though.

**Comment by vivek-bala** [comment]
Hey Srinivas, can you change the post_exec to a dictionary as the previous iteration of the script.
```
stage.post_exec = {'condition': self.after_md,
                                'true': void,
                                'false': void}
```

From the next EnTK version onwards, we'll remove the dictionary and keep it to a single function. I don't want to do a hard transition in the API level so as to not affect anyone else's current experiments/trials.

**Comment by vivek-bala** [comment]
I just saw that https://github.com/radical-cybertools/radical.entk/issues/298 this was closed by me. Apologies if that lead you to the error. That issue is still open and will be addressed in the next version.

**Comment by SrinivasMushnoori** [comment]
Vivek, this makes sense. I sort of guessed that might be it, but hadn't tested it out yet. I'll test further and let you know. Thanks for the heads up!

**Comment by SrinivasMushnoori** [comment]
This does not work either. After some testing (and changing to the older way of specifying `post_exec` dictionaries) I find that it still fails. Now however the workflow seems to be created and submitted to the EnTK layer, but then breaks as follows: 

```
Exception in thread synchronizer-thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 907, in _synchronizer
    task_update(msg, '%s-sync-to-enq' % self._sid, props.correlation_id, mq_channel)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 641, in task_update
    completed_task.from_dict(msg['object'])
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/task/task.py", line 778, in from_dict
    actual_type=type(d['executable']))
TypeError: Expected (base) type(s) <type 'list'>, but got <type 'unicode'>.
```

The client and agent sandboxes are [here.](https://github.com/radical-cybertools/radical.entk/files/2870026/client_and_agent_sandbox.zip)

How did it work for you @andre-merzky ? I'm using the same stack as before, so the same branch of EnTK as you, i.e. `fix/issue_302`

**Comment by andre-merzky** [comment]
For some reason,`executable` needs to be a list of strings instead of a string.  I used `[echo]` for testing...

**Comment by SrinivasMushnoori** [comment]
I'm using the MD engine in my script. `SANDER` is the AMBER MD engine...

**Comment by andre-merzky** [comment]
Understood - the point though is that you need to specify `executable` as list of strings (with one member, `SANDER`).

**Comment by SrinivasMushnoori** [comment]
`SANDER   = ['/home/scm177/mantel/AMBER/amber14/bin/sander']`

is what I am doing. That is a list of strings...

**Comment by andre-merzky** [comment]
And then 'task.executable = SANDER`?  And that still fails with the same error?  Can you please commit your code so that I can try to fix this - that should indeed not happen.

**Comment by SrinivasMushnoori** [comment]
On it. Hang on.

**Comment by SrinivasMushnoori** [comment]
Committed.

[Line 17](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_sliding_window.py#L17) is where the executable is declared

[Line 365](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_sliding_window.py#L365) is where it is used to set up the MD stage.

**Comment by andre-merzky** [comment]
In line 112 and 210, `'python'` is used as executable - that should be `['python']` I assume.  Can you give that a try, please?

**Comment by SrinivasMushnoori** [comment]
Ah I missed that: my apologies. Appears to be working right now. Will keep you updated.

**Comment by andre-merzky** [comment]
Great!

**Comment by SrinivasMushnoori** [comment]
This appears to run to completion, but I do not find any pipelines ever getting suspended.

Terminal output:
```
submit 4 unit(s)
        ....                                                                  ok
Update: Task task.0001 in state SUBMITTED
Update: Task task.0002 in state SUBMITTED
Update: Task task.0003 in state SUBMITTED
Update: Task task.0004 in state SUBMITTED
Update: Task task.0001 in state EXECUTED
Update: Task task.0001 in state DEQUEUEING
Update: Task task.0001 in state DEQUEUED
Update: Task task.0001 in state DONE
Update: Task task.0003 in state EXECUTED
Update: Stage stage.0001 in state DONE
Update: Pipeline pipeline.0001 in state DONE
Update: Task task.0003 in state DEQUEUEING
Update: Task task.0003 in state DEQUEUED
Update: Task task.0004 in state EXECUTED
Update: Task task.0003 in state DONE
Update: Stage stage.0003 in state DONE
Update: Pipeline pipeline.0003 in state DONE
Update: Task task.0004 in state DEQUEUEING
Update: Task task.0004 in state DEQUEUED
Update: Task task.0004 in state DONE
Update: Stage stage.0004 in state DONE
Update: Pipeline pipeline.0004 in state DONE
Update: Task task.0002 in state EXECUTED
Update: Task task.0002 in state DEQUEUEING
Update: Task task.0002 in state DEQUEUED
Update: Task task.0002 in state DONE
Update: Stage stage.0002 in state DONE
Update: Pipeline pipeline.0002 in state DONE
wait for 1 pilot(s)
                                                                              ok
closing session re.session.mcewan.engr.rutgers.edu.scm177.017942.0006          \
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 96.3s                                                       ok
```
First: This _might_ be a RepEx level logic issue, but I find it strange that none of the pipelines are ever getting suspended or resumed. Secondly: the exchange task (which by the way we have set up the replicas should be `task.0005` does not even spawn. I dug into the sandbox and sure enough, it isn't even there.

**Comment by andre-merzky** [comment]
I would suggest to then open an issue in the repex repo to discuss that problem, but to close this EnTK issue until we see suspend failing otherwise. I can at least confirm its working for the case where it failed before.

**Comment by SrinivasMushnoori** [comment]
Got it. I appear to not have the ability to close this ticket.

**Comment by andre-merzky** [comment]
I have to re-open, this is still a problem after all.

**Comment by SrinivasMushnoori** [comment]
Update: while the code does not hang, it fails with the following:

```
Update: p_1.stage.0001.mdtsk-1-0 state: DEQUEUEING
Update: p_1.stage.0001.mdtsk-1-0 state: DEQUEUED
Update: p_1.stage.0001.mdtsk-1-0 state: DONE
2019-03-25 16:08:47,794: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : ERROR   : Execution failed in post_exec of stage stage.0001
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 388, in _dequeue
    resumed_pipes = stage.post_exec['function'](*stage.post_exec['args'])
KeyError: 'function'
2019-03-25 16:08:47,795: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : ERROR   : Unable to receive message from completed queue: 'functi
on'
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 388, in _dequeue
    resumed_pipes = stage.post_exec['function'](*stage.post_exec['args'])
KeyError: 'function'
2019-03-25 16:08:47,796: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : ERROR   : Error in dequeue-thread: 'function'
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 388, in _dequeue
    resumed_pipes = stage.post_exec['function'](*stage.post_exec['args'])
KeyError: 'function'
Exception in thread dequeue-thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 469, in _dequeue
    raise EnTKError(ex)
EnTKError: 'function'
```

This is an infinite loop. `radical-stack` is
```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.45.2-104-ge615742@feature-entk-integration
  radical.entk         : 0.7.16-0.7.15-12-g98ea7f1@feature-suspend_resume
  radical.pilot        : 0.50.19-v0.50.19-12-g9cab005@devel
  radical.utils        : 0.50.2-v0.50.2-4-gffd777f@devel
  saga                 : 0.50.0-v0.50.0-4-gfc8d2e0@devel
```

RepEx script is [here](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/repex/async_sliding_window.py)

**Comment by andre-merzky** [comment]
This has been fixed by now.
