### ISSUE TITLE
Correcting typos in documentation

### ISSUE THREAD

**Issue by uvaaland** [radical-cybertools/radical.entk#303]
Going through the documentation at:

https://radicalentk.readthedocs.io/en/latest/

I noticed some typos along the way that we should correct. What would be the best way to do that? Would you want me to contribute corrections directly, or should I go through you to do so?

Uno

**Comment by vivek-bala** [comment]
Thanks Uno! Really appreciate it! Feel free to simply list them in this ticket. The doc files are kept in radical.entk/docs/, I can fix them and merge them to master.

**Comment by vivek-bala** [comment]
You are most welcome to contribute as well! You can start a new branch (forked from master), fix any files/documents and request a pull request (PR). Someone, from our team, would review your PR and merge it. As mentioned above, the files for the documentation are held in radical.entk/docs/ as .rst files.

Let me know if you require any help navigating through any of the files.

**Comment by uvaaland** [comment]
Yes, that sounds like a good way to do it. Thank you for the prompt feedback!

**Comment by uvaaland** [comment]
Pull request opened -> https://github.com/radical-cybertools/radical.entk/pull/305

**Comment by vivek-bala** [comment]
Thanks Uno! Merged with devel.
