### ISSUE TITLE
src tree

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#312]
Several subdirs in the EnTK source tree have only one file each, specifically `pipeline/`, `stage/`, and `task/`.  Why is that?  Wouldn't it make sense to move those files one level up, to simplify navigation?

**Comment by vivek-bala** [comment]
I think initially I might have had those files under src/radical/entk. I can't quite place why I moved them around. It might have something to do with the testing setup.

I'm happy to move them around: put them back in src/radical/entk or put them all in a folder called user_components?

**Comment by andre-merzky** [comment]
Well, they are not components but API objects - main entk folder would be suitable for that (and would be in sync with the other layers).  I don't feel strongly about it, really, just found it interesting / odd :-)  Feel free to close w/o action if you don't want to change the current state...

**Comment by mturilli** [comment]
@andre-merzky @iparask time to pick this up again?

**Comment by andre-merzky** [comment]
Sure, this is easily done.  Let me do that.

<tap tap tap>

have a look here: #510
