### ISSUE TITLE
Running get_started.py example on remote resource

### ISSUE THREAD

**Issue by uvaaland** [radical-cybertools/radical.entk#315]
Hi,

I am trying to run EnTK with a remote resource (bridges.xsede). The script I am running is the get_started.py example script which I am successfully running on my localhost.

I am using the ssh scheme to connect to the remote resource and have set up and tested the passwordless connection. Still, I get an error that I cannot seem to figure out.

Attached is the session files, the script that is being run, and verbose.log.

Thanks!

[issue_files.tar.gz](https://github.com/radical-cybertools/radical.entk/files/2881622/issue_files.tar.gz)

Uno

**Comment by vivek-bala** [comment]
Hey Uno, I think the default queue specified for bridges is incorrect in our configs (see https://github.com/radical-cybertools/radical.pilot/issues/1816). Error from the logs:

```
NoSuccess: future exception: Couldn't get job id from submitted job! sbatch output:
sbatch: error: invalid partition specified: normal
sbatch: error: Batch job submission failed: Invalid partition name specified
```

Partition name on bridges means the queue name. You should add the following key and value to the resource description:
```
'queue': '<queue name you want to use>'
```

**Comment by uvaaland** [comment]
Great, adding:

`'queue': 'RM'`

to the resource dictionary resolves the issue on Bridges.
