### ISSUE TITLE
radical.entk version 0.7.13 breaks execution of example scripts

### ISSUE THREAD

**Issue by uvaaland** [radical-cybertools/radical.entk#322]
I have been running radical.entk version 0.7.11 for a couple of weeks without any problem on my virtual machine. However, recently when I helped someone else with the exact same setup, we ran into a problem when trying to run any of the example scripts.

Trying to run `get_started.py` or any of the other examples, we get the following error:

```
EnTK session: re.session.test.vagrant.017956.0004
Creating AppManager                                                           ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                    ok
All components created
Update: Pipeline pipeline.0000 in state SCHEDULING
Update: Stage stage.0000 in state SCHEDULING
Update: Task task.0000 in state SCHEDULING
Update: Task task.0000 in state SCHEDULED
Update: Stage stage.0000 in state SCHEDULED
/home/vagrant/scratch/entk/venv/local/lib/python2.7/site-packages/pymongo/topology.py:149: UserWarning: MongoClient opened before
fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.ht
ml#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
Update: Task task.0000 in state SUBMITTING
Update: Task task.0000 in state SUBMITTED
2019-03-01 21:17:36,802: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: ERROR   : Unknown e$
ror in synchronizer: Expected (base) type(s) <type 'str'>, but got <type 'list'>..
 Terminating thread
Traceback (most recent call last):
  File "/home/vagrant/scratch/entk/venv/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 888, in _synch$
onizer
    task_update(msg, '%s-sync-to-cb' % self._sid, props.correlation_id, mq_channel)
  File "/home/vagrant/scratch/entk/venv/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 641, in task_up
date
    completed_task.from_dict(msg['object'])
  File "/home/vagrant/scratch/entk/venv/local/lib/python2.7/site-packages/radical/entk/task/task.py", line 780, in from_dict
    actual_type=type(d['executable']))
TypeError: Expected (base) type(s) <type 'str'>, but got <type 'list'>.
```

We could not understand where this was coming from, since the setup was the exact same as on my working VM. I noticed, however, that the version of EnTK was more recent (0.7.13 instead of 0.7.11).

I went through the entire setup one more time on my own computer to verify that I could reproduce the issue, and that was the case. I found that the issue goes away by downgrading radical.entk to version 0.7.12 or 0.7.11, so the issue appears to be tied to the most recent version.

If the observed behavior is intentional we should update the example scripts to reflect this.

[session.tar.gz](https://github.com/radical-cybertools/radical.entk/files/2921135/session.tar.gz)

Attached are the session files and `verbose.log`.

**Comment by andre-merzky** [comment]
Thanks for reporting the issue!  This has been introduced by a recent update which, apparently, was not fully backward compatible.  A fix is in the works and should be released shortly.

Meanwhile, as a workaround, please specify your executables on `re.Task` objects as string types (not list of string anymore).  Thanks!

**Comment by vivek-bala** [comment]
Same as #295. Fixed and tested.
