### ISSUE TITLE
move heartbeat into its own thread (task manager)

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#327]
[cleaned out template]

**Comment by vivek-bala** [comment]
Haha you didn't clear the issue template :stuck_out_tongue:

**Comment by andre-merzky** [comment]
Nope I didn't - was supposed to be a quick placeholder :-P  But let me expand on this now.

We discussed why the task manager is split in two threads:  to avoid that actual work blocks the heartbeat progression which would lead to timeouts.  The second thread takes over the actual work, the heartbeat works.

A simple approach with the same result is to move the heartbeat into its own thread - then the work stays localized in the main thread, and no communication and synchronization is needed between the threads (apart from some alive signal), simplifying the main loop of the process significantly.

**Comment by mturilli** [comment]
Depends on when heartbeat will be available in RU v2

**Comment by iparask** [comment]
I think this is already done. @andre-merzky can you verify? See [here](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/execman/base/task_manager.py#L305-L333).

**Comment by andre-merzky** [comment]
Yes, agree, this is done.
