### ISSUE TITLE
Page about tests in RTD broken

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#337]
https://radicalentk.readthedocs.io/en/latest/tests.html

**Comment by mturilli** [comment]
@iparask let's review this and decide what to do with that page.

**Comment by iparask** [comment]
I do not think we need it in full. We can have a test example under the development guide nothing more. I would like to move Travis, coverage and other badges in the main page of the documentation.

**Comment by mturilli** [comment]
I agree. Should we plan it for Dec release?

**Comment by iparask** [comment]
Yes. I think we should. Let me push it in the unit tests branch the next couple of days and assign you as a reviewer.
