### ISSUE TITLE
Resource allocation fails for `feature/tiger` branch

### ISSUE THREAD

**Issue by uvaaland** [radical-cybertools/radical.entk#339]
I have installed the `feature/tiger` branch of EnTK in a new virtual environment and am trying to run the `getting_started.py` example on the princeton `tigercpu` resource.

Upon launching it I get a resource allocation failure in the `appman.run()` line.

```bash
Setting up RabbitMQ system                                                    ok
/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/libcloud/utils/py3.py:60: UserWarning: Missing backports.ssl_match_hostname package
  warnings.warn("Missing backports.ssl_match_hostname package")
                                                                              ok
create pilot manager                                                          ok
submit 1 pilot(s)
        [princeton.tiger_cpu:1]
                                                                              ok
2019-04-25 09:01:05,682: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2019-04-25 09:01:05,690: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager: Cannot proceed. Resource allocation ended up in FAILED
Traceback (most recent call last):
  File "/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 311, in run
    raise EnTKError(msg="Cannot proceed. Resource allocation ended up in %s"%res_alloc_state)
EnTKError: Cannot proceed. Resource allocation ended up in FAILED
wait for 1 pilot(s)
                                                                              ok
closing session re.session.jakarta.princeton.edu.uvaaland.018011.0003          \
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 12.3s                                                       ok
Traceback (most recent call last):
  File "get_started_princeton.py", line 61, in <module>
    appman.run()
  File "/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 311, in run
    raise EnTKError(msg="Cannot proceed. Resource allocation ended up in %s"%res_alloc_state)
radical.entk.exceptions.EnTKError: Cannot proceed. Resource allocation ended up in FAILED
[1409][uvaaland: scripts]$ python get_started_princeton.py &> verbose.log
```

Attached are the session files for entk and the pilot, in addition to `verbose.log` and the script that I am trying to run `getting_started_princeton.py`

[issue.tar.gz](https://github.com/radical-cybertools/radical.entk/files/3116938/issue.tar.gz)

**Comment by vivek-bala** [comment]
Hey Uno, can you confirm that you installed the feature/tiger branch of RP (I don't think there is a branch in EnTK)? I think that's what you meant, but just want to be sure.

The error is in the pmgr launcher:
```
2019-04-25 08:40:30,734: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 488, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 677, in _start_pilot_bulk
    js = rs.job.Service(js_ep, session=self._session)
  File "/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/radical/saga/job/service.py", line 116, in __init__
    url, session, ttype=_ttype)
  File "/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/radical/saga/base.py", line 105, in __init__
    **kwargs)
  File "/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/radical/saga/adaptors/cpi/decorators.py", line 62, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/radical/saga/adaptors/slurm/slurm_job.py", line 304, in init_instance
    self._open()
  File "/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/radical/saga/adaptors/slurm/slurm_job.py", line 366, in _open
    raise rse.NoSuccess._log (self._logger, message)
NoSuccess: Error finding SLURM tool squeue on remote server slurm://localhost/!
Locations searched:
which: no squeue in (/home/uvaaland/scratch/entk/vdevel/bin:/home/uvaaland/.local/bin:/home/uvaaland/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin)

Is SLURM installed on that machine? If so, is your remote SLURM environment configured properly?  (/home/uvaaland/scratch/entk/vdevel/lib/python2.7/site-packages/radical/saga/adaptors/slurm/slurm_job.py
```

Seems like the command ```squeue``` did not respond.

**Comment by uvaaland** [comment]
My apologies. Yes, the `feature/tiger` branch is for `radical.pilot`. SLURM and `squeue` are available by default on Tiger, no module load required. Is it somehow looking for SLURM locally? The program never got as far as putting anything on the Tiger, as far as I understand.

**Comment by vivek-bala** [comment]
I am not sure. You have to log into the login node on tigercpu, create a virtualenv and install EnTK+RP on that login node and then run the above script . I believe that's what Andre has tested by looking at [this](https://github.com/radical-cybertools/radical.pilot/blob/feature/tiger/src/radical/pilot/configs/resource_princeton.json#L6) line . 

Can you confirm if you have done the same? You cannot run the script for your machine like you did for bridges, I think the reason is the two level gateway which prevents anyone outside the campus to ssh directly into the tigercpu login node.

**Comment by uvaaland** [comment]
I see. Because that is definitely not what I have done. I am using my Princeton desktop machine which is behind the firewall and can therefore connect to Tiger directly.

I am happy to try the head node option, but it would be great to extend it such that scripts can be run from computers that are on the Princeton network. You can also do this yourself by using VPN instead of going through `tigressgateway`.

Let me test it on the tiger head node and get back to you.

**Comment by vivek-bala** [comment]
Sure, yes. Can you elaborate or give any instructions on the VPN idea please? I couldn't find a method to do so following the user guide, maybe I missed it. Either way, I don't think creating that functionality is difficult, its just the we (being outside the Princeton) network might not be able to test it before handing it over to you. Let's see if the VPN idea works.

Let us know how the current login node approach works, adding accessibility from your desktop machine is trivial I think.

**Comment by uvaaland** [comment]
Sounds good. Here are instructions for VPN usage:
https://www.net.princeton.edu/vpn/

Follow one of the links under SRA according to your need. Let me know if that works, and if not, I will talk to some of the systems people to see what options we have.

**Comment by vivek-bala** [comment]
Great thanks!

**Comment by uvaaland** [comment]
How do you guys use virtualenv on Tiger? I was going to send an email to support about how to do this, but perhaps you could summarize it more quickly?

**Comment by vivek-bala** [comment]
We might be using the anaconda module ```module load anaconda/5.3.1```. You can either use ```conda create -n <env name> python=2.7``` or ```virtualenv <env name>``` after that.

**Comment by uvaaland** [comment]
But I always get the following error when trying to use virtualenv through anaconda:

New python executable in /home/uvaaland/scratch/entk/venv/bin/python
ERROR: The executable /home/uvaaland/scratch/entk/venv/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/usr' (should be u'/home/uvaaland/scratch/entk/venv')
ERROR: virtualenv is not compatible with this system or executable

How do you guys get around that?

**Comment by vivek-bala** [comment]
Woah, I don't remember encountering anything like that. Let me test again.

**Comment by uvaaland** [comment]
That came from me doing:

module load anaconda
pip install --user virtualenv
virtualenv venv

**Comment by vivek-bala** [comment]
```
module load anaconda
conda create -n venv python=2.7
source activate venv
pip install radical.entk
<install feature/tiger branch of RP>
```

The above worked for me and RP is able to submit a pilot. The pilot goes through the queue and fails with a conda error for me. @andre-merzky could you give us the commands we should use please.

**Comment by uvaaland** [comment]
From the example that Andre had me run on Tiger, he is using:

```bash
./bin/radical-pilot-ve ve
```

And that is sufficient for running the pilot examples. However, I reached out to PU support to ask what the best way to work with `virtualenv` on the Tiger is, and they said that you either have to use conda instead, or `virutalenv` from within a conda environment. That is, nesting virtual environments.

The issue is this. In order to have a version of `virtualenv` that is compatible with `conda` you need to do
```bash
conda install virtualenv
```
and
```bash
pip install virtualenv
``` 
does not work. This will allow us to install EnTK and its requirements, but there is still an issue that will not show up until you try to run an example. This happens the first time when the pilot sets up its own virtual environment. Because the pilot tries to use a `virtualenv` that is different from `conda install virtualenv` and is thus not compatible with conda.

This is one of the initial issues I had when trying to run EnTK on my personal laptop or local desktop through `conda`. I never found a good solution, and settled on not using `conda`.

**Comment by uvaaland** [comment]
I haven't actually tried to reproduce this issue on Tiger yet, but I have some time free now and will do so as a sanity check and report back.

**Comment by uvaaland** [comment]
Another question regarding running EnTK from the Tiger head node, how are we to deal with the RabbitMQ requirement? The obvious answer is to have the system administrators install it, but requesting software to be made globally available can be a big deal on Tiger. Especially when the more obvious use case would be to run EnTK from a local desktop, thus circumventing the need for additional software installation on Tiger.

That is, I don't think they will do it unless it is necessary, which it is not.

So in trying to reproduce the conda/virtualenv issue described above, I get stuck because of the RabbitMQ dependency, and I think we should pause here and figure out how to tackle this.

My inclination is to shift the focus to running EnTK from machines that are on the Princeton network, but not the cluster itself. That is how I envision members of our group working with EnTK going forward.

Please, I am laying things out the way I see it myself, but you should push back and let me know if you have other opinions and suggestions. Thanks! :)

**Comment by vivek-bala** [comment]
> This will allow us to install EnTK and its requirements, but there is still an issue that will not show up until you try to run an example. This happens the first time when the pilot sets up its own virtual environment. 

I think I see what you're saying and I agree. From the other ticket, once you have executed ```(ve) $ ./bin/radical-pilot-create-static-ve ~/radical.pilot.sandbox/ve.princeton.tiger/```, you should have a virtualenv for the pilot as well. There should not be an issue unless there is a system change in any of the libraries.

> Another question regarding running EnTK from the Tiger head node, how are we to deal with the RabbitMQ requirement? The obvious answer is to have the system administrators install it, but requesting software to be made globally available can be a big deal on Tiger.

There are many options available here:
1) As you pointed out, run EnTK from your own machine other than the Tiger head nodes. You would be able to install RabbitMQ on your machine and use it. @andre-merzky should/can we enable this via change in the access schemas in the config files?
2) We can setup a RabbitMQ service on one of our VMs that you can access. This option would be good for testing and not production runs (latency can be high).
3) Asking for RabbitMQ specifically on Tiger could be difficult, do you know if the system admins provide support for containers? If there is support for Docker, you can install and invoke the RabbitMQ container (which is what we do on our VMs as well).
4) You can install RabbitMQ as a persistent user process on the login node as well. You would have to build from source though (as well as build erlang - dependency). I would keep this as the last option.

**Comment by uvaaland** [comment]
This sounds good to me. I agree with the options that you have listed, and they also come in order of preference for me. So 1 would be most desirable, and 4 the last resort.

**Comment by vivek-bala** [comment]
Great, let's see what Andre says. Let me know if you need a RabbitMQ on our VM for the time being/testing phase.

**Comment by uvaaland** [comment]
If it is trivial to provide, I wouldn't mind having that as an option right now :)

**Comment by vivek-bala** [comment]
Yup, done. I'll send you the port number through slack now.

**Comment by andre-merzky** [comment]
Sorry I missed that ticket.  Not sure if I parsed the current state correctly - but the ssh access for tiger is now configured in RP's resource config, and EnTK should pick this up.  I could only test this on tiger itself (don't have any other host behind the firewall), but that seems to work.

**Comment by vivek-bala** [comment]
Seems like the 'local' access schema is being used as default. Can you confirm if you are using feature/srun branch?

**Comment by uvaaland** [comment]
I have been using `feature/tiger`

**Comment by vivek-bala** [comment]
Yes, I checked again. 'feature/tiger' should allow ssh access as well. It still picks up the 'local' access schema.
