### ISSUE TITLE
Need 'raw' MD kernels with commandline flags corresponding to the ones in original MD package

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.entk#35]
From the RE application developer point of view I think having raw MD kernels would be very useful for the following reasons.
Potential domain specific application developers are already familiar with commandline flags of a given MD package. If these are substituted with something more generic it would require an application developer to learn the meaning of these new flags from the ENMD documentation, which in turn means that documentation should be of high quality and very detailed. Amber documentation for example is 350 pages.
Application developers will be interested to run many different simulations e.g. 2d vs temperature vs salt concentration with any kernel. Running different simulations requires different sets of commandline flags and to cover all possible variations would be quite challenging (3 dimensions here: flag names, number of flags, order of flags). 
From the usability perspective I would argue that users will see time spent reading about new generic flags as a better investment in comparison to time spent on specifying original flags in kernel descriptions. If someone is already familiar with Amber and NAMD, modifying an application so that it supports another kernel, using original flags, would not require considerable coding effort. Also, the first step would be to write the first! ENMD application and kernel swapping goes only after that. What many ENMD-Toolkit users would appreciate is reduced "simulation setup time" in comparison to original MD package. Many simulations are difficult to setup - e.g. specify parameters in input files, etc. Developers of MD packages have overlooked this somehow.

**Comment by oleweidner** [comment]
Ole will do an Amber version of this.

**Comment by vivek-bala** [comment]
No longer applicable.
