### ISSUE TITLE
separate unit tests and integration tests

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#356]

**Comment by mturilli** [comment]
@iparask should we target Jan 2021 for release of unit/integration tests or is the separation between the two already ready for Dec 2020 release?

**Comment by iparask** [comment]
I think integration tests are for Jan 2021. I am not confident that I will be able to create them for December. I still do not know what kind of issues, we will have to face when RP components are introduced.

**Comment by mturilli** [comment]
Can we approach integration tests incrementally and have the 'framework' part in place by the end of the year? I am asking because that would be consistent with our initial roadmap.

**Comment by iparask** [comment]
This can be closed. Testing however should continue moving forward
