### ISSUE TITLE
Download data from online resource using a task (Tiger)

### ISSUE THREAD

**Issue by lsawade** [radical-cybertools/radical.entk#359]
Hi folks!

I already have a bunch of stages working except the download stage which gives me this error:

```bash
LWP::Protocol::http::Socket: Bad hostname 'service.iris.edu' at /usr/share/perl5/LWP/Protocol/http.pm line 51.
```

The task itself is actually executing, but the download is encountering an error. 

 I fear that EnTK blocks the internet connection?

The download itself works without issues from the command line on tiger, so the internet connection of tiger itself can't be the issue.

Thank you!

Cheers,

Lucas

**Comment by lsawade** [comment]
`service.iris.edu` is the server I download the data from.

**Comment by andre-merzky** [comment]
How do you try to download the data?

> The download itself works without issues from the command line on tiger, so the internet connection of tiger itself can't be the issue.

Is that from Tiger's login node, or from the compute node?  Network connectivity might differ on the compute nodes...

**Comment by lsawade** [comment]
aaaah, that might be the issue. I definitely try to call the download from the compute node.

**Comment by lsawade** [comment]
While this, as I realize, is not an issue with EnTK per se, because the compute nodes probably don't have internet connection, my question now is: 
How can make a task run from the login node? Is there a quick answer to this? 
Can I execute python code within the pipeline on the login node although the rest of my pipeline is run on the compute? I feel like there is an easy answer to this that I'm not seeing ...

**Comment by andre-merzky** [comment]
> How can make a task run from the login node? Is there a quick answer to this?
> Can I execute python code within the pipeline on the login node although the rest of my pipeline is run on the compute? I feel like there is an easy answer to this that I'm not seeing ...

You will not be able to run a task on a login node.  How large are the data you try to stage, and how frequent do you need to do so?  Once per run, or once per task?

If it is once per run, I would propose to fetch the data in the main application (I  assume you run that on the login node, your laptop or some other machine which has connectivity), and then use the EnTK staging directives to move the data to the task.  This is not very efficient (two hops), but in many cases that's the easiest way I would say.

I you need to fetch frequently and large data, please let me know *how* data are fetched - I can look into options for tunneling the data transfer through the login node.

FWIW, most of our users pre-stage data to the target machine manually before the application runs, to avoid those connectivity problems, but also in order to not waste time on the compute nodes waiting for incoming data.  If that is impractical for your use case, we should try to find a solution - I'll reopen the ticket meanwhile, if you don't mind.

**Comment by lsawade** [comment]
I do not mind mind!

#### The data
The data fetch is usually once per run through a perl script which I feed input data created in a prior task and then call through a python subprocess call. Also, fetching the data from within the script wouldn't be a problem at all, as the data will only be around 100-200MB once per run.

#### The solution ?

> ... use the EnTK staging directives to move the data to the task

I think this could be a solution, I'm not clear about it though. How can I make sure that the 'download part' is executed from within the main script but as a stage? Do you have a code snippet that does something similar?

This could be a solution for now anyways because my software will most likely not be running on the cluster, but on a designated single high performance machine. So, the internet connection wouldn't be an issue. That being said, I am trying to recompute a large earthquake source catalog, which in the beginning might be done in a batch job on a cluster.

Thanks for the help!

**Comment by mturilli** [comment]
@iparask ping

**Comment by iparask** [comment]
> The data fetch is usually once per run...

Do you mean once per workflow or task?

>...through a perl script which I feed input data created in a prior task and then call through a python subprocess call. 

If I understand correctly, there is a perl script, which can be executed as an EnTK task, that downloads the data and then a second task creates a python subprocess call?

> #### The solution ?
> > ... use the EnTK staging directives to move the data to the task
> 
> I think this could be a solution, I'm not clear about it though. How can I make sure that the 'download part' is executed from within the main script but as a stage? Do you have a code snippet that does something similar?

We do not currently support data staging at stages or pipelines, neither pre_exec. Are these data shared between tasks in a stage or for the whole pipeline?

> 
> This could be a solution for now anyways because my software will most likely not be running on the cluster, but on a designated single high performance machine. So, the internet connection wouldn't be an issue. That being said, I am trying to recompute a large earthquake source catalog, which in the beginning might be done in a batch job on a cluster.
> 
> Thanks for the help!

In case there is an internet connection on the compute nodes, you can define a stage with a task that executes the pearl script you mentioned before. Then you can define data dependencies between different tasks. (see [here](https://radicalentk.readthedocs.io/en/stable/user_guide/adding_data.html))

**Comment by andre-merzky** [comment]
@ip: sorry for the belated followup - that specific problem for Lucas got solved: he added a pre_exec to the task which triggered a data staging command on the login node.  We missed to close this ticket :-/
