### ISSUE TITLE
missing type check on RMQ port (and probably other parameters)

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#362]

**Comment by andre-merzky** [comment]
see also radical-collaboration/hpc-workflows/issues/82

**Comment by lee212** [comment]
PR #385, I attempt to add type conversion for user input parameters e.g. RMQ port. Other parameters concerned are either numerical value, boolean or python dictionary like:
```
reattempts (integer)
resubmit_failed (bool)
autoterminate (bool)
write_workflow (bool)
rmq_cleanup (bool)
rts_config (dict)
```

Maybe we can use ru's `to_type` function to apply a correct type? If this is agreed, `to_type` will expand to try `bool` and `dict` as it is currently checking `int` and `float` only. @andre-merzky , what is your thought?

**Comment by andre-merzky** [comment]
It's somewhat tricky to do automatic type conversion in Python, since many conversions are possbile but don't give the intended results.  For example:

```python
>>> data = ['ab', 'cd']
>>> dict(data)
{'a': 'b', 'c': 'd'}
>>> data = 'foobar'
>>> list(data)
['f', 'o', 'o', 'b', 'a', 'r']
```

One needs some idea of the target type to do that sensibly.  But, RU actually has a `as_list()` method which acts like this:

```python
>>> ru.as_list(data=None)
[]
>>> ru.as_list(data='foo')
['foo']
>>> ru.as_list(data=['foo', 'bar'])
['foo', 'bar']
```

We similarly could add `as_float()`, `as_int()` etc.  Is that what you are looking for?

**Comment by lee212** [comment]
PR #385 fixes this
