### ISSUE TITLE
EnTK not detecting RMQ port?

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#371]
`radical-stack` is as follows:
```
(Env_RepEx)scm177@mcewan:~/RADICAL-LAB/repex_3/examples$ radical-stack

  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : 0.72.0
  radical.entk         : 0.72.0
  radical.pilot        : 0.72.0
  radical.saga         : 0.72.0
  radical.utils        : 0.72.0
```

Now, I try to run any EnTK script, I see the following:

```
(Env_RepEx)scm177@mcewan:~/RADICAL-LAB/repex_3/examples$ python async_repex.py 
EnTK session: re.session.mcewan.engr.rutgers.edu.scm177.018155.0005
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
                                                                              ok
create pilot manager                                                          ok
submit 1 pilot(s)
        [local.localhost:8]
                                                                              ok
Traceback (most recent call last):
  File "async_repex.py", line 463, in <module>
    exchange.execute()
  File "async_repex.py", line 190, in execute
    self.run()
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 389, in run
    self.terminate()
  File "async_repex.py", line 183, in terminate
    self.resource_terminate()
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 434, in resource_terminate
    self.terminate()
  File "async_repex.py", line 179, in terminate
    self._dump(msg='terminate', special=self._replicas, glyph='=')
  File "async_repex.py", line 164, in _dump
    self._dout.write(' | %7.2f |' % (time.time() - t_0))
ValueError: I/O operation on closed file
^CException KeyboardInterrupt: KeyboardInterrupt() in <module 'threading' from '/usr/lib64/python2.7/threading.pyc'> ignored
```

Here, I want to point out specifically the line `Setting up RabbitMQ system                                                   n/a`

It appears that EnTK cannot detect the rabbitmq. I do have RMQ installed via docker image. 

```
(Env_RepEx)scm177@mcewan:~/RADICAL-LAB/repex_3/examples$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                                 NAMES
b87ae7117f70        rabbitmq:3          "docker-entrypoint.s…"   15 minutes ago      Up 15 minutes       0.0.0.0:32771->4369/tcp, 0.0.0.0:32770->5671/tcp, 0.0.0.0:32769->5672/tcp, 0.0.0.0:32768->25672/tcp   repex_rmq_1
```

Now in my EnTK script I clearly specify the RMQ port to use (I've tried MULTIPLE ways, even):
1) At the start of the script: `RMQ_PORT = int(os.environ.get('RMQ_PORT', 32769))`
2) While initializing the appmanager object: `re.AppManager.__init__(self, autoterminate=False, port=32769) `
3) In the terminal before executing the script: `export RMQ_PORT=32769`

Unsure what else I can do. I have run the script with `RADICAL_LOG_LVL=DEBUG` and RADICAL_LOG_TGT=debug.log` and that file has been [attached here](https://github.com/radical-cybertools/radical.entk/files/3618122/debug_log.zip)

Thanks

**Comment by andre-merzky** [comment]
Can you connect to the port with `telnet localhost 32769`?  You should not get an error message when trying the above - that would confirm that RMQ is indeed listening on that port.

**Comment by SrinivasMushnoori** [comment]
Yes I am able to.
This seems(??) to be in fact an issue not with the RMQ port visibility but MongoDB? Because Matteo's MDB instance fixed this. Leaving ticket open for now since this might still be hiding some unresolved issue.

**Comment by andre-merzky** [comment]
Ah, great - in this case we can actually close the ticket - its simply that the log messages indicating the problem were not in the debug log, but that MLAB is not working anymore is indeed a known problem...
