### ISSUE TITLE
MongoDB Atlas URI format not compatible with EnTK

### ISSUE THREAD

**Issue by akashban** [radical-cybertools/radical.entk#373]
Hi,
I am trying to install EntK on my desktop. I tried to execute the export_radical_pilot_dburl=' ' command. The format in which I obtain the URI from MongoDB Atlas does not seem be recognized by EnTK. This is the following error when I try to run get_started.py
```
tk/examples/user_guide$ python get_started.py 
EnTK session: re.session.polomastaan-Lenovo-Yoga-710-15ISK.polo-mastaan.018158.0012
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
                                                                             err
All components terminated
Traceback (most recent call last):
  File "get_started.py", line 59, in <module>
    appman.run()
  File "/home/polo-mastaan/myenv/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 355, in run
    self._rmgr._submit_resource_request()
  File "/home/polo-mastaan/myenv/local/lib/python2.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 133, in _submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/home/polo-mastaan/myenv/local/lib/python2.7/site-packages/radical/pilot/session.py", line 255, in __init__
    % (self._dburl, e))
RuntimeError: session create failed [mongodb+srv://akashbanerjee:Polopolo123%24@cluster0-bpgrg.mongodb.net/test]: cluster0-bpgrg.mongodb.net:27017: [Errno -2] Name or service not known
```

My best guess is that the format of the URI is not correct. I tried to manually set it using the following link 

https://docs.mongodb.com/manual/reference/connection-string/

This effort made no difference to the above output. I would be grateful for any help.

Thanks
Akash

**Comment by andre-merzky** [comment]
Hi Akash, 

we are indeed not able to handle URIs which point to MongoDB clusters, and adding support for that is somewhat difficult: we internally use an UR**L** to represent the MongoDB endpoint, but the cluster endpoints are not well formed URLs, but, as you said UR**I**s.  Given that we plan to remove the dependency of the stack from MongoDB over the next months, we are hesitant to invest in fixing this specific problem.  

Are you able to infer a URL of the form `mongodb://user:pass@host:port/db` for your MongoDB instance?  This format should be recognized by our stack.

**Comment by SrinivasMushnoori** [comment]
@andre-merzky for a context: Akash is a PhD student in my group in Chemical Engineering, whose thesis has a section involving writing specialized workflows, hence the need for EnTK.

**Comment by andre-merzky** [comment]
In that case, does it make sense if Akash shares the DB with you which Matteo provided?

**Comment by SrinivasMushnoori** [comment]
Happy to. However, I'll need to understand how to properly manage the DB. I don't want to run a job to find that the DB has been filled up (and presumably neither does Akash). When MLab was our friend, I would just get rid of a full DB and make a fresh one because it was so easy to do. Now I cannot, since I have only ONE db instance to work with (and share). We could discuss how to manage the db (i.e. when and how we would wipe it, etc.) on our call this evening.

Am I making sense?

**Comment by mturilli** [comment]
Our machine is pretty beefed up, it should be fine for a while. Potentially, the DB has around 1TB of space available, using your DB with two users should be fine. I would try that out and if you notice any issue, I will create a DB (on the same server) also for Akash. Would that work for you?

**Comment by SrinivasMushnoori** [comment]
That should be perfect. Thank you!

**Comment by mturilli** [comment]
Great, I am going to close this ticket then.
