### ISSUE TITLE
Random units fail with "Authentication Failed" in the STDERR file (PSC Bridges). 

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#374]
Trying to run on Bridges. This is random, typically tends to happen when medium-sized jobs are run (200ish concurrent units). I tried looking for why, but I can find nothing aside from random units failing with "Authentication Failed". There seems to be no rhyme or reason for this. I tried recursively greping for `error`, `ERROR`, `failed`,`FAILED`,`failure`.... and all combinations of keywords of the sort.

The sandbox is large and for some reason `radical-pilot-fetch-logfiles` hangs, so I have run `chmod 777 foldername` on the directory. This should give you access to the full sandbox. The path is below:
```/pylon5/mr560ip/mushnoor/radical.pilot.sandbox/re.session.mcewan.engr.rutgers.edu.scm177.018159.0004```

One such failed unit is 
```/pylon5/mr560ip/mushnoor/radical.pilot.sandbox/re.session.mcewan.engr.rutgers.edu.scm177.018159.0004/pilot.0000/unit.000053```

Assistance is appreciated.
Thanks

EDIT:
apologies, stack is:

```
(Env_RepEx)scm177@mcewan:~/RADICAL-LAB/repex_3/examples$ radical-stack

  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : 0.72.0
  radical.entk         : 0.7.17
  radical.pilot        : 0.72.0
  radical.saga         : 0.72.0
  radical.utils        : 0.72.0
```

I use entk 0.7.17 because 0.72.0 breaks (separate ticket about that shortly)

**Comment by andre-merzky** [comment]
I assume that the configuration uses ssh for task execution, and you are running out of ssh connections.  Can you check if that assumption is correct?  

```
grep 'launch_method'  agent_0.cfg
```
in the pilot sandbox should tell...

**Comment by andre-merzky** [comment]
This is fixed by using an alternative launch method or by increasing unit size (thus limiting concurrency)
