### ISSUE TITLE
radical.entk.exceptions

### ISSUE THREAD

**Issue by akashban** [radical-cybertools/radical.entk#377]
Hi,

I used the MongoDB instance provided by Srinivas to run get_started.py. It works. However, I get this error 

```
Traceback (most recent call last):
  File "get_started.py", line 59, in <module>
    appman.run()
  File "/home/polo-mastaan/myenv/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 360, in run
    'ended in state %s' % res_alloc_state)
radical.entk.exceptions.EnTKError: Cannot proceed. Resource ended in state FAILED
```

Please let me know what I should do to fix the above.

Kind Regards,
Akash

**Comment by andre-merzky** [comment]
Hi @SrinivasMushnoori, you know your way around a bit in RE by now, can you have a look together with Akash to check whats up?  Have look for `ERROR` messages in the log files on the client and resource side, that's always a good starting point.

If you don't find the time or get stuck, obviously let us know, and we'll jump on it, ok?

Thanks, Andre.

**Comment by SrinivasMushnoori** [comment]
Reasonable. Will take over and ping you if necessary.

**Comment by SrinivasMushnoori** [comment]
@akashban Can you please upload your log files?
```
export RADICAL_LOG_LVL=DEBUG
export RADICAL_LOG_TGT=verbose_logs.log
```
And rerun the example. You should be able to find the logfile in the same directory. Can you please attach that?

Additionally, after you have run the script again (and hit the error) please run
```
export RADICAL_PILOT_DBURL=<the MDB URL that I sent you>
radical-pilot-fetch-logfiles <sessionname>
```
The session name should look something like `re.session.something.something.rutgers.edu.018159.0004` 

When you have all these files, please tar it up and upload. I'll have a look.

**Comment by akashban** [comment]
Thank you for the instructions @SrinivasMushnoori . I have attached the log files here. Please have a look at your convenience. 
[error_9_26_2019.zip](https://github.com/radical-cybertools/radical.entk/files/3660046/error_9_26_2019.zip)

**Comment by SrinivasMushnoori** [comment]
@akashban Terribly sorry for the delay. I am unable to see much in these logs. Can you please zip your **pilot sandbox** and send me that?
It should probably be in
```
$~/radical.pilot.sandbox/rp.session.polomastaan-Lenovo-Yoga-710-15ISK.polo-mastaan.018165.0000
```

Or something like that. I might need to dig into agent side logs to figure out what's going on.

**Comment by akashban** [comment]
Thanks Srinivas for the instructions. The issue has been solved. I am closing the ticket
