### ISSUE TITLE
do not pollute user dir

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#380]

**Comment by lee212** [comment]
May I ask for some context?

**Comment by andre-merzky** [comment]
Yes, of course - sorry, that ticket description is really useless!

When running an RE example or the test suite, there appear many files in the workdir which are not cleaned up after the run.  Those files should be cleaned up after execution.

**Comment by iparask** [comment]
No files and folders are currently created while running the test suite. I agree this should not be case and it had to do with the fact that we were running examples to test. I will close this issue
