### ISSUE TITLE
jsrun job aborted with radical-entk 

### ISSUE THREAD

**Issue by hengma1001** [radical-cybertools/radical.entk#382]
I was running a working workflow on summit with entk. 
One of the stages collapsed during the run. 
But while testing on login node or a single `jsrun` job, it worked without any issue. 
I hope you wouldn't mind looking at it. 

My current radical stack is 
```
/ccs/home/hm0/.conda/envs/entk/lib/python2.7/site-packages/radical/utils
/ccs/home/hm0/.conda/envs/entk/lib/python2.7/site-packages/radical/saga
/ccs/home/hm0/.conda/envs/entk/lib/python2.7/site-packages/radical/pilot
/ccs/home/hm0/.conda/envs/entk/lib/python2.7/site-packages/radical/entk

  python               : 2.7.15
  pythonpath           : /sw/summit/xalt/1.1.4/site:/sw/summit/xalt/1.1.4/libexec
  virtualenv           : entk

  radical.entk         : 0.7.17
  radical.pilot        : 0.70.0-v0.62.0-548-g58011c1@experiment-periscope
  radical.saga         : 0.70.0-v0.62.0-40-g6b80c39@devel
  radical.utils        : 0.70.0
```

The jobs is at `/gpfs/alpine/scratch/hm0/bip179/hyperspace_hm0/microscope/experiments_folding/experiments_vhp_fold` and the sandbox dir is `/gpfs/alpine/bip179/scratch/hm0/radical.pilot.sandbox/re.session.login1.hm0.018186.0000`. 

The error message is in `/gpfs/alpine/bip179/scratch/hm0/radical.pilot.sandbox/re.session.login1.hm0.018186.0000/pilot.0000/unit.000000/STDERR`. 

Thank you very much.

**Comment by andre-merzky** [comment]
I am afraid the sandbox is not accessible.  Could you please check the permissions (including the parent directories)?  Thanks!

**Comment by hengma1001** [comment]
@andre-merzky I made a copy of data at `/gpfs/alpine/bip179/world-shared/entk_issue_382`.

**Comment by lee212** [comment]
Do you still experience the same problem, `jsrun free() invalid next size`? because I can't replicate the error on my environment. I have similar rp stack like yours and my test run with your `entk_issue_382` directory seemed working as expected. FYI, the copy of my rp sandbox is at `/gpfs/alpine/world-shared/bip179/entk_issue_382/hrlee`

STDERR looks fine like:
```
Using TensorFlow backend.
2019-10-31 16:00:17.743876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9
40] Found device 0 with properties:
name: Tesla V100-SXM2-16GB
major: 7 minor: 0 memoryClockRate (GHz) 1.53
pciBusID 0004:04:00.0
Total memory: 15.75GiB
Free memory: 15.42GiB
2019-10-31 16:00:17.743911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9
61] DMA: 0
...
```
and STDOUT is also like:
```
['/gpfs/alpine/bip179/scratch/hrlee/debug/experiments_vhp_fold/MD_exps/VHP_exp/o
mm_runs_1571263510/output_cm.h5', '/gpfs/alpine/bip179/scratch/hrlee/debug/exper
iments_vhp_fold/MD_exps/VHP_exp/omm_runs_1571263511/output_cm.h5', '/gpfs/alpine
/bip179/scratch/hrlee/debug/experiments_vhp_fold/MD_exps/VHP_exp/omm_runs_157126
3512/output_cm.h5', '/gpfs/alpine/bip179/scratch/hrlee/debug/experiments_vhp_fol
d/MD_exps/VHP_exp/omm_runs_1571263513/output_cm.h5', '/gpfs/alpine/bip179/scratc
h/hrlee/debug/experiments_vhp_fold/MD_exps/VHP_exp/omm_runs_1571263514/output_cm
.h5']
Using model /gpfs/alpine/bip179/scratch/hrlee/debug/experiments_vhp_fold/CVAE_ex
ps/cvae_runs_12_1571263512/cvae_weight.h5 with loss 3.93273844446
Model latent dimension: 12
________________________________________________________________________________
__________________
Layer (type)                    Output Shape         Param #     Connected to

================================================================================
==================
input_1 (InputLayer)            (None, 36, 36, 1)    0
...
```

and the stack I used is
```
/ccs/home/hrlee/.conda/envs/rp/lib/python2.7/site-packages/radical/utils
/ccs/home/hrlee/.conda/envs/rp/lib/python2.7/site-packages/radical/saga
/ccs/home/hrlee/.conda/envs/rp/lib/python2.7/site-packages/radical/pilot
/ccs/home/hrlee/.conda/envs/rp/lib/python2.7/site-packages/radical/entk

  python               : 2.7.16
  pythonpath           : /sw/summit/xalt/1.1.4/site:/sw/summit/xalt/1.1.4/libexec
  virtualenv           : rp.copy

  radical.entk         : 0.70.0
  radical.pilot        : 0.70.3-v0.70.3-116-ge36a04f@devel
  radical.saga         : 0.70.0
  radical.utils        : 0.70.0
```

I will see if there is something I missed again.

**Comment by euhruska** [comment]
I see the same error on Summit.

**Comment by andre-merzky** [comment]
Until we can replicate the `jsrun` problem, you may want to switch to the `ornl.summit_prte` resource label which uses a different launch method.

**Comment by euhruska** [comment]
this ```jsrun``` issue happens for me every time for one of the tasks in one of the setups. Always a different task, but always replica number 9. In a different case, I just changed the name of the directory where the files were saved and it stopped happening.

**Comment by andre-merzky** [comment]
This is unexpected.  Can you please attach the agent sandbox of such a failed run to this ticket?  Thanks!

**Comment by euhruska** [comment]
unit 26 failed
[re.session.login2.eh22.018212.0055-local.zip](https://github.com/radical-cybertools/radical.entk/files/3839255/re.session.login2.eh22.018212.0055-local.zip)

**Comment by andre-merzky** [comment]
Apologies Eugen, I wasn't clear - with 'pilot sandbox' I meant the remote sandbox.

**Comment by euhruska** [comment]
it's 9Gb, can I share it on summit?

**Comment by andre-merzky** [comment]
Ouch - of course, thanks!

**Comment by euhruska** [comment]
it's at ```/gpfs/alpine/bip191/world-shared/re.session.login2.eh22.018212.0055```

**Comment by andre-merzky** [comment]
Thanks Eugen.  jsrun segfaults here even though the jsrun command and the resource file seem well-formed.  There is not much we can do besides opening an ticket with ORNL.  I can take care of this, please leave the sandbox in place for the time being.  Meanwhile, you may want to switch to `ornl.summit_prte` as resource target to avoid jsrun related problems.

**Comment by andre-merzky** [comment]
This is now ORNL issue #414851

**Comment by euhruska** [comment]
thanks

**Comment by euhruska** [comment]
```ornl.summit_prte``` doesn't submit jobs for me

**Comment by mturilli** [comment]
@andre-merzky any news from ORNL?

**Comment by andre-merzky** [comment]
Oh, my aopologies - ORNL replied, but I missed the message.  Here it is:

> In STDERR, it looks like the main error is
> *** Error in `/opt/ibm/spectrum_mpi/jsm_pmix/bin/stock/jsrun': free(): invalid next size (fast): 0x000000002c290740 ***
>
> Even though that's being tagged as "jsrun", I think it's possible that it could be originating in what jsrun is trying to run. And, there are a lot of memory-related operations that can cause that error.
> 
> It looks like this is a serial python script that uses the GPU, correct? I have not tried it myself, but I understand that the Arm Forge (DDT) debugger can handle python. So, it may be worth trying to see if it's possible to isolate what might be tripping the error.
> 
> The best way to use DDT is probably to download the remote client on https://developer.arm.com/tools-and-software/server-and-hpc/arm-architecture-tools/downloads/download-arm-forge. There's some information (including a link to the download site) at https://www.olcf.ornl.gov/tutorials/forge-remote-client-setup-and-usage/.
> 
> Thanks,
> Bill


Is there a way to have a closer look at the workload (replica 9 for @euhruska ) to make sure it is not an application level problem?  One option I could see is two wrap the job in a small shell script to check error codes etc. before returning to jsrun:
```sh
#!/bin/sh
trap echo "trapped HUP  " HUP
trap echo "trapped INT  " INT 
trap echo "trapped QUIT " QUIT 
trap echo "trapped KILL " KILL 
trap echo "trapped TERM " TERM
trap echo "trapped EXIT " EXIT 

exe="$1"; shift
args=$*
exe=
echo "start $exe $args"
$exe $args
ret=$?
echo "stop $exe $args: $ret
exit $ret
```
This way, segfaults etc. should not fall through to jsrun, or so I hope.

**Comment by iparask** [comment]
Hello @hengma1001, is this still an issue for you? Thank you

**Comment by hengma1001** [comment]
@iparask I haven't been using summit for a while. But I think we can close it.
