### ISSUE TITLE
ValueError: Cannot find module radical.saga

### ISSUE THREAD

**Issue by krb09** [radical-cybertools/radical.entk#383]
Hello, 

I was working with the ENTK get_started.py example on the local machine using two.radical-project.org. I received the following error:
"    
ended in state %s' % res_alloc_state)
radical.entk.exceptions.EnTKError: Cannot proceed. Resource ended in state FAILED
"
My current stack is:
python                : 2.7.12
pythonpath        :
virtualenv           : /home/krb09/myenv

radical.entk        : 0.72.1
radical.pilot        : 0.73.1
radical.saga       : 0.72.1
radical.utils        : 0.72.0

After speaking with Matteo, he suggested me to open a ticket and attach the log file.
[rp.log](https://github.com/radical-cybertools/radical.entk/files/3752729/rp.log)

Thank you very much.

**Comment by AymenFJA** [comment]
Hello, 

Can you please create a tarball of your session.tar (you should see a session folder) in your directory that you are running your script from. Include that tarball in your ticket.

Best,
Aymen

**Comment by krb09** [comment]
Sure. I have attached the following. Let me know if you need anything  else from my side.

[session.tar.gz](https://github.com/radical-cybertools/radical.entk/files/3752874/session.tar.gz)

Thank you, 
Kartik

**Comment by mturilli** [comment]
I worked on this with @krb09 checking all the boxes I could find. I enabled localhost passwordless ssh that was missing and DEBUG verbosity. Based on the logs I saw, the problem seems to be with EnTK or at least I did not find any explicit failure at RP level.

**Comment by krb09** [comment]
This the new session files after Aymen helped me. The problem persists. 
[failed_session_rp.tar.gz](https://github.com/radical-cybertools/radical.entk/files/3763905/failed_session_rp.tar.gz)

**Comment by andre-merzky** [comment]
> will be deleted

Do I understand correctly that before the run, something like
```sh
python -c 'import radical.saga as rs'
```
works, but it does not work anymore after the run, so the module gets physically deleted?  Ouch.  What is the OS version and on what machine are you running?  How was RP installed?  Thanks!

**Comment by krb09** [comment]
Yes, correct.
We are running the example locally on
Machine: radical.two VM.
env: virtualenv
Python: python 2.7.
OS version : 16.04
We installed Radical.pilot via pip .

**Comment by krb09** [comment]
Hello, 
I tried to replicate this with @iparask and we could not. So we cleaned everything up. We removed the .cache, .conda, and .radical files. 
After re-creating the environment by installing radical-pilot and radical-entk using pip, it started to work correctly. We do not know what led to the error before. Let me know if I close the ticket.

**Comment by andre-merzky** [comment]
Its a bit scary that a install can remove modules in the virtualenv.  Please reopen if it happens again, and we'll track it down.  Glad that it works now of course :-)

**Comment by iparask** [comment]
I'm starting to think that it might be a failed `pip install --upgrade`.

This is an example upgrading `radical.utils`:
```
Successfully built radical.utils
Installing collected packages: radical.utils
  Found existing installation: radical.utils 0.90.3
    Uninstalling radical.utils-0.90.3:
      Created temporary directory: /home/iparask/test_rp/bin/~_pycache__
      Removing file or directory /home/iparask/test_rp/bin/__pycache__/
      Created temporary directory: /tmp/pip-uninstall-k9mzwoum
      Removing file or directory /home/iparask/test_rp/bin/radical-bridge
      Removing file or directory /home/iparask/test_rp/bin/radical-stack
      Removing file or directory /home/iparask/test_rp/bin/radical-utils-fix-headers.pl
      Removing file or directory /home/iparask/test_rp/bin/radical-utils-mongodb.py
      Removing file or directory /home/iparask/test_rp/bin/radical-utils-pwatch
      Removing file or directory /home/iparask/test_rp/bin/radical-utils-pylint.sh
      Removing file or directory /home/iparask/test_rp/bin/radical-utils-version
      Created temporary directory: /tmp/pip-uninstall-15pvy198
      Removing file or directory /home/iparask/test_rp/lib/python3.5/site-packages/radical.utils-0.90.3-py3.5-nspkg.pth
      Created temporary directory: /home/iparask/test_rp/lib/python3.5/site-packages/~adical.utils-0.90.3.dist-info
      Removing file or directory /home/iparask/test_rp/lib/python3.5/site-packages/radical.utils-0.90.3.dist-info/
      Created temporary directory: /home/iparask/test_rp/lib/python3.5/site-packages/radical/~tils
      Removing file or directory /home/iparask/test_rp/lib/python3.5/site-packages/radical/utils/
      Created temporary directory: /home/iparask/test_rp/share/radical.utils/examples/~mq
      Removing file or directory /home/iparask/test_rp/share/radical.utils/examples/zmq/
      Successfully uninstalled radical.utils-0.90.3

Successfully installed radical.utils-0.90.3
```

As you can see it removes the `utils` first to uninstall and then it places the new one. It's possibility, but still scary
