### ISSUE TITLE
`_` special character is not allowed in names of Pipeline, Stage, and Task; failing data sharing

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#392]
To exchange or share data between tasks, e.g. `copy_input_data`, PST names are referenced but the underscore `_` is used for parsing. The errors, otherwise, is seen like, if names contain this character:

```
p = Pipeline()
p.name = 'simple_mdff'
...
EnTKError: Value for attribute placeholder of object task incorrect.
 Expected value ('$Pipeline_(pipeline_name)_Stage_(stage_name)_Task_(task_name) 
or $SHARED',),
but got ['$Pipeline', 'simple', 'mdff', 'Stage', 'Generating a simulated density map', 
'Task', 'Starting to load the target PDB'].
``` 

pipeline name `simple_mdff` was accidentally sliced by the delimiter `_`. 

A possible solution would be:
- encoding names by base64 as it contains three special characters only `+, /,  =`
- prohibit using `_` in names

https://github.com/radical-cybertools/radical.entk/blob/d249c2c95db5987c42ed84a52e796e00ac8f4e2a/src/radical/entk/execman/rp/task_processor.py#L59

**Comment by iparask** [comment]
I suggest excluding any special character from the pipeline, stage, and task names, apart from `.`.

**Comment by mturilli** [comment]
I would agree but then I think we should check for naming before execution and raise an error if a name uses illegal characters.
