### ISSUE TITLE
Workflow Processor does not advance stages

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#399]
EnTK faces issues where the execution does not proceed when a stage is completed. I executed the getting started user guide example with the following stack:
```
  python               : 3.7.5
  pythonpath           :
  virtualenv           : rct_test

  radical.entk         : 0.90.6-v0.72.0-81-gad4d968c@fix-issue_393
  radical.pilot        : 0.90.8-v0.90.1-169-g1c35e226@devel
  radical.saga         : 0.90.6-bv0.72.1-67-g5deb253b@devel
  radical.utils        : 0.90.7-v0.90.3-176-g3cc0cd0@devel
```

When a stage is completed EnTK's workflow processor, check is there is a stage `post_exec` directive, [here](https://github.com/radical-cybertools/radical.entk/blob/fix/issue_393/src/radical/entk/appman/wfprocessor.py#L353).
If there is, it gets executed. If not, it checks whether the respective pipeline is completed.

This last statement is where the bug lies. When a stage post exec is executed the pipeline [goes to the new stage](https://github.com/radical-cybertools/radical.entk/blob/fix/issue_393/src/radical/entk/appman/wfprocessor.py#L412)
The pipeline does not move to the next stage if there is no post_exec, [no else](https://github.com/radical-cybertools/radical.entk/blob/fix/issue_393/src/radical/entk/appman/wfprocessor.py#L353) statement.

As a result, in the case of the getting started example, the stage number never increases, and the pipeline never get completed, and does not move in the `DONE` state. This in turn, does not allow the execution to finish.

Furthermore, I think that this bug would cause issues to any pipeline that has a stage without a post exec statement. The stage number would not be increased, as a result a completed stage would always be checked and the execution would stay there.

I suggest the following fix, [here](https://github.com/radical-cybertools/radical.entk/blob/fix/issue_393/src/radical/entk/appman/wfprocessor.py#L353):
```python
                    # Check if the current stage has a post-exec
                    # that needs to be executed
                    if stage.post_exec:
                        self._execute_post_exec(pipe, stage)
                    else:
                         pipe._increment_stage()
                    # If pipeline has completed, make state
                    # change
                    if pipe.completed:
```

I also suggest the fix to be implemented in the `fix/issue_393` branch which provides a fix for the termination calls.

**Comment by andre-merzky** [comment]
Fascinating.  This seems to explain the issue nicely - but its surprising that it worked before...  Oh well, we can dig through git history once it's fixed.

Fixing the way you suggest works - but please consider that the state increment can then happen in one of two places, which makes the control flow a bit harder to follow.  Maybe move the `if pipe.state == states.SUSPENDED:` conditional out of the post-exec execution into `update_dequeue_task`?  I think all state transitions should belong there, not scattered over subroutines?
