### ISSUE TITLE
Read workflow description file

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#402]
This is a feature request for reading workflows from json. I would like to be able to pass a workflow as a json to EnTK and that to convert it to a set of pipeline objects. The supporting use case is the Campaign Manager, I'm designing and developing.

Let me know what you think.

**Comment by lee212** [comment]
There were attempts to separate data and process using structured file formats. For example, [extasy](https://github.com/ClementiGroup/ExTASY/blob/master/settings_extasy_tica_ala12_small.wcfg) used cfg file for sim/analysis steps with resource definitions and [mdff-error](https://github.com/radical-collaboration/MDFF-Error/blob/master/workflow_cfg.yml) used yaml. Yes, I agree the necessity of data separation using these file formats.

**Comment by iparask** [comment]
Yes, something like that! But I thought that it would be better if EnTK could read the json file it writes for a workflow ([here](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/utils/prof_utils.py#L225)), as it would provide consistency and reproducibility in my opinion.

**Comment by andre-merzky** [comment]
I would think that can easily be implemented by a standalone EnTK script.  Is there an advantage compared to providing that capability in EnTK directly?

**Comment by iparask** [comment]
I'm considering the functionality of my campaign manager. I think that having an API call to submit workflows to the selected workflow engine would make the integration more maintainable. 

The advantage that I see it that is separates the functionalities nicely. The campaign manager has to verify that the json is of the correct format and then EnTK can translate it and start executing it. As @lee212 said, there are already 2 use cases that use cfg and yaml files to describe workflows. Offering a single format would offer better portability, easier debugging because you would only ask for the json file. Now, I am not fixed to the format, but I believe that it should be the same as the one offered by the `write_workflow` method.

In addition, I find it natural to be part of the API, since the reverse operation is already offered, right?

**Comment by andre-merzky** [comment]
Thank @iparask, that input helps me to clarify my reservation.  The result of this discussion may well be that we implement exactly what you request, but my concern is related to the scope of the feature.

`write_workflows` is a misnomer, or at least it is incomplete: the file format does *not* capture the full expressiveness of EnTK's workflow enactment.  Instead, it is a recording of what that enactment decided and executed, so a recording of the *resulting* workflow, somewhat independent of what was called in the API.  For simple, static workflows that might be the same: you specify a pipeline of stages and tasks, and that's what is recorded in the `workflows.json`.  But as soon as your application makes a branch
```python
if task_1.success:
    submit(task_2)
else:
    submit(task_3)
```
, this is not captured anymore.  The same holds for post-processing directives in stages, for suspend and sync ops, etc.  The `workflow.json` we write is *not* a workflow description language (thank god).

Parts of the EnTK API can certainly be mapped to a workflow description language.  My concerns wrt. scope are thus:

  - there exists a plethora of WF description languages and meta-languages, why the hell should we invent our own?
  - other parts of the API are not trivial to map, and are not covered in our `wrokflow.json` output, what happens to those?

**Comment by iparask** [comment]
Hello @andre-merzky,

>write_workflows is a misnomer, or at least it is incomplete: the file format does not capture the full expressiveness of EnTK's workflow enactment.

I agree with you, it does not capture the actual workflow, and it mainly captures the execution.

>there exists a plethora of WF description languages and meta-languages, why the hell should we invent our own?
I am not concerned to with the language that is used. I just mentioned `json` because that is what `write_workflow` outputs. Let me check what other WMF use and see if there is one that is used by at least a few of them.

>other parts of the API are not trivial to map, and are not covered in our `workflow.json` output, what happens to those?

Can you give me an example? Do you mean the dynamic execution and the `stop/resume` feature?

**Comment by andre-merzky** [comment]
> Can you give me an example? Do you mean the dynamic execution and the `stop/resume` feature?

Yes, exactly - the things which make a static workload _flow_: decision points, loops, and data dependencies.

**Comment by mturilli** [comment]
@iparask can we close this ticket?

**Comment by iparask** [comment]
Yes
