### ISSUE TITLE
AppManager non-blocking run and callbacks

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#405]
When the `appmanager` `run` method is invoked the execution blocks. In addition, there is no method to capture the state of the workflow through EnTK's API. 

As far as I understand it, in order to execute multiple workflows concurrently I would have to start a thread that creates an application manager, run, and check whether that specific thread has return. Base on the return code of the thread I will be able to understand whether the execution succeeded or not. Do you think this sequence of events is correct?

Is there a way to introduce a run with a callback, where the callback will be executed based on what is happening with the workflow?

Thank you

**Comment by andre-merzky** [comment]
Would those callbacks return state changes for *all* entities (workflow, pipelines, stages, tasks), or only for the workflow itself?  Note also that RE does not have the notion of a `state of the workflow` really, as no respective `Worrkflow` object, nor does a state model for a workflow exist.  Adding that might be worthwhile (and would also provide a clean way to execute multiple workflows), but is likely a non-trivial extension.  So what information do you exactly need, apart from `workflow execution completed`?

**Comment by iparask** [comment]
I do not think I need all the states. I need 3 basic states such as `PENDING`, `EXECUTING`, `DONE`. It's fine if it comes from the AppManager like: `WAITING`, `EXECUTING` (a workflow), `DONE`. This will allow me to monitor the execution of multiple Workflow/AppManagers.

**Comment by andre-merzky** [comment]
`PENDING` is not defined for the workflow, and RE does not know about `WAITING` and `EXECUTING` either - but one could assume that `PENDING is everything before the first pipeline goes into `SUBMITTED`?  Similarly,  `DONE` could mean that all pipelines are in a final state (`DONE`, `FAILED`, `CANCELED`)?  Also, we may want to reuse the states available in RE though instead of creating new ones?

**Comment by iparask** [comment]
> `PENDING` is not defined for the workflow, and RE does not know about `WAITING` and `EXECUTING` either - but one could assume that `PENDING is everything before the first pipeline goes into `SUBMITTED`? 

I would say so.

> Similarly, `DONE` could mean that all pipelines are in a final state (`DONE`, `FAILED`, `CANCELED`)? 

Yes. I would say 

> Also, we may want to reuse the states available in RE though instead of creating new ones?

Of course. I do not remember the exact state names, but I agree we should use the same things.

**Comment by iparask** [comment]
I'll close this for now. Will reopen when it is needed again
