### ISSUE TITLE
failure to generate session json file

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.entk#407]
Hi,
I am running a sample radical entk example (get_started.py) on two.radical-project. However it fails to generate <session>.json file. The logs are attached. Radical stack info is included.
Thanks,
Aydin

[sessionlogs.zip](https://github.com/radical-cybertools/radical.entk/files/4087604/sessionlogs.zip)
[verboselog.zip](https://github.com/radical-cybertools/radical.entk/files/4087606/verboselog.zip)

```
radical-stack:
  python               : 3.6.9
  pythonpath           :
  virtualenv           : /home/aydins/env3

  radical.analytics    : 0.90.7
  radical.entk         : 1.0.0-v1.0.0-4-g2eac2ef5@devel
  radical.pilot        : 1.0.0
  radical.saga         : 1.0.0
  radical.utils        : 1.0.0
```

**Comment by lee212** [comment]
Did you set ```
RADICAL_LOG_TGT=radical.log
RADICAL_LOG_LVL=DEBUG
RADICAL_PROFILE=TRUE
```

**Comment by aydinsaribudak** [comment]
yes these are the commands:
export RADICAL_ENTK_PROFILE="TRUE"
export RADICAL_LOG_LVL="DEBUG"
export RADICAL_LOG_TGT="radical.log"
export RADICAL_PROFILE="TRUE"

**Comment by iparask** [comment]
Did you setup the `write_workflow` attribute of the `Appmanager` to `true`? It is `false` by default and the `getting_started.py` example does not write that value as `true`.

**Comment by lee212** [comment]
I believe `true` is default, maybe not?

**Comment by aydinsaribudak** [comment]
I didn't set `write_workflow`. Could you please provide the command to set `write_workflow` to `true` ?

**Comment by iparask** [comment]
@aydinsaribudak you can find it [here](https://radicalentk.readthedocs.io/en/stable/api/appman.html). Also, the `verboselog` you attached above is the STDOUT, and not log messages. May I suggest that when you run an example to use `2>verbose.log` instead of `>verbose.log`?

@lee212, the `Appmanager` has it set to `None` at the constructor ([here](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/appman/appmanager.py#L73)), which then updates it with what exists in the default config file ( [here](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/appman/appmanager.py#L159) and [here](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/appman/config.json#L10))

**Comment by lee212** [comment]
I see that. Thanks Giannis. However, rp profile is set which will generate profile data in a json file format. I am not sure how it differs from `write_workflow` but at least Aydin's result should include `json` file as he claimed to have env variables for profiling.

**Comment by iparask** [comment]
If you see in the `sessionlog` there is nothing from the agent side. @aydinsaribudak do you see any log files in the `radical.pilot.sandbox` for the specific session?

EnTK also writes a `json` file that shows after the execution at which specific unit each task was mapped. 

If we are discussing about RP's profiles and log files, I did not see anything. It might make sense for @aydinsaribudak to include the above flags, apart from `RADICAL_LOG_TGT` to his `.bashrc`

**Comment by aydinsaribudak** [comment]
@iparask 
Thanks for the suggestion for using `2>verbose.log`. It may be also helpful for other users to update radical.entk instructions appearing in the write field when we are creating a ticket.
yes there is a log file under sandbox, and it is available with the sessionlog.zip as a folder named as <session>/<session>/
Ok Thanks. I ll include 'RADICAL_LOG_TGT' into `.bashrc`
 I ll set `write_workflow` and let both you know whether it helps or not.
Thanks

**Comment by aydinsaribudak** [comment]
@iparask 
{sessionname}.json file is still not generated with the following edits:

This is how I call AppManager constructor: 
`appman = AppManager(hostname=hostname, port=port, write_workflow = True)`

These are the flags I included into `.bashrc`
```
export RADICAL_ENTK_PROFILE="TRUE"
export RADICAL_LOG_LVL="DEBUG"
export RADICAL_PROFILE="TRUE"
```

Log files are attached.
[verboselogs.zip](https://github.com/radical-cybertools/radical.entk/files/4092409/verboselogs.zip)
[sessionlogs.zip](https://github.com/radical-cybertools/radical.entk/files/4092411/sessionlogs.zip)
[sandboxlogs.zip](https://github.com/radical-cybertools/radical.entk/files/4092412/sandboxlogs.zip)

Thanks
Aydin

**Comment by aydinsaribudak** [comment]
@lee212
json file has been generated successfully for `get_started.py` and `add_pipeline.py` scripts today. I am not sure why it is worked this time, because I have followed the same steps to run the script. 
The only difference compared to earlier successful runs is with the json file name. It is with a prefix "radical.entk", so the full name of the file is radical.entk.{sessionname}.json
Since it is generated successfully, I am closing the issue. Thanks.
