### ISSUE TITLE
Python version problem

### ISSUE THREAD

**Issue by Abdullah-Ghani** [radical-cybertools/radical.entk#409]
After setting up the environment, installing radical entk with pip leads to the following errors.

$pip install radical.entk
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting radical.entk
  Using cached radical.entk-1.0.0.tar.gz (54 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/abdullahghani/myenv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-MlR24k/radical.entk/setup.py'"'"'; __file__='"'"'/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-MlR24k/radical.entk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-MlR24k/radical.entk/pip-egg-info
         cwd: /private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-MlR24k/radical.entk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-MlR24k/radical.entk/setup.py", line 142, in <module>
        raise RuntimeError('%s requires Python 3.5 or higher' % name)
    RuntimeError: radical.entk requires Python 3.5 or higher
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by lee212** [comment]
`pip install radical.entk==0.72.1` will allow you to use python2 compatible version.

I will check if we can continue supporting `pip` installation for python2 environment but in the meantime, please consider upgrading your python.

**Comment by mturilli** [comment]
@Abdullah-Ghani , I echo @lee212 comment, you should directly start to work with python 3 version of our stack, avoiding to use a python 2.7 stack.

**Comment by Abdullah-Ghani** [comment]
yes.
I have updated my python and pip to the the most updated versions but ran into a different issue. 
recreated below.

(myenv) nbp-172-61:~ abdullahghani$ python -V
Python 3.7.6
(myenv) nbp-172-61:~ abdullahghani$ pip3 install radical.entk
Processing ./Library/Caches/pip/wheels/c2/0e/a3/d28a7867f13d8dfe4a338fdc1f4560e2b246ea6d300d7efbd2/radical.entk-1.0.0-cp37-none-any.whl
Requirement already satisfied: radical.utils in /usr/local/lib/python3.7/site-packages (from radical.entk) (1.0.0)
Processing ./Library/Caches/pip/wheels/ba/fe/1f/98eb73d1dcbefa9006a2fce7d8668a826e86137a1ad4dd4b95/radical.pilot-1.0.0-cp37-none-any.whl
Requirement already satisfied: sphinx in /usr/local/lib/python3.7/site-packages (from radical.entk) (2.3.1)
Requirement already satisfied: pika==0.13.0 in /usr/local/lib/python3.7/site-packages (from radical.entk) (0.13.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.7/site-packages (from radical.utils->radical.entk) (3.10.1)
Requirement already satisfied: regex in /usr/local/lib/python3.7/site-packages (from radical.utils->radical.entk) (2020.1.8)
Requirement already satisfied: future in /usr/local/lib/python3.7/site-packages (from radical.utils->radical.entk) (0.18.2)
Requirement already satisfied: munch in /usr/local/lib/python3.7/site-packages (from radical.utils->radical.entk) (2.5.0)
Requirement already satisfied: msgpack in /usr/local/lib/python3.7/site-packages (from radical.utils->radical.entk) (0.6.2)
Requirement already satisfied: wheel in /usr/local/lib/python3.7/site-packages (from radical.utils->radical.entk) (0.33.6)
Requirement already satisfied: colorama in /usr/local/lib/python3.7/site-packages (from radical.utils->radical.entk) (0.4.3)
Requirement already satisfied: netifaces in /usr/local/lib/python3.7/site-packages (from radical.utils->radical.entk) (0.10.9)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.7/site-packages (from radical.utils->radical.entk) (1.1.10)
Requirement already satisfied: pyzmq in /usr/local/lib/python3.7/site-packages (from radical.utils->radical.entk) (18.1.1)
Collecting radical.saga>=0.90
  Using cached radical.saga-1.0.1.tar.gz (326 kB)
Processing ./Library/Caches/pip/wheels/01/57/3e/efd47a531ba9b41bdcafe39df160b1ed5bbd0ad9a2fdd93054/python_hostlist-1.20-cp37-none-any.whl
Requirement already satisfied: msgpack-python in /usr/local/lib/python3.7/site-packages (from radical.pilot->radical.entk) (0.5.6)
Requirement already satisfied: ntplib in /usr/local/lib/python3.7/site-packages (from radical.pilot->radical.entk) (0.3.3)
Requirement already satisfied: imagesize in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (1.2.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (20.0)
Requirement already satisfied: sphinxcontrib-jsmath in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (1.0.1)
Requirement already satisfied: sphinxcontrib-serializinghtml in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (1.1.3)
Requirement already satisfied: sphinxcontrib-htmlhelp in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (1.0.2)
Requirement already satisfied: sphinxcontrib-qthelp in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (1.0.2)
Requirement already satisfied: Jinja2>=2.3 in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (2.10.3)
Requirement already satisfied: docutils>=0.12 in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (0.16)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (2.0.0)
Requirement already satisfied: babel!=2.0,>=1.3 in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (2.8.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (42.0.2)
Requirement already satisfied: sphinxcontrib-devhelp in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (1.0.1)
Requirement already satisfied: requests>=2.5.0 in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (2.22.0)
Requirement already satisfied: sphinxcontrib-applehelp in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (1.0.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (0.7.12)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python3.7/site-packages (from sphinx->radical.entk) (2.5.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from munch->radical.utils->radical.entk) (1.14.0)
Requirement already satisfied: apache-libcloud in /usr/local/lib/python3.7/site-packages (from radical.saga>=0.90->radical.pilot->radical.entk) (2.8.0)
Requirement already satisfied: parse in /usr/local/lib/python3.7/site-packages (from radical.saga>=0.90->radical.pilot->radical.entk) (1.14.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/site-packages (from packaging->sphinx->radical.entk) (2.4.6)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/site-packages (from Jinja2>=2.3->sphinx->radical.entk) (1.1.1)
Requirement already satisfied: pytz>=2015.7 in /usr/local/lib/python3.7/site-packages (from babel!=2.0,>=1.3->sphinx->radical.entk) (2019.3)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->radical.entk) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->radical.entk) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->radical.entk) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->radical.entk) (2019.11.28)
Building wheels for collected packages: radical.saga
  Building wheel for radical.saga (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py'"'"'; __file__='"'"'/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-wheel-vm9it5kx
       cwd: /private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/
  Complete output (22 lines):
  Traceback (most recent call last):
    File "setup.py", line 143, in <module>
      raise RuntimeError('%s requires Python 3.5 or higher' % name)
  RuntimeError: radical.saga requires Python 3.5 or higher
  Traceback (most recent call last):
    File "/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py", line 128, in get_version
      '%s/%s'   % (mod_root, sdist_name))  # copy into tree
    File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 248, in copy
      copyfile(src, dst, follow_symlinks=follow_symlinks)
    File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
      with open(src, 'rb') as fsrc:
  FileNotFoundError: [Errno 2] No such file or directory: 'dist/radical.saga-1.0.1.tar.gz'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py", line 148, in <module>
      version, version_detail, sdist_name = get_version(mod_root)
    File "/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py", line 137, in get_version
      raise RuntimeError('Could not extract/set version: %s' % e)
  RuntimeError: Could not extract/set version: [Errno 2] No such file or directory: 'dist/radical.saga-1.0.1.tar.gz'
  ----------------------------------------
  ERROR: Failed building wheel for radical.saga
  Running setup.py clean for radical.saga
Failed to build radical.saga
Installing collected packages: radical.saga, python-hostlist, radical.pilot, radical.entk
    Running setup.py install for radical.saga ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py'"'"'; __file__='"'"'/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-record-meqa5f3u/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/radical.saga
         cwd: /private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/
    Complete output (22 lines):
    Traceback (most recent call last):
      File "setup.py", line 143, in <module>
        raise RuntimeError('%s requires Python 3.5 or higher' % name)
    RuntimeError: radical.saga requires Python 3.5 or higher
    Traceback (most recent call last):
      File "/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py", line 128, in get_version
        '%s/%s'   % (mod_root, sdist_name))  # copy into tree
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 248, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: 'dist/radical.saga-1.0.1.tar.gz'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py", line 148, in <module>
        version, version_detail, sdist_name = get_version(mod_root)
      File "/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py", line 137, in get_version
        raise RuntimeError('Could not extract/set version: %s' % e)
    RuntimeError: Could not extract/set version: [Errno 2] No such file or directory: 'dist/radical.saga-1.0.1.tar.gz'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py'"'"'; __file__='"'"'/private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-install-5m7svhly/radical.saga/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2y/h5z5f5pd4px5zt4wt0q7fy5m0000gn/T/pip-record-meqa5f3u/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/radical.saga Check the logs for full command output.

**Comment by lee212** [comment]
Can you try again after pip upgrade? i.e. `pip install pip --upgrade` 20.0.1 is the latest version, btw.
No cache (`--no-cache-dir`) pip installation might help as well if you had corrupted egg and settings before.
