### ISSUE TITLE
ENTK ERROR (python 3.5): radical.entk.exceptions.EnTKError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by krb09** [radical-cybertools/radical.entk#411]
Hello,

I was working with the ENTK get_started.py and change_target.py examples on jetstream (stampede2 for change_target). I received the following error:

"
radical.entk.task_manager.0000.log:1580143434.432 : radical.entk.task_manager.0000 : 30173 : 139864122873600 : ERROR    : task_manager.0000 failed with the JSON object must be str, not 'bytes' " 

The above error kept repeating and the script did not terminate until I terminated it manually (ctrl + c). I faced similar issues for the change_target.py, but the script, in that case, terminated after ~10 mins.

My stack was:
  python                : 3.5.2
  pythonpath        :
  virtualenv           : /home/krb09/ve-entk

  radical.entk        : 1.0.0
  radical.pilot        : 1.0.0
  radical.saga       : 1.0.0
  radical.utils        : 1.0.0

After a bit of reading online, I figured out the error was for python version <3.7. I made a new virtualenv with python 3.7, and all the scripts worked fine. 

My current stack: 

  python                   : 3.7.6
  pythonpath           :
  virtualenv              : /home/krb09/ve-entk-3.7

  radical.entk          : 1.0.0
  radical.pilot          : 1.0.0
  radical.saga         : 1.0.1
  radical.utils          : 1.0.0

I don't know what the issue was initially, and I would be happy if someone could explain to me. Some of my colleagues were facing similar issues, so I thought I will update them with the solution.

**Comment by lee212** [comment]
The error message was raised because of the encoding/decoding failure of a json file but this shouldn't be a problem with python 3.6 or higher. I am afraid that EnTk does not support 3.5.2.

**Comment by lee212** [comment]
I will close this for now. Feel free to reopen anytime
