### ISSUE TITLE
use exception chaining

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#417]
See radical-cybertools/radical.utils/pull/210

**Comment by mturilli** [comment]
@iparask good for Dec release?

**Comment by iparask** [comment]
@andre-merzky is this the `from e` that I am adding in all exceptions? If yes, it is already happening as I test and lint files. Also, some parts of it is already released in November.

**Comment by andre-merzky** [comment]
Yes, indeed - I saw that you applied that in several places, and the remaining ones should be easy to do I guess...
