### ISSUE TITLE
failure to submit job on comet_ssh

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.entk#419]
Hi,
I couldnt submit job on comet_ssh. The log files are attached. `res_dict` from `get_started.py` is also included.

```
    res_dict = {
        'resource': 'xsede.comet_ssh',
        'walltime': 10,
        'cpus': 4,
        'project': 'unc100',
        'queue'  : 'compute',
        'schema' : 'gsissh'
    }
```

We checked Saga and get the following report on the console. It looks like the error is not from Saga layer.

```
Job ID    : None
Job State : New
Job State : Pending
Job State : Done
Exitcode  : 0
```

[sessionlogs.zip](https://github.com/radical-cybertools/radical.entk/files/4140319/sessionlogs.zip)
[verboselog.zip](https://github.com/radical-cybertools/radical.entk/files/4140320/verboselog.zip)

radical-stack:
```
  python               : 3.7.6
  pythonpath           :
  virtualenv           : /home/aydins/ve-entk

  radical.analytics    : 0.90.7-v0.72.0-35-g4f5242d@devel
  radical.entk         : 1.0.0
  radical.pilot        : 1.0.0
  radical.saga         : 1.0.1
  radical.utils        : 1.0.0
```

**Comment by lee212** [comment]
Hi Ayidn, this has not been addressed for a while. Do you still have the issue? Otherwise, I will close for now due to the ages but I am willing to look at the problem anytime.

**Comment by aydinsaribudak** [comment]
Hi @lee212 ,
Yes I guess it is not an issue for now. We will reopen the ticket in future if needed.
Thanks,
Aydin
