### ISSUE TITLE
deadlock during `rp.umgr` creation

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#421]
Saw this once when running the reproducer for #410, and could not yet reproduce it, but it seemed to indicate that the UMGR's callback lock got acquire attempts from two threads (did not have the DebugHelper active :-( )

This is low priority for now, I'll add to the ticket once it's reproducible.

**Comment by mturilli** [comment]
@andre-merzky any follow up on this?

**Comment by andre-merzky** [comment]
No, but I would assume that this is a duplicate for #428.  Let me close this one.
