### ISSUE TITLE
Key tag not in schema

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#429]
I define a task in `radical.entk` as follows:

```
    task1 = Task()
    task1.name = '%s-T1' % stage1.name
    task1.pre_exec = ['module load anaconda3/2019.03',
                      'source activate keras-gpu']
    task1.executable = 'python3'   # Assign executable to the task
    # Assign arguments for the task executable
    task1.arguments = ['predict.py',
                       '--input', '$NODE_LFS_PATH/%s/%s-multipage.tif' %
                       (task0.name, image.split('/')[-1].split('.')[0]),
                       '--output_folder', '$NODE_LFS_PATH/%s' % task1.name,
                       '--weights_path', 'weights/unet_weights.hdf5']
    task1.link_input_data = ['$SHARED/unet_weights.hdf5 >' +
                             'weights/unet_weights.hdf5']
    task1.upload_input_data = [os.path.abspath('../classification/predict.py'),
                               os.path.abspath('../classification/' +
                                               'gen_patches.py'),
                               os.path.abspath('../classification/' +
                                               'train_unet.py'),
                               os.path.abspath('../classification/' +
                                               'unet_model.py')]
    task1.cpu_reqs = {'processes': 1, 'threads_per_process': 1,'process_type': None,
                      'thread_type': 'OpenMP'}
    task1.gpu_reqs = {'processes': 1, 'threads_per_process': 1,'process_type': None,
                      'thread_type': 'OpenMP'}
    task1.tag = task0.name
```

When the task is getting submitted I get the following error:
```
1582837692.001 : radical.entk.task_manager.0000 : 24100 : 140437612377856 : ERROR    : task_manager.0000 failed with key tag not in schema
Traceback (most recent call last):
  File "/home/iparask/iceberg/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 324, in _process_tasks
    umgr.submit_units(bulk_cuds)
  File "/home/iparask/iceberg/lib/python3.7/site-packages/radical/pilot/unit_manager.py", line 698, in submit_units
    unit = ComputeUnit(umgr=self, descr=ud)
  File "/home/iparask/iceberg/lib/python3.7/site-packages/radical/pilot/compute_unit.py", line 61, in __init__
    descr.verify()
  File "/home/iparask/iceberg/lib/python3.7/site-packages/radical/utils/description.py", line 234, in verify
    return super(Description, self).verify(self._schema)
  File "/home/iparask/iceberg/lib/python3.7/site-packages/radical/utils/description.py", line 187, in verify
    if k not in schema: raise TypeError('key %s not in schema' % k)
TypeError: key tag not in schema
```

Apparently in `radical.pilot` schema `tag`, has been renamed to `tags`.

@andre-merzky can you confirm that the change happened? I think this is critical and needs to be fixed immediately.

I can create a hot fix and open the required PR, but I do not know EnTK's release procedure to finalize it.

**Comment by andre-merzky** [comment]
Hmm, RP introduced `tags` in [this](https://github.com/radical-cybertools/radical.pilot/commit/de3dad937#diff-992e0a198aaebf4c2c8a8f45e4c41939R37) commit in August 2018, but that did not exist as `tag` before, AFAICT.  Well, that's what I saw from a quick check.  Either way though, we can add `tag` as an alias to `tags` until EnTK is sorted out?

**Comment by iparask** [comment]
I remember that it worked with `0.72`, so I made a few spot checks. EnTK had it as [tag](https://github.com/radical-cybertools/radical.entk/blob/v0.72.0/src/radical/entk/execman/rp/task_processor.py#L428), but RP registered only [tag](https://github.com/radical-cybertools/radical.pilot/blob/v0.72.0/src/radical/pilot/compute_unit_description.py#L360) as an attribute and could set both [tag](https://github.com/radical-cybertools/radical.pilot/blob/v0.72.0/src/radical/pilot/compute_unit_description.py#L395) and [tags](https://github.com/radical-cybertools/radical.pilot/blob/v0.72.0/src/radical/pilot/compute_unit_description.py#L398).

I will sort EnTK now, run a test based on a use case and let you know.

**Comment by iparask** [comment]
Furthermore, RP's scheduler [used the `tag` key](https://github.com/radical-cybertools/radical.pilot/blob/v0.72.0/src/radical/pilot/agent/scheduler/continuous.py#L195) to schedule units, which apparently is still true in [devel](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/scheduler/continuous.py#L364)

**Comment by mturilli** [comment]
@iparask any update on this?

**Comment by iparask** [comment]
Yes, this is work in progress. Currently, I am trying to understand how the colocation scheduler works exactly, because I am not sure if it schedules units. Also, there is this issue: radical-cybertools/radical.pilot/issues/2258

**Comment by andre-merzky** [comment]
@iparask : can you please give the RP branch `hotfix/tags` a try?  I should address this problem for the time being.

**Comment by iparask** [comment]
The `hotfix/tags` branch works! Thank you! Also, the tags PR is open again!
