### ISSUE TITLE
purge `radical.ensemblemd` from pypi

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#430]

**Comment by lee212** [comment]
@andre-merzky , can you add me to the maintainer? BTW how do you want to proceed purging this? I was thinking of simple deletion without linking to radical.entk.

**Comment by andre-merzky** [comment]
Yes, it can just be deleted.  Let me see if I have access...

**Comment by andre-merzky** [comment]
Done :-)
