### ISSUE TITLE
Outdated documentation and software

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.entk#431]
The following should be taken offline alongside radical.ensamblemd https://radical-cybertools.github.io/entk/quick_start.html

**Comment by lee212** [comment]
https://github.com/radical-cybertools/radical-cybertools.github.io/pull/40 will fix this

**Comment by lee212** [comment]
This has been resolved as the page is forwarded to readthedocs, https://radicalentk.readthedocs.io/en/latest/user_guide/get_started.html
