### ISSUE TITLE
entk no attribute _uid error

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.entk#433]
Hi, I got the following error when I tried to use xsede.bridges as my resource:
AttributeError: 'NoneType' object has no attribute '_uid'
The script works fine when I use stampede2 as the resource.
The same issue in #355 & #403

radical-stack:
```
  python               : 3.7.6
  pythonpath           :
  virtualenv           : /home/aydins/ve-entk

  radical.analytics    : 0.90.7-v0.72.0-35-g4f5242d@devel
  radical.entk         : 1.0.1-v1.0.1-2-g92797c9@devel
  radical.pilot        : 1.0.0
  radical.saga         : 1.0.1
  radical.utils        : 1.0.0
``` 

[session.zip](https://github.com/radical-cybertools/radical.entk/files/4293830/session.zip)
[verbose.log](https://github.com/radical-cybertools/radical.entk/files/4293832/verbose.log)

To collect the logfiles, I ran radical-pilot-fetch-logfiles <session>. However it gives the following error. Then I get the log files using sftp.
Traceback (most recent call last):
  File "/home/aydins/ve-entk/bin/radical-pilot-fetch-logfiles", line 88, in <module>
    rpu.fetch_logfiles(sid=sid, dburl=dburl, src=src, tgt=tgt, access=access, skip_existing=skip)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/radical/pilot/utils/session.py", line 259, in fetch_logfiles
    json_docs = get_session_docs(db, sid)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/radical/pilot/utils/db_utils.py", line 89, in get_session_docs
    raise ValueError ('no session %s in db' % sid)
ValueError: no session re.session.js-17-94.jetstream-cloud.org.aydins.018326.0011/ in db

**Comment by andre-merzky** [comment]
Hi Ayden - if another issue with the same error is already open, then please add a comment on the existing one and ask to increase the priority.  I am closing this one in favor of #403 - the information from this ticket here are cross referenced in #403 now.

**Comment by aydinsaribudak** [comment]
Hi Andre,
I understand. Thank you for the clarification and increasing the priority. 
Please let me know if you need any other data to resolve the issue. 
Thank you
Aydin
