### ISSUE TITLE
delay between stages

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#439]
Two tasks in two stages show 10+ sec delays, although each task runs < 1sec:
```
[hrlee@login3.summit unit.000001]$ more STDOUT
Sun Mar 29 23:24:44 EDT 2020
Hello World
Sun Mar 29 23:24:45 EDT 2020
[hrlee@login3.summit unit.000002]$ more STDOUT
Sun Mar 29 23:24:57 EDT 2020
Hello World
Sun Mar 29 23:24:58 EDT 2020
```

**Comment by mturilli** [comment]
@lee212 based on what we learned on Summit, is this due to RBMQ latency or is it an actual bug? I see that is assigned for January milestone, does that mean you know already how to fix this?

**Comment by mturilli** [comment]
@lee212 ping

**Comment by lee212** [comment]
#483 was the first attempt to resolve this delay, (reducing the avg. delay to 5 from 10 secs) and there is more. It seems that `db_poll_sleeptime: 2.0` from radical.pilot is related to this but I have to collect some data to clarify.

**Comment by iparask** [comment]
Closing as we cannot currently optimize any further at the moment.
