### ISSUE TITLE
Sections in documentation need to become up-to-date

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.entk#442]
Current documentation was not able to clarify the questions listed at: https://github.com/radical-collaboration/facts/issues/23

Further, examples at https://radicalentk.readthedocs.io/en/latest/user_guide/adding_shared_data.html do not clarify the use of `copy_output_data` (> notation) and the different between `copy_output_data` and `download_output_data`.

**Comment by lee212** [comment]
Changed the title to reflect the following items as well:
- best practice on multiple tasks: https://github.com/radical-collaboration/hpc-workflows/issues/118
- description on task.`post_exec` method according to facts#23
- shared_data API behavior according to hpc-workflows#119
