### ISSUE TITLE
No possibility to set env variables for rp.cu.description['environment']

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.entk#443]
In RP launch methods read about env variables from `cu['description'].get('environment', {})`. Is there a possibility to set such information (env variables) for Task at EnTK?

There is argument `pre_exec` for Task, but information there is not considered at the level of Launch Methods (and particularly at `construct_command` methods)

**Comment by andre-merzky** [comment]
No, the EnTK Task API unfortunately does not expose env settings.

**Comment by mtitov** [comment]
such feature would be needed, as for current project - use LM `ibrun` that considers `TACC_TASKS_PER_NODE`

**Comment by andre-merzky** [comment]
Can't we set that variable automatically from the launch method?  What information does the user have to determine the value which we are missing in the LM?

**Comment by mtitov** [comment]
@andre-merzky this variable manages the number of tasks to be executed by `ibrun`, if not set then corresponding number from slurm setting will be used (so we can define resource allocation for the whole app, but at the certain stage we can adjust the actual number of tasks)

from TACC support:

> If this parameter is not set, the ibrun script will use the default slurm setting for the number of tasks per node to build the hostlist.  So, if you set this to 40, ibrun will create a hostlist in which the first 40 lines are the same host.  This is important when using the "-n" "-o" options, because ibrun builds a new hostlist by carving a subset of lines out of the master host list.

as I understand, this parameter is to increase the efficiency of the usage of provided resources (doesn't sound it's a mandatory parameter). Could be considered as an extra layer of resource utilization, and the value of this parameter might be different from stage to stage (in terms of EnTK)

**Comment by andre-merzky** [comment]
thanks.  So given a task with `n` processes and `m` threads per process (== cores per process), and nodes with `l` cores per node, what value should the user set for that variable?

**Comment by mtitov** [comment]
threads wouldn't be counted here (that's what also was provided by TACC support), and then

1) if `n <= l` then it would be `n`
2) if `n > l` then `math.ceil(float(n)/n_nodes)` (where `n_nodes` is based on number of requested cores and `l`) - but this one should be confirmed with internal calculation of `core_map`

**Comment by andre-merzky** [comment]
Right.  This though sounds like we are not missing any information in the LM to set the value ourself, and don't need to ask the user or application to do so, right?  I mean, ideally the user should not even know that (a) it's a TACC machine, (b) that ibrun is used for task launching, and (c) over how many nodes a task has been scheduled (the last the user cannot know actually).

**Comment by mtitov** [comment]
In general - yes, agree, but with (a) and (b) it is 50/50 - user is responsible to pick the corresponding resource configuration, thus should be aware (and such information as env variable could be added to `"notes"` at resource_config). Also having such possibility wouldn't limit the user in taking advantage of env variables

**Comment by mtitov** [comment]
Ticket is closed, but the info related to IBRun LM is kept ([PR 2138](https://github.com/radical-cybertools/radical.pilot/pull/2138))
