### ISSUE TITLE
dryrun

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#444]
```
$ python entk.py --dryrun
pipeline
stage1:
task1: echo helloworld
stage2:
task1: echo goodbye

**Comment by mturilli** [comment]
@lee212 ping

**Comment by lee212** [comment]
For the testing purpose of the executables, dryrun would be useful to catch failures like syntax error and incorrect parameters, and the `local.localhost` seems like serving the purpose without allocating real resources. I would revisit this again later but for now, `local.localhost` would be sufficient, what do you think?

**Comment by andre-merzky** [comment]
Isn't the purpose of the Mock excutor in `src/radical/entk/execman/mock` to provide that capability?
