### ISSUE TITLE
Running multiple workflows in one session fails

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.entk#447]
See https://github.com/radical-collaboration/facts/issues/24

**Comment by andre-merzky** [comment]
I think this is not fundamentally broken - the attached script runs two workflows (2 pipelines each) in separate `appmgr.run()` calls, and this seems to work as expected (I see a total of 4 pipelines executed).  Not that the appmgr constructor needs an `autoterminate=False` then, and termination must be triggered by the application.

PS.: attaching python files is not supported (strange), so [here it is](https://gist.github.com/andre-merzky/e74f807fdf8eb43f3a9feb158745d934).

**Comment by mturilli** [comment]
This was solved for the user. We can close it.
