### ISSUE TITLE
RADICAL-EnTK conda recipe fails

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#455]
The new conda installation fails with the following error:

```
error: can't copy 'examples/user_guide/re.session.login1.hrlee.018411.0012': doesn't exist or not a regular file
```

It seems like there is a session under the examples folder in the pip release. I am not sure if that is correct or not. I will see how to resolve it, but it may require a new release.

Thank you

**Comment by lee212** [comment]
Yes, I accidentally included the session in the dist for the release. Thanks for reporting this.
I yanked the release 1.4.1 and uploaded new one without the session. `1.4.1.post1` is now the latest and it seems fine.

**Comment by andre-merzky** [comment]
Hey @Hyungro - thanks for fixng this quicly!  You may want to use the next minor version number the next time you need to update an release (so `1.4.2` or whatever is up by then).  For the end user it is not obvious what `post1` is supposed to mean, and version numbers which use different schema are not easy to compare (automatically).

**Comment by iparask** [comment]
This is fixed and I'm closing it
