### ISSUE TITLE
Can a resource description be "overridden"?

### ISSUE THREAD

**Issue by wilkinson** [radical-cybertools/radical.entk#458]
Given the following EnTK program:
```python
import os
from radical.entk import AppManager

appman = AppManager(
    hostname=os.environ["RMQ_HOSTNAME"],
    port=int(os.environ["RMQ_PORT"]),
    username=os.environ["RMQ_USERNAME"],
    password=os.environ["RMQ_PASSWORD"])

appman.resource_desc = {
    'resource': 'ornl.summit',
    'walltime': 10,
    'cpus': 1,
    'project': 'stf011'
}

# ...
```

Is it possible to override parts of the "ornl.summit" resource description, specifically the queue that will be used? It would be nice to be able to specify the `debug` queue explicitly in a way that overrides the [default](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_ornl.json#L102).

**Comment by mturilli** [comment]
I think you can use the key `queue` in the `resource_desc` dictionary. I find it at `src/radical/entk/execman/base/resource_manager.py` but I see we miss the `resource_manager.py` API at https://radicalentk.readthedocs.io/en/latest/api.html . Should we add it?

**Comment by mturilli** [comment]
@iparask could you have a go at this? Happy to help.
