### ISSUE TITLE
Not running all stages on eop.py

### ISSUE THREAD

**Issue by akashban** [radical-cybertools/radical.entk#465]
Hi entk developers,

I am trying to run the eop.py example in the examples/simple folder. The script is supposed to generate 3 stages. However, only one stage is generated in the sandbox in my case. I have attached all the associated log files and the sandbox to this ticket. Please have a look as per your convenience and advise me on what I can do next.

[log_eop.zip](https://github.com/radical-cybertools/radical.entk/files/4839868/log_eop.zip)
[sandbox.zip](https://github.com/radical-cybertools/radical.entk/files/4839869/sandbox.zip)

could do.

Thank you.

Kind Regards,
Akash

**Comment by lee212** [comment]
Hi Akash, 

Thanks for reporting this and your patience. I just noticed that the example, `eop.py` is outdated, I've created PR #469 to fix that. In the meantime, you can rerun your example by replacing `.uid` to `.name` at these two lines:
https://github.com/radical-cybertools/radical.entk/blob/a1961e7fd41887a183cc06adbe36a38f19b639c8/examples/simple/eop.py#L48

https://github.com/radical-cybertools/radical.entk/blob/a1961e7fd41887a183cc06adbe36a38f19b639c8/examples/simple/eop.py#L64

Then I think your example of 3 stages should be fine to complete. Let us know if you fail again with this and/or other problems.

**Comment by akashban** [comment]
Thank you so much @lee212 . It works with .name. I will close the ticket.

Thank you for your help.

Kind regards,
Akash
