### ISSUE TITLE
EnTK issue

### ISSUE THREAD

**Issue by EsraaAbdelmotteleb** [radical-cybertools/radical.entk#467]
I get this error when running any of my entk applications on bridges or comet. Most of these applications executed in the past with no issues. 

radical-stack:
  python               : 3.8.3
  pythonpath           : 
  virtualenv           : ve-rct

  radical.entk         : 1.4.0
  radical.pilot        : 1.4.0
  radical.saga         : 1.4.0
  radical.utils        : 1.4.0

[verbose.log](https://github.com/radical-cybertools/radical.entk/files/4871547/verbose.log)

**Comment by EsraaAbdelmotteleb** [comment]
Any update on this? It is blocking my experiments. @lee212 can you help with this?

**Comment by lee212** [comment]
@EsraaAbdelmotteleb ; I looked your log file it was failed due to the connection issue, I specifically say this:
```
 in _submit_resource_request
    self._pilot.wait([rp.PMGR_ACTIVE, rp.DONE, rp.FAILED, rp.CANCELED])
```
We probably have to generate a more readable error message than this but can you confirm if you have access to Comet on your jetstream? This will confirm, for example:
```
$ ssh comet.sdsc.edu hostname
comet-ln3.sdsc.edu
```

I also need to see your `res_dict` in your script, maybe if you can share your script it might be easier.

Sorry for the late response and thanks for the patience.

**Comment by EsraaAbdelmotteleb** [comment]
Hi @lee212. I've attached my script below. Please note that I get this error when using comet, bridges or stampede2.
comet-ln2.sdsc.edu

I have access to comet on jetstream. 
`$ ssh comet.sdsc.edu hostname`  returns `comet-ln2.sdsc.edu`
[code.zip](https://github.com/radical-cybertools/radical.entk/files/4893538/code.zip)

**Comment by lee212** [comment]
Thanks. In your resource description, I find `gsissh` is  used, not `ssh`. These two are different authentications.  What do you see when you run `gsissh -p 2222 comet.sdsc.edu hostname` do you see the same results?

**Comment by EsraaAbdelmotteleb** [comment]
`gsissh -p 2222 comet.sdsc.edu hostname` returns a connection refused error. I tried 
`gsissh -p 2222 bridges.psc.xsede.org hostname` and was able to connect. But I still get the same error when I use bridges in my resource description.

**Comment by lee212** [comment]
`myproxy-logon` fixes the issue. I am closing this now.
