### ISSUE TITLE
Keyboard Interrupt error

### ISSUE THREAD

**Issue by akashban** [radical-cybertools/radical.entk#473]
Hi ENTK developers,

I am getting the keyboard interrupt error whenever I try to run any of the entk examples. My entk stack was working until friday, and then suddenly started giving this error. I have installed a new version and made sure to have the latest build on the master branch. Please have a look at my error files. With this specific error, I am not sure where to start debugging. It would be great if I could
[error.zip](https://github.com/radical-cybertools/radical.entk/files/5025768/error.zip)
 get some assistance on that as this error pops up whenever I use a new entk installation.

Thank you for your help in advance.

Kind Regards,
Akash

**Comment by SrinivasMushnoori** [comment]
Please leave the output of `radical-stack` here?

**Comment by akashban** [comment]
python               : 3.7.5
  pythonpath           : 
  virtualenv           : /home/votca-machine-ubuntu-19/ve-entk

  radical.entk         : 1.4.0-v1.4.1@master
  radical.pilot        : 1.4.1
  radical.saga         : 1.4.0
  radical.utils        : 1.4.0

**Comment by andre-merzky** [comment]
Thank you @akashban, and sorry for the later reply.  Can you please create a tarball of the pilot sandbox, too?  You should find it in `$HOME/radical.pilot.sandbox/re.session.votcamachineubuntu19-OptiPlex-9010.votca-machine-ubuntu-19.018479.0001/ `.  It looks like the pilot did not come up correctly.

**Comment by akashban** [comment]
[re.session.votcamachineubuntu19-OptiPlex-9010.votca-machine-ubuntu-19.018479.0001.zip](https://github.com/radical-cybertools/radical.entk/files/5058411/re.session.votcamachineubuntu19-OptiPlex-9010.votca-machine-ubuntu-19.018479.0001.zip)

Thanks for the instructions, Andre. I have attached my sandbox here.

**Comment by andre-merzky** [comment]
Hi @akashban , thanks for providing the files.  If you have a look into `bootstrap_0.out`, you will see that the bootstrapper complains about `curl` not being available, and also `virtualenv` not being found.  Either error should be recoverable (if virtualenv is not installed, we use curl to fetch and install it locally; if curl is not available, we use the system's virtualenv command) - but we can't recover from both.  

It looks like you are using ubuntu: a 
```sh
sudo apt install curl
sudo apt install python3-virtualenv
```
should make the commands available on your system.  Let me know if yhou don't have the rights to execute those, and we'll figure out how to fix that problem without admin rights.

**Comment by akashban** [comment]
Thank you so much @andre-merzky . It worked. I will make a note of this solution and close the ticket.

Thanks
Akash
