### ISSUE TITLE
Version update message for older stacks

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#476]
To encourage using the latest version of RCT, it is useful if a version check is enabled with a message to update.

**Comment by iparask** [comment]
@lee212, can you provide an example of how you think this might work? I think we may have to go to all tags and add a warning.

**Comment by mturilli** [comment]
@lee212 ping

**Comment by lee212** [comment]
pip warning would be a good example like:
```
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
``` 

from https://github.com/pypa/pip/blob/master/src/pip/_internal/self_outdated_check.py

**Comment by iparask** [comment]
Alright! Does it make sense to include from Jan 2021 release onwards or update all previous releases as well?

**Comment by andre-merzky** [comment]
We actually had this implemented with a `-v` flag on `radical-stack` which checked pypi for the latest available version.  Alas, the pypi interface we used for this became deprecated, and thus a recent PR (radical-cybertools/radical.utils/pull/276) removes that support again until we find a different way to query that information (in a timely and simple fashion).
