### ISSUE TITLE
Q. Assiging multiple gpus

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#479]
I have a mpi process asking two ranks and two gpus per rank, which the task description looks like:

```
    t.gpu_reqs = { 'processes': 2,
            'process_type': None,
            'threads_per_process':2,
            'thread_type': 'CUDA'
            }
    t.cpu_reqs = { 'processes': 2,
            'process_type': 'MPI',
            'threads_per_process':4,
            'thread_type':'OpenMP'}
```

and the `.sl` file seems okay but the erf file `.rs` doesn't, it only has one gpu core assigned.
the sl file looks:
```
{'cores_per_node': 167,
 'gpus_per_node': 6,
 'lfs_per_node': {'path': None, 'size': 0},
 'lm_info': {'cvd_id_mode': 'logical'},
 'mem_per_node': 0,
 'nodes': [{'core_map': [[0, 1, 2, 3]],
            'gpu_map': [[0], [1]],
            'lfs': {'path': None, 'size': 0},
            'mem': 0,
            'name': 'h29n09',
            'uid': '1'},
           {'core_map': [[4, 5, 6, 7]],
            'gpu_map': [[2], [3]],
            'lfs': {'path': None, 'size': 0},
            'mem': 0,
            'name': 'h29n09',
            'uid': '1'}]}
```

and `.rs` file:
```
[hrlee@login5.summit unit.000000]$ more unit.000000.rs
cpu_index_using: physical
rank: 0: { host: 1; cpu: {0,1,2,3}; gpu: {0}}
rank: 1: { host: 1; cpu: {4,5,6,7}; gpu: {2}}
```

what would be a correct task description to allocate two gpus per rank?

**Comment by andre-merzky** [comment]
This is the correct task description, and the slots file confirms that the scheduler interprets it correctly.  The error seems to be caused by the jsrun launch method in RP.  I opened radical-cybertools/radical.pilot/issues/2219 for this.  What is the priority on the issue?  Thanks, Andre.

**Comment by lee212** [comment]
This prevents running pytorch distributed version on Summit for workflow-2, I had to manually generate jsrun command in pre_exec instead.

**Comment by andre-merzky** [comment]
Please give the RP branch `hotfix/issue_re_479` a try - it should resolve this issue.

**Comment by lee212** [comment]
Yes, it does. and this is updated erf file:
```
rank: 0: { host: 1; cpu: {0,1,2,3}; gpu: {0,1}}
rank: 1: { host: 1; cpu: {4,5,6,7}; gpu: {2,3}}
```
