### ISSUE TITLE
Align thread/processes definitions between EnTK and RP

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.entk#481]
The current differences create unnecessary confusion.

**Comment by iparask** [comment]
Hello @mturilli, I just checked the attributes naming and it seems to be the same. From RP, we have:

```
CPU_PROCESSES          = 'cpu_processes'
CPU_PROCESS_TYPE       = 'cpu_process_type'
CPU_THREADS            = 'cpu_threads'
CPU_THREAD_TYPE        = 'cpu_thread_type'

GPU_PROCESSES          = 'gpu_processes'
GPU_PROCESS_TYPE       = 'gpu_process_type'
GPU_THREADS            = 'gpu_threads'
GPU_THREAD_TYPE        = 'gpu_thread_type'
```

EnTK introduces dictionaries for CPU and GPU requirements. I can either change the dictionary keys to much RPs or make a API change on EnTK to much that of RP. I think the first option is better and I will introduce a deprecation message for users.

**Comment by iparask** [comment]
Closing as PR #492 is merged
