### ISSUE TITLE
feature request: job_name attribute in resource description

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#484]
See radical-collaboration/hpc-workflows/issues/122: EnTK should forward `job_name` settings to RP.

**Comment by iparask** [comment]
This is blocked by #496. The tests of the components need to be changed are updated and I would like test to follow any development.

**Comment by iparask** [comment]
So, I was just wondering. We can setup the session name and that sets up the sandbox folder name. Wouldn't it make more sense to use that as the job name? This is the same for RP.

**Comment by andre-merzky** [comment]
That would invalidate multiple pilots in one session, and would also require pilot names to be unique to avoid sandbox colissions...

**Comment by iparask** [comment]
Currently blocked by radical-cybertools/radical.pilot#2248
