### ISSUE TITLE
Stampede2 Resource Tag

### ISSUE THREAD

**Issue by akashban** [radical-cybertools/radical.entk#486]
HI ENTK Developers, 

I am trying to launch my ENTK script on Stampede2 with the resource tag "xsede.stampede2_ibrun". I am not able to control the number of nodes with this resource tag. By default, it runs the code on 1 node. I am guessing that the ibrun command is not executed and hence the code runs just on 1 node. 

I have also tried using "xsede.stampede2_ssh", but that didn't resolve the issue either. Please help me include the ibrun command in my ENTK scripts so that I can control the number of nodes. 

Thank you. 

Kind Regards,
Akash

**Comment by akashban** [comment]
To add to the previous message, I would like to also provide the associated log files in the sandboxes. Unfortunately, the sandbox on stampede2 is too big to upload on this ticket. Hence, I am only providing the sandbox that is generated on my laptop.
[local_sandboz.zip](https://github.com/radical-cybertools/radical.entk/files/5431293/local_sandboz.zip)

**Comment by akashban** [comment]
[re.session.abanerjee-OptiPlex-990.abanerjee.018563.0001.zip](https://github.com/radical-cybertools/radical.entk/files/5466199/re.session.abanerjee-OptiPlex-990.abanerjee.018563.0001.zip)
[verbose1.log](https://github.com/radical-cybertools/radical.entk/files/5466200/verbose1.log)

Hi @lee212 , @andre-merzky 

I am not able to use the "xsede.stampede2_ibrun" resource tag properly. I am not able to control the number of cpus with the resource tag. By default, I am being allowed to use only 1 core on a stampede2 node ( irrespective of whatever value I enter in my config files). Please help me resolve this issue. I have uploaded my latest log files. 

Thank you
Kind Regards,
Akash

**Comment by andre-merzky** [comment]
@lee212 : can you please take care of this issue?

@akashban : I think there is some misunderstanding on the role of the config file.  You should not need to edit that at all in order to increase the number of cores that the pilot uses or a task uses.  For that, you should set the resource requirements in the resource description and the task description, respectively.  What code are you trying to run?

**Comment by akashban** [comment]
@andre-merzky : Sorry for the confusion, I meant config files of our internal group project ( PACE, developed by Srinivas). I am setting the resource requirements in the config files specially made for PACE. 

{
	"resource"      : "xsede.stampede2_ibrun",
	"walltime"      : 30,
	"cpus"          : 64,
        "gpus_per_node" : 0,
        "access_schema" : "gsissh",
        "project": "XXXXXXXXXX", # have intentionally cut it out
        "queue": "development"
}

**Comment by andre-merzky** [comment]
Then the answer really depends on what PACE does with that dictionary - maybe that is really a question to @SrinivasMushnoori ?  Or are you able to point us to the code which shows how PACE translates that dictionary into a EnTK resource description?

**Comment by akashban** [comment]
Yes, absolutely. I am attaching 3 files 
1. PACE : this is the main ENTK script (you will find res_dict on line 595)
2. simconfig_DPPC_stampede2.json : has information about the simulation ( executable, pre_exec, etc.)
3. resconfig_stampede.json : has information to set the resource requirements on stampede2. 
[PACE-ENTK script.zip](https://github.com/radical-cybertools/radical.entk/files/5467796/PACE-ENTK.script.zip)

The actual github repo for PACE is private within the group, and I am not the admin. Maybe Srinivas will look into this. Please let me know if I can provide any other files.

**Comment by andre-merzky** [comment]
If I am reading your configs correctly, the `cpus` key in the resource config is evaluated as `cores`, and your pilot is getting a single node as Stampede-2 nodes feature 64 cores per node.  If you want more cores and nodes, you may want to increase that number to `n * 64` for `n` nodes.

Any single task you are running is using a single core though: the PACE script reads the `pipeline_cores` value from the simconfig file, but it does not use that value, and the task description will default to using one core.  @SrinivasMushnoori may want to comment if that is the expected behavior (which I doubt).

**Comment by akashban** [comment]
1. Yes, I want to use the entire single node on stampede2 for my MD simulations. Thank you for the explanation for multiple nodes. 
2. Yes, thats not expected behavior, we want simulations to use multiple cores. Could you point me to an ENTK example script where I can learn how to effectively assign the number of cores to different tasks?

Thank you so much for your help. I sincerely appreciate it.

**Comment by andre-merzky** [comment]
Maybe [this section on `cpu_reqs` from the documentation](https://radicalentk.readthedocs.io/en/latest/dev_docs/dev_api/task.html#radical.entk.Task.cpu_reqs) is helpful: the `processes` value translates to the number of MPI ranks created, the `threads_per_process` value translates to the number of cores each rank can use.

**Comment by akashban** [comment]
That worked! I am able to change the number of cores as per my requirements. Thank you so much @andre-merzky for all your help. 
Have a great weekend!
Kind Regards,
Akash

**Comment by andre-merzky** [comment]
Great :-)
