### ISSUE TITLE
file discovery

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.entk#488]
Is it possible to enable file discovery? If a task doesn't find a file in the sandbox task directory, entk would go into the $SHARED directory (or an user-specified directory) to see if entk can find the file there. Currently each file can be linked/copied from $SHARED to the sandbox task directory, but allowing file discovery could allow to streamline this step. Note: this is not mainly about the executable but mostly about the other files which are usually linked/copied. An slightly related example is $PATH variables, where binaries are discovered not only local but also in user-defined directories, the use case here extends beside binaries to any file the task might need.

**Comment by iparask** [comment]
Hello @euhruska,

If I understand correctly, you are asking for EnTK to fall back to different directories based on whether a file exists in the sandbox or not. EnTK does not verify if a file used as input from an executable exists or not.  It assumes that the user has made sure to either provide the correct path to an input file or stage it correctly.

Having said that, I understand that there might be a need for tasks from different stages to access the same data, and creating links can create bugs in the workflow definition. May I suggest to check the task `sandbox` capabilities ([here](https://radicalentk.readthedocs.io/en/stable/dev_docs/dev_api/task.html#radical.entk.Task.sandbox))? Using the same sandbox for several dependent tasks makes sure that they all land in the same folder and have access to the same data. That removes any need to always stage (link) data between different stages of your workflow.

Does this help?

Thank you

**Comment by euhruska** [comment]
Can the sandbox setter be given an arbitrary path and it will execute there?

**Comment by iparask** [comment]
The sandbox can point to any path on your target resource. The tasks which have the same sandbox path will all execute in that folder.

**Comment by euhruska** [comment]
That should resolve this issue.
