### ISSUE TITLE
hidden rabbitmq for localhost

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.entk#489]
When entk is run on localhost, then rabbitmq could be hidden from the end-user, at least as an option. Entk would launch it's own rabbitmq-server, with no parameters or options for the end-user. Is it possible to implement this?

**Comment by mturilli** [comment]
With RabbitMQ this is complicated and likely not viable. RMQ needs to bind to a specific port that, in turn, needs to be open and available. Running multiple RMQ on the same host generates problems for the same reason. It can run well in a container but then we make assumptions about the availability (and permission to use) of a specific OS-level virtualization technology. Finally, RMQ has fairly heavy dependencies that are difficult to automatically install in user space.

Said that, the requirement is well-received and we are discussing internally with what tool we should replace RMQ so to be able to launch it at runtime, transparent to the user and likely independent from the OS on which we are executing EnTK. Unfortunately, this will not be available anytime soon though.

**Comment by mturilli** [comment]
Can we close this ticket?
