### ISSUE TITLE
Not able to move beyond the first simulation task in workflow

### ISSUE THREAD

**Issue by akashban** [radical-cybertools/radical.entk#501]
Hi ENTK developers, 

I have made a workflow which has the following layout : Simulation (STAGE 1) -> Analysis (STAGE 2) -> Extended simulation. (STAGE 3) 

This works when the simulation runs for short durations ( 10 simulation steps). However, when I increase the number of steps to the 50,000, the following happens: 

1. The simulation terminates successfully
2. But the following analysis is not launched

I have ensured that I ask for sufficient wall time on the remote resource (stampede2). I have attached the log files. 

pace : the main entk script
*.json files : config files for that have simulation specifications and the entk resource_dictionary. 

[debug.log](https://github.com/radical-cybertools/radical.entk/files/5518973/debug.log)
[logfiles.zip](https://github.com/radical-cybertools/radical.entk/files/5518974/logfiles.zip)
[Files.zip](https://github.com/radical-cybertools/radical.entk/files/5518986/Files.zip)

Thank you. 
Akash

**Comment by SrinivasMushnoori** [comment]
Ping. @lee212 @andre-merzky 
Essentially, task completion does not seem to be reported to EnTK. This appears to be happening erratically, from what I can gather from my discussion with @akashban

**Comment by andre-merzky** [comment]
@lee212 : Hyungro, could you please have a look?

**Comment by akashban** [comment]
Hi @lee212 @andre-merzky @SrinivasMushnoori ,

Just wanted to follow up on the above ticket. I am having an issue with task completion in my ENTK workflow. My MD simulation terminates, but the consequent stage is not launched. This only happens when the MD simulations runs for a higher number of MD steps (takes longer time). I was wondering what I could do to debug this issue.  (I have made sure to give enough wall time on the remote resource to avoid forced termination.

Any advice on how to go about the process?

**Comment by lee212** [comment]
@akashban , can you check your stack by run this: `radical-stack`?

Also, I need to see debugging messages from your log files but it requires you to set env variables prior launching your job by:
```
export RADICAL_LOG_LVL=DEBUG
export RADICAL_LOG_TGT=radical.log
```
could you re-run after this enabled?

**Comment by akashban** [comment]
This is my radical-stack:  

python               : 3.7.2
  pythonpath           : 
  virtualenv           : /home/abanerjee/ve-entk

  radical.entk         : 1.5.5-v1.5.5@master
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.7
  radical.saga         : 1.5.7
  radical.utils        : 1.5.7

Currently, my remote resource (stampede2) is undergoing maintenance. I will re-run the code once its back online, and attach the required debug files by Friday. Thank you for your help.

**Comment by akashban** [comment]
[myfiles.zip](https://github.com/radical-cybertools/radical.entk/files/5576387/myfiles.zip)

Hi @lee212 ,

I re-ran my ENTK script with the above instructions and then used the radical-fetch command. 
Please have a look at the attachment.
My ENTK scripit is there in the ENTK folder under the name "PACE"

Thank you for your help
Akash

**Comment by akashban** [comment]
Hi @lee212 , @SrinivasMushnoori 
I wanted to follow up regarding task completion. I have updated my log files as per the above instructions in previous comment. Please let me know how I could resolve the issue. 
Thank you for your help.
Akash

**Comment by lee212** [comment]
@akashban , I am checking it now, sorry for the delay.

**Comment by lee212** [comment]
@akashban , you may want to try again with the older version by:
```
pip install radical.entk==1.5.1
```
I suspect the new release has a problem related to this and you might be able to avoid the issue by downgrading entk.

**Comment by akashban** [comment]
@lee212 , Thanks so much, I will try this and come back to you.

**Comment by akashban** [comment]
[logfiles.zip](https://github.com/radical-cybertools/radical.entk/files/5609282/logfiles.zip)
@lee212 
I downgraded entk to 1.5.1. At first, the resource tag "xsede.stampede2_ibrun" did not work with entk 1.5.1. So, I used "xsede.stampede2_ssh". That seems to work but I am not sure if that would run my jobs. Currently, I am getting a keyboard interrupt error. I have attached the log files. The file radical_host.log is the log file generated on my laptop, and radical_remote.log is the log file I got by using the radical fetch command.

**Comment by akashban** [comment]
Hi @lee212 , 
Just wanted to follow up with this ticket. I downgraded ENTK, and I am facing a new issue. I have attached the log files. 
Thanks
AKash

**Comment by akashban** [comment]
@lee212 , 
A gentle ping - Did you get a chance to have a look at my log files ? 
Thanks
Akash

**Comment by lee212** [comment]
@akashban , sorry for the delay, I was looking at your log files but didn't find a clue what actually happened. Maybe @iparask , can find something that I didn't catch.

**Comment by akashban** [comment]
Hi @iparask , @SrinivasMushnoori 
I am getting the keyboard interrupt error when I try to launch my entk scripts. Any suggestions on how I could fix the above issue? The log files and a description of the issue are attached in this ticket. 

Thank you.
Akash

**Comment by akashban** [comment]
Hi @andre-merzky @lee212 

Following up on the above thread.

**Comment by lee212** [comment]
@akashban , I will try to revisit this issue again, and get back to you by today.

**Comment by iparask** [comment]
Hello @akashban, I have a couple of questions:

1. For how long are your tasks running for?
2. Do you mind rerun it with out setting the `RADICAL_LOG_TGT` variable? It will make sure that all log messages go to their respective log files.

**Comment by akashban** [comment]
HI @iparask ,
1. With the latest ENTK stack, my test MD simulations run for around 5-7 minutes. I have made sure that the wall-time requested on stampede2 (remote resource) is much more than that. 
2. Do you want me to run with or without the RADICAL_LOG_TGT variable? Currently, I am generating log files in the following manner: 
export RADICAL_LOG_LVL=debug
export RADICAL_LOG_TGT=debug.log
RADICAL_VERBOSE=DEBUG RADICAL_ENTK_VERBOSE=DEBUG python example.py 2> verbose.log
radical-pilot-fetch-logfiles <session id>

I was under the impression that export RADICAL_LOG_TGT=debug.log puts all log messages in their respective log files. Please let me know where I am going wrong. This would help me in the future.

**Comment by iparask** [comment]
> 1. With the latest ENTK stack, my test MD simulations run for around 5-7 minutes. I have made sure that the wall-time requested on stampede2 (remote resource) is much more than that.

Thank you, it seems that the pilot is actually running. It makes sense to ask for more time.

>    export RADICAL_LOG_TGT=debug.log

This places all messages in a single file. It makes it difficult sometimes to find out what the issue is. 

>    RADICAL_VERBOSE=DEBUG RADICAL_ENTK_VERBOSE=DEBUG python example.py 2> verbose.log

I would also ask you not to redirect to `verbose.log` at all. Everything should go to log files, and you will only see the reporter messages, which are not needed.

**Comment by akashban** [comment]
@iparask ,
So I will do the following: 
1. Ask for a lot of time on the remote resource. Currently I am asking for 2 hours for a simulation that actually takes 5-7 minutes. So I am guessing I should ask for a day of wall-time for the 5-7 minutes simulation?
2. Run ENTK script in the following manner : 
python example.py
radical-pilot-fetch-logfiles

Please let me know if this is correct.

**Comment by iparask** [comment]
> @iparask ,
> So I will do the following:
> 
> 1. Ask for a lot of time on the remote resource. Currently I am asking for 2 hours for a simulation that actually takes 5-7 minutes. So I am guessing I should ask for a day of wall-time for the 5-7 minutes simulation?

2 hours should be more than enough.

> 2. Run ENTK script in the following manner :
>    python example.py
>    radical-pilot-fetch-logfiles

I would say do the following:
```
export RADICAL_LOG_LVL=DEBUG
export RADICAL_VERBOSE=DEBUG 
export RADICAL_ENTK_VERBOSE=DEBUG 
python example.py 
radical-pilot-fetch-logfiles
```

**Comment by akashban** [comment]
@iparask 
Currently, I am getting the error when I ask for 2 hours. So what I will do is: rerun the entk script with the above instructions you have provided. Will get back to you soon.

**Comment by akashban** [comment]
I am able to run my ENTK script successfully.
