### ISSUE TITLE
EnTK does not delete queues after completion

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#512]
EnTK does not consistently delete queues from the server after closing a session. That has resulted to the server having over 1K queues declared.
```
(base) iparask@js-17-185:~$ sudo rabbitmqctl list_queues name | wc -l
1019
```

I would like to suggest that EnTK deletes the queues it creates after the completion of a session. What do you think?

**Comment by andre-merzky** [comment]
Ouch...  Well, cleanup certainly makes sense.  We have to take care that queues only get deleted on actual completion, and not on any errors from which RE may want to recover: supporting that recover process is one of the main reasons why we have those queues in the first place...

**Comment by mturilli** [comment]
I agree with @andre-merzky, we need to delete the queues only when we are sure EnTK exited cleanly and completed the execution of all the tasks. We should keep the scenario in which EnTK executes a workflow, some tasks fail and it cleanly exits. The user then wants to re-execute only the failed tasks. Do we need for the original queue to be there? Probably not but this is an example of what we need to consider to understand when do we need for a queue to survive an EnTK execution.

**Comment by iparask** [comment]
> I agree with @andre-merzky, we need to delete the queues only when we are sure EnTK exited cleanly and completed the execution of all the tasks. 

EnTK deletes the queues when it exits cleanly, but not every time it does not exit cleanly.

> We should keep the scenario in which EnTK executes a workflow, some tasks fail and it cleanly exits. The user then wants to re-execute only the failed tasks. Do we need for the original queue to be there? Probably not but this is an example of what we need to consider to understand when do we need for a queue to survive an EnTK execution.

If EnTK exits, the user needs to define a new workflow with the failed tasks. We do not keep the state of finished workflows. In this case, new queues will be created and used.

Queues are not deleted when EnTK does not exit cleanly. I believe that exception chaining will trigger the terminate command on the AppManager layer and clean all the queues.

**Comment by mturilli** [comment]
I am not sure I understand correctly your answer. If you confirm that queues are not deleted only in presence of some type of failure, then I guess we could close the ticket?

**Comment by iparask** [comment]
I am not sure if it deletes everything, even with correct termination. I need to check. I also think that in case of failure, where terminate is called queues should be deleted. 

Do you think they should remain on the server?

**Comment by mturilli** [comment]
I agree, I think they should be deleted as much as possible.

**Comment by iparask** [comment]
I checked this in every angle I could and I cannot replicate the behavior from before. I'm closing this issue.
