### ISSUE TITLE
Error initializing session directory, err: -33

### ISSUE THREAD

**Issue by adw62** [radical-cybertools/radical.entk#515]
Hello,

I'm trying to run RTC jobs on Summit. I have had trouble with jobs timing out this was fixed here: https://github.com/radical-cybertools/radical.pilot/issues/2278 by switching to the `devel` branch of radical.pilot

I am now encountering a new issue where previously working scripts now fail, the std.err from all jobs seems to be Error initializing session directory, err: -33

I have provided by session and sandbox on Summit here: /gpfs/alpine/world-shared/chm155/alex/2radical_err

Any help finding my problem here would be appreciated.

**Comment by mturilli** [comment]
Could you provide the script you are using, with the actual task description?

**Comment by adw62** [comment]
I have place the script I'm using here: `/gpfs/alpine/world-shared/chm155/alex/hybrid_tests/test.py` 
Please ask if anything is not verbose enough.

**Comment by mturilli** [comment]
@adw62, at Line 162 I see TIES. Is that the name of the executable? If so, maybe use `./TIES`? I also see that at line 154 you change directory into `$WORKDIR`. Did you check whether that value is formed correctly at line 150?

**Comment by mturilli** [comment]
@adw62 an update on this. We still don't know where the error comes from but we have now more resources allocate to this problem. We will be updating this ticket with what we find. We should be ready to set an 1-hour meeting to all work on this.

**Comment by adw62** [comment]
Thank you for the update. Please let me know if I can provide any examples or files that my help with this.

**Comment by mturilli** [comment]
@adw62 we think we might have found the problem. The issue seems to be related to the change in pip interface we mentioned before. That broke the deployment of our stack on Summit. Could you update your stack so to use the latest development branch of RADICAL-Pilot and let us know whether it works?

**Comment by adw62** [comment]
@mturilli I think this has fixed the issue, I can now run the hybrid pipeline. Thank you.
