### ISSUE TITLE
sample script fails to run on Bridges

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.entk#516]
Hi,
I had an issue to run get_started.py on Bridges. The details are as follows:
```
    res_dict = {
            'resource': 'xsede.bridges',
            'walltime': 2,
            'schema': 'gsissh',
            'cpus'    : 1,
            'gpus'    : 4,
            'project' : 'unc100'
    } 
```
```
radical-stack:
  python               : 3.6.12
  pythonpath           :
  virtualenv           : midas-env
  radical.entk         : 1.5.7
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.7
  radical.saga         : 1.5.7
  radical.utils        : 1.5.8
```
error message on the console:

```
session lifetime: 31.9s                                                       ok
wait for 1 pilot(s)
              0                                                          timeout
All components terminated
Traceback (most recent call last):
  File "get_started.py", line 66, in <module>
    appman.run()
  File "/pylon5/mc3bggp/aydins/anaconda3/envs/midas-env/lib/python3.6/site-packages/radical/entk/appman/appmanager.py", line 418, in run
    self._rmgr._submit_resource_request()
  File "/pylon5/mc3bggp/aydins/anaconda3/envs/midas-env/lib/python3.6/site-packages/radical/entk/execman/rp/resource_manager.py", line 178, in _submit_resource_request
    self._pilot.wait([rp.PMGR_ACTIVE, rp.DONE, rp.FAILED, rp.CANCELED])
  File "/pylon5/mc3bggp/aydins/anaconda3/envs/midas-env/lib/python3.6/site-packages/radical/pilot/compute_pilot.py", line 536, in wait
    time.sleep(0.1)
KeyboardInterrupt
```

`squeue -u $USER` command did not list any jobs from the start until the termination.

Please let me know your suggestions?

[session.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5645270/session.tar.gz)
https://github.com/radical-group/aydin/blob/master/verbose.log
https://github.com/radical-group/aydin/blob/master/radical.pilot.utils.log

Note: session.tar.gz folder is from the previous run. It was exactly the same script and the same env.

**Comment by aydinsaribudak** [comment]
Session client folder is added.

[session_client.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5645437/session_client.tar.gz)

**Comment by andre-merzky** [comment]
You should be able to find error causes by grepping for `ERROR` in the log files of the client and pilot sandbox.  You will find that the pilot sandbox does not contain any logfiles, so the pilot did not come up.  The client side will show:
```sh
$ grep ERROR *
pmgr.0000.log:1607110128.688 : pmgr.0000            : 1768  : 140514150053632 : ERROR    : [Callback]: pilot 'pilot.0000' failed (exit)
pmgr.0000.log:1607110128.689 : pmgr.0000            : 1768  : 140514150053632 : ERROR    : listener died
pmgr_launching.0000.log:1607110128.685 : pmgr_launching.0000  : 2082  : 139999185053440 : ERROR    : bulk launch failed
radical.entk.appmanager.0000.log:1607110130.696 : radical.entk.appmanager.0000 : 1768  : 140553914070848 : ERROR    : Execution interrupted by user (you probably hit Ctrl+C), trying to cancel enqueuer thread gracefully...
radical.entk.resource_manager.0000.log:1607110130.696 : radical.entk.resource_manager.0000 : 1768  : 140553914070848 : ERROR    : Execution interrupted (probably by Ctrl+C) exit callback thread gracefully...
radical.saga.cpi.log:1607110128.682 : radical.saga.cpi     : 2082  : 139977077815040 : ERROR    : NoSuccess: Couldn't get job id from submitted job! sbatch output:
```

where `bulk launch failed` should get your attention.  Looking closer, you will see:
```sh
$ cat pmgr_launching.0000.log
1607110128.685 : pmgr_launching.0000  : 2082  : 139999185053440 : ERROR    : bulk launch failed
Traceback (most recent call last):
  File "/pylon5/mc3bggp/aydins/anaconda3/envs/midas-env/lib/python3.6/site-packages/radical/pilot/pmgr/launching/default.py", line 562, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/pylon5/mc3bggp/aydins/anaconda3/envs/midas-env/lib/python3.6/site-packages/radical/pilot/pmgr/launching/default.py", line 824, in _start_pilot_bulk
    jc.run()
  File "/pylon5/mc3bggp/aydins/anaconda3/envs/midas-env/lib/python3.6/site-packages/radical/saga/task.py", line 435, in run
    raise se.NoSuccess ("future exception: %s" % (future.exception))
radical.saga.exceptions.NoSuccess: future exception: Couldn't get job id from submitted job! sbatch output:
sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified
rm -f tmp_q5p6wwwz.slurm
 (/pylon5/mc3bggp/aydins/anaconda3/envs/midas-env/lib/python3.6/site-packages/radical/saga/adaptors/slurm/slurm_job.py +715 (_job_run)  :  " sbatch output:\n%s" % out)) (/pylon5/mc3bggp/aydins/anaconda3/envs/midas-env/lib/python3.6/site-packages/radical/saga/task.py +435 (run)  :  raise se.NoSuccess ("future exception: %s" % (future.exception)))
```

and you'll find `Invalid account or account/partition combination specified` as the sbatch error.

HtH, Andre.

**Comment by aydinsaribudak** [comment]
Thank you for the explanation @andre-merzky @mtitov @iparask 
I was trying to run the entk script from Bridges login node. Ioannis suggested me to run the script from the VM.
I started a new run from the VM with the same script, but I am still getting the same error as Andre pointed above:
`, Batch job submission failed: Invalid account or account/partition combination specified`

Thanks.

**Comment by mtitov** [comment]
@aydinsaribudak please check the project name you use

**Comment by aydinsaribudak** [comment]
@mtitov 
You were right.  The project name did not look correct. I updated the res desc as:
```
    res_dict = {
            'resource': 'xsede.bridges',
            'walltime': 5,
            'schema': 'gsissh',
            'cpus'    : 1,
            #'gpus'    : 4,
            'project' : 'mc3bggp'
    }
```
Now I have a new type of error:
On the client side:
radical.entk.appmanager.0000.log reports the following error:
```
1607123362.075 : radical.entk.appmanager.0000 : 23239 : 140595263690496 : ERROR    : Error in AppManager
Traceback (most recent call last):
  File "/home/aydins/env-dreamer/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 423, in run
    'ended in state %s' % res_alloc_state)
radical.entk.exceptions.EnTKError: Cannot proceed. Resource ended in state CANCELED
```

**Comment by AymenFJA** [comment]
@aydinsaribudak , can you specify the `queue` you want to run your code in on Bridges? Also, can you increase the amount of walltime? the minimum walltime is 30 minutes for a small queue on Bridges: check here https://portal.xsede.org/psc-bridges

**Comment by aydinsaribudak** [comment]
New res desc:
```
    res_dict = {
            'resource': 'xsede.bridges',
            'queue': 'RM',
            'walltime': 30,
            'schema': 'gsissh',
            'cpus'    : 1,
            #'gpus'    : 4,
            'project' : 'mc3bggp'
    }
```

radical.entk.appmanager.0000.log:
`1607125544.997 : radical.entk.appmanager.0000 : 30849 : 140029362980608 : ERROR    : Execution interrupted by user (you probably hit Ctrl+C), trying to cancel enqueuer thread gracefully...`

radical.entk.resource_manager.0000.log:
`1607125544.996 : radical.entk.resource_manager.0000 : 30849 : 140029362980608 : ERROR    : Execution interrupted (probably by Ctrl+C) exit callback thread gracefully...`

pmgr.0000.log:
```
1607125543.879 : pmgr.0000            : 30849 : 140027703043840 : ERROR    : [Callback]: pilot 'pilot.0000' failed (exit)
1607125543.880 : pmgr.0000            : 30849 : 140027703043840 : ERROR    : listener died
Traceback (most recent call last):
  File "/home/aydins/env-dreamer/lib/python3.7/site-packages/radical/utils/zmq/pubsub.py", line 314, in _listener
    cb(t, m)
  File "/home/aydins/env-dreamer/lib/python3.7/site-packages/radical/pilot/pilot_manager.py", line 320, in _state_sub_cb
    if not self._update_pilot(thing, publish=False):
  File "/home/aydins/env-dreamer/lib/python3.7/site-packages/radical/pilot/pilot_manager.py", line 361, in _update_pilot
    self._pilots[pid]._update(pilot_dict)
  File "/home/aydins/env-dreamer/lib/python3.7/site-packages/radical/pilot/compute_pilot.py", line 206, in _update
    else      : cb([self])
  File "/home/aydins/env-dreamer/lib/python3.7/site-packages/radical/pilot/compute_pilot.py", line 152, in _default_state_cb
    ru.cancel_main_thread('int')
  File "/home/aydins/env-dreamer/lib/python3.7/site-packages/radical/utils/threads.py", line 164, in cancel_main_thread
    sys.exit()
SystemExit
```

**Comment by andre-merzky** [comment]
This would be the point where you repeat the grep commands from above to see if you find the error :-)

**Comment by aydinsaribudak** [comment]
Following error logs are from bootstrap_0.out file under radical.pilot.sandbox session folder (Bridges):
`Couldn't install radical.pilot-1.5.7/! Lets see how far we get ...`
Couldn't install radical.utils-1.5.8/! Lets see how far we get ...
I will reinstall radical tools on a new environment, and report here what will I got.

**Comment by iparask** [comment]
Can you please use the `devel` branch? There is an important fix there.

**Comment by aydinsaribudak** [comment]
Thank you @iparask
You mean the devel branch for ENTK, right? Or for both radical.entk and radical.pilot ?

**Comment by iparask** [comment]
I mean RP. Sorry, I thought this was on the RP repo

**Comment by aydinsaribudak** [comment]
HI,
I update anaconda package and create a new conda environment, and free as much space as I can. Below are the details of the stack and error logs:

```
  python               : 3.9.0
  pythonpath           :
  virtualenv           : midas-env3

  radical.entk         : 1.5.7
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.7-v1.5.7-288-g61d8f9f@devel
  radical.saga         : 1.5.7
  radical.utils        : 1.5.8  
```

[session.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5670168/session.tar.gz)
[session_sandbox.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5670169/session_sandbox.tar.gz)

**Comment by mtitov** [comment]
@aydinsaribudak please try a devel-branch for saga, in your logs there is the following error: 
```
  File "/pylon5/mc3bggp/aydins/envs/midas-env3/lib/python3.9/site-packages/radical/saga/task.py", line 427, in run
    if  future.isAlive () :
AttributeError: 'Future' object has no attribute 'isAlive'
```
and it was fixed in devel

**Comment by aydinsaribudak** [comment]
Hi,
Unfortunately the execution is not completed and the session folder is not created under sandbox.
Here is the radical stack and the new session folder:
```
  python               : 3.9.0
  pythonpath           :
  virtualenv           : midas-env3

  radical.entk         : 1.5.7
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.7-v1.5.7-255-gf6fe45a@devel
  radical.saga         : 1.5.6-v1.5.6-7-geeabf6d@devel
  radical.utils        : 1.5.8
```

[session.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5676924/session.tar.gz)

**Comment by aydinsaribudak** [comment]
Hi,

get_started.py is worked on my env even though I didnt change anything on my env. 
@AymenFJA also tested and it worked on his env as well. However, it fails again if I request gpu in addition to cpu.
Here is the radical-stack and res description:
```
  python               : 3.9.0
  pythonpath           :
  virtualenv           : midas-env3

  radical.entk         : 1.5.7
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.7-v1.5.7-255-gf6fe45a@devel
  radical.saga         : 1.5.6-v1.5.6-7-geeabf6d@devel
  radical.utils        : 1.5.8
```
 ```
   res_dict = {
            'resource': 'xsede.bridges',
            'project' : 'mc3bggp',
            'queue': 'RM',
            'walltime': 30,
            'schema': 'gsissh',
            'cpus'    : 1
    }
```

**Comment by mtitov** [comment]
@aydinsaribudak what error it gives when you add gpus?

**Comment by aydinsaribudak** [comment]
@mtitov 

Here are the session folders:

[session.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5681755/session.tar.gz)
[session_sandbox.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5681756/session_sandbox.tar.gz)

Thanks

**Comment by aydinsaribudak** [comment]
Hi all,

As Aymen suggested, I have updated the queue as "GPU-small" and make the number of GPUs 2. It worked. It is just taking longer time than usual. Many thanks to @AymenFJA and @mtitov for looking into the issue in detail. 

As a future reference for everyone: To fix this issue, first we switch to devel branches. Then, update the queue information.
A possible reason for such an error `Requested node configuration is not available` may be because of not selecting the appropriate queue option.

And below are my radical-stack and res desc. I am closing the issue.
```
  python               : 3.9.0
  pythonpath           :
  virtualenv           : midas-env3

  radical.entk         : 1.5.7
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.7-v1.5.7-255-gf6fe45a@devel
  radical.saga         : 1.5.6-v1.5.6-7-geeabf6d@devel
  radical.utils        : 1.5.8
```

   ```
 res_dict = {
            'resource': 'xsede.bridges',
            'project' : 'mc3bggp',
            'queue': 'GPU-small',
            'walltime': 30,
            'cpus'    : 1,
            'gpus'    : 2,
            'schema': 'gsissh'
    }
```
