### ISSUE TITLE
gromacs MD simulation with cpu thread type OpenMP is failed 

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.entk#528]
Hi, I am running a plumed patched gromacs simulation on Bridges. 
My cpu/gpu request for each task is as follows:

```
t.cpu_reqs = {'processes': 1,
                           'process_type': None,
                              'threads_per_process': 4,
                              'thread_type': 'OpenMP'
                              }
            t.gpu_reqs = {'processes': 1,
                           'process_type': None,
                              'threads_per_process': 1,
                              'thread_type': 'CUDA'
                             }
```

and the radical-stack is:

```
  python               : 3.9.0
  pythonpath           :
  virtualenv           : midas-env3

  radical.entk         : 1.5.7
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.7-v1.5.7-255-gf6fe45a@devel
  radical.saga         : 1.5.6-v1.5.6-7-geeabf6d@devel
  radical.utils        : 1.5.8

```
I got this error: `task_manager.0000 failed`.  Could you please help? (Session files are attached)

P.S. If I update cpu 'thread_type' from 'OpenMP' to None, the error I received is: 
```
Fatal error:
When using GPUs, setting the number of OpenMP threads without specifying the
number of ranks can lead to conflicting demands. Please specify the number of
thread-MPI ranks as well (option -ntmpi)
```
I can provide log files for this one as well if it is needed.

Thank you,

[session_openmp.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5732866/session_openmp.tar.gz)
[session_openmp_sandbox.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5732867/session_openmp_sandbox.tar.gz)

[debug_openmp.txt](https://github.com/radical-cybertools/radical.entk/files/5732891/debug_openmp.txt)

**Comment by iparask** [comment]
Does this error originate from Gromacs? Does EnTK succeed in launching the task on Bridges?

**Comment by aydinsaribudak** [comment]
Hi @iparask 
My manual run (without ENTK) for gromacs simulation was successful on Bridges.
A sample ENTK script was completed successfully as well (under the same resource configuration).
In this case, the `task cpu/gpu requests` may be the root cause of the error. 
Because `task cpu/gpu requests` is one of the differences between gromacs simulation script and a sample Entk script.  The other differences are the pre_execs for the gromacs simulation.

**Comment by aydinsaribudak** [comment]
@iparask 
I gave another try several hours ago after updating the res config to set the number of cpus to 4. It has just finished. 
I see that one of the unit was completed successfully. (I have two concurrent units ). For the other unit I got this error: `Could not detect shell prompt (timeout)`
I will make another run and update the ticket as soon as it will be finished.
Thanks.

**Comment by aydinsaribudak** [comment]
@iparask 
The simulation has worked with an update in resource configuration. I basically increased the number of CPUs.
I am closing the issue. Thank you for your comments.
