### ISSUE TITLE
individual non-blocking tasks

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.entk#540]
Feature request for entk to enable adding individual non-blocking tasks.

Two proposed new function calls (to be discussed):
1) appman.run_non_blocking() 
Description: Starts an Application manager with an pipeline. Pipeline might contain only an empty stage. Keep running even if no tasks are left to be run until walltime runs out. This call has to be non-blocking.

2) appman.run_task_nonblocking(task)
Description: Add to above Application manager one task. This call has to be non-blocking. Will be executed as soon as possible. No data transfer from tasks back except task.state. 

Mock code:
https://github.com/radical-cybertools/radical.midas/blob/master/midas_mock_non_blocking.py

Schema:
https://docs.google.com/presentation/d/1uXyYE10QkU33r6ucnk_PSScGLrsWbLccd4WSiG61bs8

**Comment by andre-merzky** [comment]
Hi Eugene - can you please describe the use case you are trying to address / problem you are trying to solve?  Thanks, Andre.

**Comment by euhruska** [comment]
This feature tries to solve the challenge how to implement as simply as possible the complex dependencies what tasks to submit next. Non-blocking tasks would allow the user to implement almost arbitrary logic between the non-blocking calls. I consider the post_exec call, which requires the definition of the dependencies much earlier, while previous tasks are submitted, in some situations restricting. The difference between this feature request and post_exec is Eager execution vs. "Delayed execution" programming paradigm. I consider Eager execution more friendly to newcomers, easier to debug, and with a more natural control flow.

**Comment by iparask** [comment]
@andre-merzky, we had a discussion with Eugene about this yesterday. I'll open a discussion and put Eugene's input there as well as my notes. How does that sound?

**Comment by andre-merzky** [comment]
Thanks @iparask , sounds good to me.

**Comment by iparask** [comment]
Moved everything to discussion #542. @euhruska your input there will be useful.

I will close this issue in favor of the discussion
