### ISSUE TITLE
Sandbox is not created on the remote resource

### ISSUE THREAD

**Issue by akashban** [radical-cybertools/radical.entk#541]
Hello @andre-merzky @lee212 

My ENTK script works on my local machine, but when I try to launch it on the remote resource, I get the following error (located in the main log file):

##############################
1611956551.259 : radical.saga.cpi     : 479   : 139763954788096 : ERROR    : DoesNotExist: file copy failed: '/home/abanerjee/ve-entk/lib/python3.7/site-packages/radical/pilot/agent/bootstrap_0.sh' -> '/work/04676/tg839752/stampede2/radical.pilot.sandbox/re.session.abanerjee-OptiPlex-990.abanerjee.018656.0029/pilot.0000/bootstrap_0.sh'
/bin/cp: cannot create regular file '/work/04676/tg839752/stampede2/radical.pilot.sandbox/re.session.abanerjee-OptiPlex-990.abanerjee.018656.0029/pilot.0000/bootstrap_0.sh': No such file or directory
$
1611956551.260 : stager.0000          : 479   : 139763954788096 : ERROR    : work <bound method Stager.work of <radical.pilot.worker.stager.Stager object at 0x7f1d54e1b3c8>> failed
Traceback (most recent call last). 
###########################################

This seems like a saga level error, and hence it would be great if I could get some help in diagnosis. I have attached my log file + host_sandbox here. No sandbox is generated on the remote resource. 

[log_files.zip](https://github.com/radical-cybertools/radical.entk/files/5896740/log_files.zip)

**Comment by andre-merzky** [comment]
Hi @akashban : I apologize for this problem - we also realized today that the last release introduced an error for remote submission.  That is fixed by now in this PR: radical-cybertools/radical.pilot/pull/2311 (one layer under radical.entk), and we'll push that out right after code review.  If you don't want to wait, you could install the ` hotfix/stage_bs_0` branch of radical.pilot (the above PR).

**Comment by akashban** [comment]
Hi @andre-merzky , Thank you for your quick response. I am actually getting the issue with an older version which @lee212 told me to try, i.e. 1.5.1

This is my radical-stack:

  python               : /home/abanerjee/ve-entk/bin/python3
  pythonpath           : 
  version              : 3.7.2
  virtualenv           : /home/abanerjee/ve-entk

  radical.entk         : 1.5.1
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.11
  radical.saga         : 1.5.9
  radical.utils        : 1.5.9

I will also try what you just suggested above.

**Comment by andre-merzky** [comment]
> I am actually getting the issue with an older version

Oh, then we may have introduced earlier than I thought... :-/  Thanks for giving the branch a try, let us know how it goes!

**Comment by akashban** [comment]
@andre-merzky , I updated my radical-stack to:

  python               : /home/abanerjee/ve-entk/bin/python3
  pythonpath           : 
  version              : 3.7.2
  virtualenv           : /home/abanerjee/ve-entk

  radical.entk         : 1.5.1
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.11-v1.5.11-66-g75a73a6@hotfix-stage_bs_0
  radical.saga         : 1.5.9
  radical.utils        : 1.5.9

Now, the sandbox is generated on the remote resource, but I eventually get a keyboard interrupt error (which I do not know how to diagnose). This happens before my simulations run. I have attached my log files here. 

I tested everything on my local machine: works fine on it.

[log_files.zip](https://github.com/radical-cybertools/radical.entk/files/5896856/log_files.zip)

**Comment by andre-merzky** [comment]
@akashban : the bootstrapper does not report any problems while preparing the pilot environment - but that fails then anyway :-/  Can you please check on Stampede2 if `/work/04676/tg839752/stampede2/radical.pilot.sandbox/re.session.abanerjee-OptiPlex-990.abanerjee.018656.0030/pilot.0000/rp_install/bin/radical-pilot-bridge` exists and if it can be executed?  It will fail if you just execute it manually, but it should at least be executable.

**Comment by akashban** [comment]
@andre-merzky , yes radical-pilot-bridge exists in the given folder and it is an executable (that is failing when I try to execute manually)

If you dont mind, for future diagnosis, I want to learn what details you looked for in the log files that suggested eventual failure in preparing the pilot environment. I am not able to connect the dots between the keyboard interrupt error and creation of pilot environment.

**Comment by akashban** [comment]
Hi @andre-merzky , Just wanted to follow up regarding the sandbox issue. 

Thanks
Akash

**Comment by andre-merzky** [comment]
Hi @akashban - sorry for the late reply!

> If you don't mind, for future diagnosis, I want to learn what details you looked for in the log files

I follow the pilot startup sequence.  First the bootstrapper shell script is started and produces output in `bootstrap_0.out` - that might be a bit tedious to parse as it is rather verbose, but errors should stick out.  

The bootstrapper starts the agent(s), so check `agent.0.out  agent.0.err agent.1.out agent.1.err ...` (the number of agents depends on the resource configuration).  

Once the agents are up, all logging goes to `*.log` files, and finding errors becomes easier: `grep ERROR *.log`.  Last but not least, some errors evade the logging system, check if you find output in `*.out *.err`.  Those should be mostly empty (apart from `bootstrap_0.out` as described above).

Making it easier to discern different error modes is on our roadmap, but alas will not appear very soon...

**Comment by andre-merzky** [comment]
I just realized that the above does not help you with your actual problem, you are still stuck, right?  @mtitov : Mikhael, do you have access to Stampede2?  If so, would you mind having a look at what's up there?

**Comment by akashban** [comment]
@andre-merzky @mtitov , I just had a look. I am still getting the same problem. Please let me know if I can help.

**Comment by mtitov** [comment]
Hi @akashban, I see in logs something strange with pip installation of RP on remote machine
```
# update radical.pilot-1.5.11-v1.5.11-66-g75a73a6-hotfix-stage-bs-0/ via pip
# cmd: /work/04676/tg839752/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.1.5.11/bin/python -m pip install  --src '/work/04676/tg839752/stampede2/radical.pilot.sandbox/re.session.abanerjee-OptiPlex-990.abanerjee.018656.0030/pilot.0000/rp_install/src' --prefix '/work/04676/tg839752/stampede2/radical.pilot.sandbox/re.session.abanerjee-OptiPlex-990.abanerjee.018656.0030/pilot.0000/rp_install' --no-deps --no-cache-dir --no-build-isolation radical.pilot-1.5.11-v1.5.11-66-g75a73a6-hotfix-stage-bs-0/
#
Processing ./radical.pilot-1.5.11-v1.5.11-66-g75a73a6-hotfix-stage-bs-0
Building wheels for collected packages: radical.pilot
  Building wheel for radical.pilot (setup.py): started
  Building wheel for radical.pilot (setup.py): finished with status 'done'
  Created wheel for radical.pilot: filename=radical.pilot-1.5.11_v1.5.11_66_g75a73a6_hotfix_stage_bs_0-py3-none-any.whl size=1148739 sha256=abc0796f148dd7761c3af9e78ce0bd6a214f4a01e8ada4de9178c7b15fc2d549
  Stored in directory: /tmp/pip-ephem-wheel-cache-_yjr3r3w/wheels/65/a4/eb/8c4770bff7a5891b7fba7f3d7bc026ce7d15d778fa9887151a
  WARNING: Built wheel for radical.pilot is invalid: Metadata 1.2 mandates PEP 440 version, but '1.5.11-v1.5.11-66-g75a73a6-hotfix-stage-bs-0' is not
Failed to build radical.pilot
Installing collected packages: radical.pilot
    Running setup.py install for radical.pilot: started
    Running setup.py install for radical.pilot: finished with status 'done'
  DEPRECATION: radical.pilot was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed radical.pilot-1.5.11-v1.5.11-66-g75a73a6-hotfix-stage-bs-0
```
can I ask to try the latest release of RP (that includes this branch as well) 1.5.12, and I will make tests on Stampede2 as well

**Comment by akashban** [comment]
Hi, @mtitov @andre-merzky , The issue has been resolved with the latest release of RP. Thank you so much for pointing towards it. My scripts are working on the development queue of stampede2. Currently, I have launched it on the normal queue, with a wall time of 2 days. So, it would be great if we could keep this ticket open until the entk script successfully terminates. 

@andre-merzky : Thank you so much for your detailed explanation of your diagnosis. It was very helpful.

**Comment by akashban** [comment]
Hi @andre-merzky , The job performed well on stampede2 for 2 days (maximum allowed wall time). Thank you for your and @mtitov help. 
As you mentioned in your previous comment, on previous occasions, my jobs have been terminated before the 24 hour mark. 
So, when and if it happens again, what should I do to fix the issue?

**Comment by andre-merzky** [comment]
Thanks for the ping-back!

> As you mentioned in your previous comment, on previous occasions, my jobs have been terminated before the 24 hour mark.
> So, when and if it happens again, what should I do to fix the issue?

It depends on what exactly caused the termination: it can be the cluster network capping the connection, or the MongoDB server which is used in the background, or some process cleanup on the login nodes.  And in many cases we can't do much about it :-(
Since we thus think that avoiding interruption is not really possible in all cases anyway, we plan to become resilient against it: we work on the ability to reconnect an interrupted session.  Alas, while tat feature is on our roadmap for this year, it will not emerge quickly...

**Comment by akashban** [comment]
Thank you for the detailed explanation of the connection issue. These tickets are really helpful in understanding the architecture of ENTK. The strategy to reconnect an interrupted session sounds interesting!

I sincerely appreciate your time! Thanks @andre-merzky
