### ISSUE TITLE
Placeholder for data of ALL instances of a step

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.entk#55]
... to avoid constructs like this: https://github.com/radical-cybertools/radical.ensemblemd/blob/master/usecases/extasy_coco_amber/01_static_amber_coco_loop.py#L125

**Comment by vivek-bala** [comment]
ALL instances*

**Comment by oleweidner** [comment]
Indeed ;-) Title changed.

**Comment by vivek-bala** [comment]
Placeholder format has changed and this can be addressed at the user level itself.
