### ISSUE TITLE
`argument` should complain early on `int` type elements

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#559]
See https://github.com/radical-collaboration/hpc-workflows/issues/131

This should trivially be fixed once the RE task description is rebased to `ru.Description`.

**Comment by mtitov** [comment]
resolved - attribute `arguments` has the following pattern in schema `[str]`
https://github.com/radical-cybertools/radical.entk/blob/5af9d8fd6842a8fdbbf6d97db3238c88d17d0de4/src/radical/entk/task.py#L370
