### ISSUE TITLE
Task executable inherits EnTK's PYTHONPATH

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#561]
On LLNL Lassen, I experienced odd behavior of python executable from importing numpy. There are two separate conda environments, conda-rct for EnTK, and conda-keras-powerai for task executable, and the error indicates that task executable inherits EnTK's PYTHONPATH to search packages:

```
# task.xxxxxx.err file #

Traceback (most recent call last):
  File "/p/gpfs1/envs/conda-rct/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/p/gpfs1/envs/conda-rct/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/p/gpfs1/envs/conda-rct/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/p/gpfs1/envs/conda-rct/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/p/gpfs1/envs/conda-rct/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.6 from "/p/gpfs1/envs/conda-keras-powerai/bin/python"
  * The NumPy version is: "1.19.2"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: No module named 'numpy.core._multiarray_umath'
``` 

You can find that the task executable `/p/gpfs1/envs/conda-keras-powerai/bin/python` is python3.6 but numpy was located from `conda-rct/lib/python3.7`. I also print out `os.environ`  and here the `PYTHONPATH`:
```
'/p/gpfs1/envs/conda-rct/rp_install/lib/python3.7/site-packages:/p/gpfs1/envs/conda-rct/lib/python3.7/site-packages:'
```

I have a workaround about this issue by emptying `PYTHONPATH=''` at `pre_exec` so the executable works okay but this can be problematic to other use cases if it has multiple environments.

**Comment by andre-merzky** [comment]
Is `/p/gpfs1/envs/conda-rct/` the env the pilot uses?

This issue is addressed  with the 'environment isolation' we have been discussing on the devel call, which is scheduled for release fairly soon.  Will you be able to live with the workaround for some weeks, or do you need a solution for the multi-environment case until then?

**Comment by lee212** [comment]
Yes, that is the env that RP uses, and this issue can wait until the next release with 'environment isolation'. I wanted that this issue is noted for future reference.
