### ISSUE TITLE
Addressing stdout and stderr on failed radical pilot tasks

### ISSUE THREAD

**Issue by drawadiagram** [radical-cybertools/radical.entk#562]
BACKGROUND
I want to address the task stdout and stderr files resulting from a failed rp.entk task using a stage.post_exec script or similar. I will use the stderr information for control flow in a PACE application we are developing based on entk. The idea is to flag candidate MD parameterizations that result in an error, associate them with their error type, modify the candidate pool accordingly, and continue running. I am not aware of another way I can access this task.stderr information in the entk user environment. Srinivas Mushnoori from the Dutt group and I have both tested this application, and it seems that entk shuts down file movement on task failure.

The plan:
1) Save error output with task.post_exec.
2) Read task error text from a stage.post_exec script.

CURRENT BEHAVIOR
entk task.post_exec works to copy the stdout/stderr file contents to a new file, but neither copy_output_data nor link_output_data can move those files on a failed task. In my application the failed task is still providing important information.

For example, this works whether task completes or fails:
t.stderr = 't1stderr.txt' # rename the stderr file
t.post_exec = [ 'cat t1stderr.txt >> myerror.txt' ] # put the contents of that file in another file

This only works if the task completes, does not work if it fails:
t.copy_output_data = [ 'myerror.txt >> /some/path/myerror.txt' ] # put file in user space for stage postexec script

At stage postexec time, is there another way to access task postexec information?
e.g.
s.post_exec = func_post # or whatever
def func_post():
with open(s.t.stderr?) as f:
...

**Comment by andre-merzky** [comment]
Hi @drawadiagram - the lack of output staging has been a complaint by several users already - I think we should provide that capability - I'll take this as a feature request.

**Comment by andre-merzky** [comment]
This is now addressed in the `fix/re_issue_562` branch in RP.  @iparask : would you mind making the `stage_on_error` flag available in the RE task description?

**Comment by iparask** [comment]
Yes, I will do it.

**Comment by iparask** [comment]
This is addressed now in the `devel` branch.

**Comment by iparask** [comment]
I'm closing this issue as it will be addressed with the next release. Thank you
