### ISSUE TITLE
How to change default folder in remote resource (stampede2)

### ISSUE THREAD

**Issue by akashban** [radical-cybertools/radical.entk#564]
HI @andre-merzky and @lee212 , 

The sandbox in stampede2 is created in the work folder. Stampede2 is transitioning over to work2. Could you please point me towards a reference where I can change the default directory in the resource_dict ?

Thank you for your help.
Akash

**Comment by andre-merzky** [comment]
[This](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_xsede.json#L34) would be the place you want to change (and similar for the other `stampede2` entries in the same file).  I you are up to it, do you want to do the change and submit a pull request?  No worries if not, then we'll get this done.

**Comment by akashban** [comment]
Thank you @andre-merzky . To be honest, I am still getting familiar with collaborating on GitHub. Would it be possible to assign someone else? I promise I would be able to help you more in the upcoming year :)

**Comment by andre-merzky** [comment]
> Thank you @andre-merzky . To be honest, I am still getting familiar with collaborating on GitHub. Would it be possible to assign someone else? I promise I would be able to help you more in the upcoming year :)

I am glad you are speaking up!  :-)

**Comment by iparask** [comment]
There is a branch in RP named `fix/stampede2_fs` that uses work2 as the default filesystem. @akashban, thank you for letting us know!

**Comment by andre-merzky** [comment]
This is now fixed in radical.pilot's `devel` branch (see radical-cybertools/radical.pilot/pull/2365 - thanks @iparask!).  This will be released in about 10 days. @akashban: if you need the change before then, please switch to that `devel` branch until then.

**Comment by akashban** [comment]
Thank you so much for your help @andre-merzky and @iparask
