### ISSUE TITLE
Setting all simulation parameters in main with consistent namings

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.entk#57]
I think it would be useful if examples and usecases for all patterns would have similarly named setter methods to set number of instances, cycles and so on. As of now these are set differently in each pattern and it is somewhat unintuitive. It would be better if in "main" users could do something like:

```
cluster = SingleClusterEnvironment(
    resource="localhost",
    cores=1, 
    walltime=15
)

# Allocate the resources.
cluster.allocate()

# creating RE pattern object
re_pattern = RePattern()

# set number of cycles
re_pattern.set_simulation_cycles(5)

# set number of replicas
re_pattern.set_instances(32)
```

otherwise calls like pattern = MyPattern(iterations=iterNum, instances=CU) require user to search where iterNum and CU are set in code

**Comment by marksantcroos** [comment]
consistent naming: +1
getters and setters: -1

**Comment by AntonsT** [comment]
>getters and setters: -1

For examples and usecases should be OK.

**Comment by marksantcroos** [comment]
> For examples and usecases should be OK.

Its not conventional in python. Why would it be better than assignments?

**Comment by AntonsT** [comment]
OK:

```
cluster = SingleClusterEnvironment(
    resource="localhost",
    cores=1, 
    walltime=15
)

# Allocate the resources.
cluster.allocate()

# creating RE pattern object
re_pattern = RePattern()

# set number of cycles
re_pattern.set_simulation_cycles = 5

# set number of replicas
re_pattern.set_instances = 32
```

**Comment by AntonsT** [comment]
but this should happen in one place e.g. in main

**Comment by marksantcroos** [comment]
> but this should happen in one place e.g. in main

Right, but I agreed on that earlier already :-)

**Comment by vivek-bala** [comment]
No longer applicable.
