### ISSUE TITLE
Key tag not in schema

### ISSUE THREAD

**Issue by ethzan** [radical-cybertools/radical.entk#574]
When attempting to run a script using radical.entk:

`Traceback (most recent call last):
  File "/home/ethan/venvs/radical_env/lib/python3.8/site-packages/radical/entk/execman/rp/task_manager.py", line 336, in _process_tasks
    rp_tmgr.submit_tasks(bulk_tds)
  File "/home/ethan/venvs/radical_env/lib/python3.8/site-packages/radical/pilot/task_manager.py", line 841, in submit_tasks
    task = Task(tmgr=self, descr=ud)
  File "/home/ethan/venvs/radical_env/lib/python3.8/site-packages/radical/pilot/task.py", line 61, in __init__
    descr.verify()
  File "/home/ethan/venvs/radical_env/lib/python3.8/site-packages/radical/utils/munch.py", line 359, in verify
    raise TypeError('%s: key %s not in schema'`

Corresponding log files are attached. Can you advise on how to resolve?
[log.zip](https://github.com/radical-cybertools/radical.entk/files/6347573/log.zip)

**Comment by mtitov** [comment]
hi @ethzan, can you please provide more information on what you are trying to run? This error shows that some provided data had wrong keys (which don't match `TaskDescription`'s schema)

**Comment by ethzan** [comment]
Hi @mtitov, I am trying to run an example for PACE, the ENTK application that Srinivas and I have been collaborating on.

Do you have any insight on where to check for misuse of the radical.entk API to resolve this error? Thanks.

**Comment by SrinivasMushnoori** [comment]
@ethzan I think it would be more helpful if we post the task description and/or link to the appropriate part of the PACE code?

**Comment by ethzan** [comment]
We have 3 different stages with unique task descriptions:

**Stage 1**
`basename = self.candidate_specifications['basename']
        sysname = basename + "." + str(self.cid)
        c_head = [basename + "/" + sysname + "/" + basename + ".gro",
                  basename + "/" + sysname + "/" + basename + ".itp",
                  basename + "/" + sysname + "/" + basename + ".mdp",
                  basename + "/" + sysname + "/" + basename + ".top",
                  basename + "/" + sysname + "/" + "martini_v2.2.itp"]

        # Create pre md stage
        pre_md_stage = Stage()
        pre_md_stage.name = 'premdstage'
        # Create pre md task
        pre_md_task = Task()
        pre_md_task.name = 'premdtask'  ####
        pre_md_task.executable = self.candidate_specifications['md_executable']
        pre_md_task.arguments = self.candidate_specifications['md_pre_exec']
        if self.cycle_count == 0:
            pre_md_task.upload_input_data = c_head
        else:
            # Take the same file names from c_head, no sysname/basename
            pre_md_task.link_input_data = ['$Pipline_%s_Stage_%s_Task_%s/outcrd.gro > %s.gro' % (sysname, 'mdstage'+str(self.cycle_count-1), 'mdtask', basename),
                                           '$Pipline_%s_Stage_%s_Task_%s/%s.itp'              % (sysname, 'mdstage'+str(self.cycle_count-1), 'mdtask', basename),
                                           '$Pipline_%s_Stage_%s_Task_%s/%s.mdp'              % (sysname, 'mdstage'+str(self.cycle_count-1), 'mdtask', basename),
                                           '$Pipline_%s_Stage_%s_Task_%s/%s.top'              % (sysname, 'mdstage'+str(self.cycle_count-1), 'mdtask', basename),
                                           '$Pipline_%s_Stage_%s_Task_%s/martini_v2.2.itp'    % (sysname, 'mdstage'+str(self.cycle_count-1), 'mdtask')]
        pre_md_stage.add_tasks(pre_md_task)
        # Add pre md stage to pipeline
        self.pipeline.add_stages(pre_md_stage)`

**Stage 2**
`# Create pre md stage
        self._create_pre_md_stage()
        # Create md stage
        md_stage = Stage()
        md_stage.name = 'mdstage' + str(self.cycle_count)
        # Create md task
        md_task = Task()
        md_task.name = 'mdtask'
        md_task.executable = self.candidate_specifications['md_executable']
        md_task.arguments = self.candidate_specifications['md_args']

        sysname = self.candidate_specifications['basename'] + "." + str(self.cid)
        md_task.link_input_data = ['$Pipline_%s_Stage_%s_Task_%s/sys.tpr' % (sysname, "premdstage", "premdtask")]

        md_stage.add_tasks(md_task)
        # Add md stage to pipeline
        self.pipeline.add_stages(md_stage)`

**Stage 3**
`# Create analysis stage
        an_stg = Stage()
        an_stg.name = 'analysisstage' + str(self.cycle_count)
        # Create the analysis task
        an = Task()
        an.name = 'analysistask'
        an.executable = self.candidate_specifications['an_executable']
        an_args = []
        # Add all analysis arguments in candidate specifications json
        for arg in self.candidate_specifications['an_args'].split():
            an_args.append(arg)
        an.arguments = an_args

        # Create file with success/failure output of analysis stage
        sysname = self.candidate_specifications['basename'] + "." + str(self.cid)
        filename = 'out{}.txt'.format(sysname)
        file_number = 1
        while os.path.isfile(filename):
            filename = 'out{}'.format(sysname) + '.{}'.format(file_number) + '.txt'
            file_number += 1

        f = open(filename, 'x')
        f.close()

        # Copy output of analysis out.txt to unique file
        an.download_output_data = ['out.txt > {}'.format(filename)]
        # an.copy_input_data = ['$Pipline_%s_Stage_%s_Task_%s/file.tar.gz' % (p.name, md_stg.name, md.name),]
        an_stg.add_tasks(an)

        # Add analysis stage to pipeline
        self.pipeline.add_stages(an_stg)
        return an_stg`

**Comment by ethzan** [comment]
We have 3 different stages with different task descriptions:
**Stage 1**
```
basename = self.candidate_specifications['basename']
        sysname = basename + "." + str(self.cid)
        c_head = [basename + "/" + sysname + "/" + basename + ".gro",
                  basename + "/" + sysname + "/" + basename + ".itp",
                  basename + "/" + sysname + "/" + basename + ".mdp",
                  basename + "/" + sysname + "/" + basename + ".top",
                  basename + "/" + sysname + "/" + "martini_v2.2.itp"]

        # Create pre md stage
        pre_md_stage = Stage()
        pre_md_stage.name = 'premdstage'
        # Create pre md task
        pre_md_task = Task()
        pre_md_task.name = 'premdtask'  ####
        pre_md_task.executable = self.candidate_specifications['md_executable']
        pre_md_task.arguments = self.candidate_specifications['md_pre_exec']
        if self.cycle_count == 0:
            pre_md_task.upload_input_data = c_head
        else:
            # Take the same file names from c_head, no sysname/basename
            pre_md_task.link_input_data = ['$Pipline_%s_Stage_%s_Task_%s/outcrd.gro > %s.gro' % (sysname, 'mdstage'+str(self.cycle_count-1), 'mdtask', basename),
                                           '$Pipline_%s_Stage_%s_Task_%s/%s.itp'              % (sysname, 'mdstage'+str(self.cycle_count-1), 'mdtask', basename),
                                           '$Pipline_%s_Stage_%s_Task_%s/%s.mdp'              % (sysname, 'mdstage'+str(self.cycle_count-1), 'mdtask', basename),
                                           '$Pipline_%s_Stage_%s_Task_%s/%s.top'              % (sysname, 'mdstage'+str(self.cycle_count-1), 'mdtask', basename),
                                           '$Pipline_%s_Stage_%s_Task_%s/martini_v2.2.itp'    % (sysname, 'mdstage'+str(self.cycle_count-1), 'mdtask')]
        pre_md_stage.add_tasks(pre_md_task)
        # Add pre md stage to pipeline
        self.pipeline.add_stages(pre_md_stage)
```

**Stage 2**
```
# Create pre md stage
        self._create_pre_md_stage()
        # Create md stage
        md_stage = Stage()
        md_stage.name = 'mdstage' + str(self.cycle_count)
        # Create md task
        md_task = Task()
        md_task.name = 'mdtask'
        md_task.executable = self.candidate_specifications['md_executable']
        md_task.arguments = self.candidate_specifications['md_args']

        sysname = self.candidate_specifications['basename'] + "." + str(self.cid)
        md_task.link_input_data = ['$Pipline_%s_Stage_%s_Task_%s/sys.tpr' % (sysname, "premdstage", "premdtask")]

        md_stage.add_tasks(md_task)
        # Add md stage to pipeline
        self.pipeline.add_stages(md_stage)
```


**Stage 3**
```
# Create analysis stage
        an_stg = Stage()
        an_stg.name = 'analysisstage' + str(self.cycle_count)
        # Create the analysis task
        an = Task()
        an.name = 'analysistask'
        an.executable = self.candidate_specifications['an_executable']
        an_args = []
        # Add all analysis arguments in candidate specifications json
        for arg in self.candidate_specifications['an_args'].split():
            an_args.append(arg)
        an.arguments = an_args

        # Create file with success/failure output of analysis stage
        sysname = self.candidate_specifications['basename'] + "." + str(self.cid)
        filename = 'out{}.txt'.format(sysname)
        file_number = 1
        while os.path.isfile(filename):
            filename = 'out{}'.format(sysname) + '.{}'.format(file_number) + '.txt'
            file_number += 1

        f = open(filename, 'x')
        f.close()

        # Copy output of analysis out.txt to unique file
        an.download_output_data = ['out.txt > {}'.format(filename)]
        # an.copy_input_data = ['$Pipline_%s_Stage_%s_Task_%s/file.tar.gz' % (p.name, md_stg.name, md.name),]
        an_stg.add_tasks(an)

        # Add analysis stage to pipeline
        self.pipeline.add_stages(an_stg)
        return an_stg
```

**Comment by andre-merzky** [comment]
`Key tag not in schema`: We recently changed the task description *underneath* radical.entk (which is used by repex).  EnTK was changed to account for that change.  You probably need to update EnTK to make sure that the mapping is correct again. Can you give that a try, please?  If the same problem persists, please send us the output of `radical-stack`.

**Comment by mturilli** [comment]
@ethzan did updating RCT stack as suggested by @andre-merzky solved your issue? If so, I would close this ticket.

**Comment by ethzan** [comment]
Yes. Thank you!

**Comment by andre-merzky** [comment]
Great!
