### ISSUE TITLE
Supporting virtual host and SSL in pika

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#577]
With virtual host, a single RabbitMQ server can provide multiple user-space separate from others. Our use case from LLNL Lassen requires defining a specific virtual host as their RMQ is a multi-tenant system. To allow choosing vhost name under EnTK, the extra information defined by a user need to be forwarded to pika. For example, with the extra variable e.g., `RMQ_VHOST=/deepdrive`, pika sets connectionParameters.

**Comment by mturilli** [comment]
@lee212 are you going to create a PR for this?

**Comment by lee212** [comment]
Yes, I created PR #586
