### ISSUE TITLE
Example eop.py fails with apparent MongoClient fork error 

### ISSUE THREAD

**Issue by drawadiagram** [radical-cybertools/radical.entk#578]
I am attempting to run the eop.py example on a fresh entk install in a virtual environment. All tasks seem to schedule and then fail. The session closes correctly. I am testing this in a fresh environment because this no longer works in the environment I was using with some success a month ago. For this test I am using RMQ on localhost, and MongoDB mongodb://scm177:[password]@129.114.17.185:27017/repex_3

I see this apparent MDB error in the output:

> Update: pipeline.0000.stage.0000 state: SCHEDULED
> MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
>                                                            ok
> Update: pipeline.0003.stage.0009.task.0009 state: SUBMITTING
> submit: #################

See logs and output attached. Output from `radical-stack` as follows:

> 
>   python               : /home/mason/dutt_lab/pacer/bin/python3
>   pythonpath           : 
>   version              : 3.6.9
>   virtualenv           : /home/mason/dutt_lab/pacer
> 
>   radical.entk         : 1.6.5
>   radical.gtod         : 1.5.0
>   radical.pilot        : 1.6.5
>   radical.saga         : 1.6.5
>   radical.utils        : 1.6.5

Please advise.
[re.session.navi.mason.018766.0004.zip](https://github.com/radical-cybertools/radical.entk/files/6505455/re.session.navi.mason.018766.0004.zip)
[verbose.log](https://github.com/radical-cybertools/radical.entk/files/6505456/verbose.log)

**Comment by mturilli** [comment]
@drawadiagram can you confirm this now works so that we can close this ticket?

**Comment by drawadiagram** [comment]
@mturilli I am still having trouble with the RMQ ticket, which errors out my authentication before I can get to this one. Previously I was able to use a local RMQ instance to bridge, but that is no longer available on my local system. Please advise.

**Comment by mturilli** [comment]
`examples/simple/eop.py|poe.py` are broken. This is not an issue with the user. I am going to close this ticket and open one for the EnTK team to fix those examples.
