### ISSUE TITLE
RMQ Radical Account Error

### ISSUE THREAD

**Issue by drawadiagram** [radical-cybertools/radical.entk#579]
When attempting to use my Radical account for RMQ server, I receive the following error:
> radical.entk.exceptions.EnTKError: (403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.')

Matteo reset my password last week, so I am confident I am using the correct password. Seems like this might be a permissioning issue? Found this on SO:
https://stackoverflow.com/questions/26811924/spring-amqp-rabbitmq-3-3-5-access-refused-login-was-refused-using-authentica

**Comment by mturilli** [comment]
Hi @drawadiagram, there might have been an issue with the SSL certificate of RabbitMQ. I updated the certificate and restarted the server. Could you try and see whether that has solved your issue?

**Comment by drawadiagram** [comment]
Hi @mturilli,
I just tried again, but still see the same error. Here is the full output:

> EnTK session: re.session.navi.mason.018780.000
> Creating AppManagerSetting up RabbitMQ system                                 ok
> Traceback (most recent call last):
>   File "/home/mason/dutt_lab/pace/pace_env/lib/python3.8/site-packages/radical/entk/appman/appmanager.py", line 553, in _setup_mqs
>     mq_connection = pika.BlockingConnection(self._rmq_conn_params)
>   File "/home/mason/dutt_lab/pace/pace_env/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 377, in __init__
>     self._process_io_for_connection_setup()
>   File "/home/mason/dutt_lab/pace/pace_env/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 416, in _process_io_for_connection_setup
>     self._flush_output(self._opened_result.is_ready,
>   File "/home/mason/dutt_lab/pace/pace_env/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 469, in _flush_output
>     raise maybe_exception
> pika.exceptions.ProbableAuthenticationError: (403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.')
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "./pace_env/share/radical.entk/examples/simple/eop.py", line 85, in <module>
>     appman = AppManager(hostname=hostname, port=port)
>   File "/home/mason/dutt_lab/pace/pace_env/lib/python3.8/site-packages/radical/entk/appman/appmanager.py", line 128, in __init__
>     self._setup_mqs()
>   File "/home/mason/dutt_lab/pace/pace_env/lib/python3.8/site-packages/radical/entk/appman/appmanager.py", line 587, in _setup_mqs
>     raise ree.EnTKError(ex) from ex
> radical.entk.exceptions.EnTKError: (403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.')

**Comment by drawadiagram** [comment]
I don't think anyone responded to my most recent post above? Also I have not had a chance to check my MDB error since the RMQ error is getting in my way, so I can't really say if that one is resolved for me either. @mturilli

**Comment by mturilli** [comment]
The RMQ service was down when you posted your comment. I restarted it and it is now up and running, apparently without issues. Other users do not report the same issue so let's focus on your code/credentials. Can I have a small script to replicate the problem? You can send me your credentials privately and I will try to debug the issue.

**Comment by drawadiagram** [comment]
@mturilli The output above happens when I try running the root/share/examples/simple/eop.py packaged with the base install of entk, in a Python 3.8.5 virtualenv. 

Before running, I export the environment variables in my shell (Bash) per section 3.2 in [the entk docs](https://radicalentk.readthedocs.io/en/latest/install.html). I use the RCT account spreadsheet values for those variables, with username 'mason' and password what you recently emailed to me.

My local machine is running Ubuntu 20.04.2 LTS x64. If there are any dependencies not documented in the entk docs (e.g. Python dev tools) let me know and I will check my system versions.

**Comment by mturilli** [comment]
Thank you for the details. Let me try to debug this on our VM with your credentials and I will be back to you with the result.

**Comment by mturilli** [comment]
@drawadiagram , I struggled to trace down your issue as for me it all worked as expected. I recreated the credentials in RMQ. Could you give it another try?

**Comment by mturilli** [comment]
Fixes #578

**Comment by drawadiagram** [comment]
@mturilli I still get the same error, I must be missing a step in preparing the environment. I will confer with the other folks in the lab and get back to you soon.

**Comment by mturilli** [comment]
This was a problem with mongodb and using special characters (+?) in the password. Now solved.
