### ISSUE TITLE
Failed running a slightly modified version of the echo example

### ISSUE THREAD

**Issue by Brian-Szutu** [radical-cybertools/radical.entk#595]
Hello, I ran into an issue of a modified version of the basic echo example task failing. Could I get some assistance in solving this? Thanks in advance.
The code was run on Ubuntu on VirtualBox, with the following toolkit version being used:  
```
  python               : /home/brian/ve-entk/bin/python3
  pythonpath           : 
  version              : 3.8.10
  virtualenv           : /home/brian/ve-entk

  radical.entk         : 1.8.0
  radical.gtod         : 1.6.7
  radical.pilot        : 1.9.2
  radical.saga         : 1.8.0
  radical.utils        : 1.8.4
 ```
Attached are the agent folder, client folder, and console log (with the former two in ZIP format since I wasn't able to get GitHub to accept them as TARs).
[agent.zip](https://github.com/radical-cybertools/radical.entk/files/7525240/agent.zip)
[client.zip](https://github.com/radical-cybertools/radical.entk/files/7525241/client.zip)
[018943_command_log.log](https://github.com/radical-cybertools/radical.entk/files/7525242/018943_command_log.log)

**Comment by andre-merzky** [comment]
Would you mind attaching the script you try to run?  Thank you!

**Comment by Brian-Szutu** [comment]
Sure, here it is. I'm currently testing this on the radical-provided MongoDB database and rabbitmq server
[workflow_test.zip](https://github.com/radical-cybertools/radical.entk/files/7530071/workflow_test.zip)

**Comment by AymenFJA** [comment]
Closing for now.
