### ISSUE TITLE
Is it possible to assign orders for tasks within the same stage in entk?

### ISSUE THREAD

**Issue by GKNB** [radical-cybertools/radical.entk#640]
The feature I request is to execute tasks within the same stage in some order. There might be some trick that allows us to do that, but currently I have not found it, please let me know if this is currently possible in the framework of rct. Thanks!

One thing I want to mention is that, I tried to follow the example in https://radicalentk.readthedocs.io/en/stable/api/adv_examples/adapt_tc.html, where the example uses stage.post_exec() to create a new stage within the same pipeline when the current stage is finished. I tried to mimic that by using task.post_exec() to create a new task within the same stage when the current task is finished. If this is allowed then we can actually assign order for tasks within stage by dynamically adding new task in runtime. However I got an error, and it seems like this is not allowed.

The reason why I need this feature is that, currently I have the following workflow:
|-------------task_1A-------------|-------------task_2A-------------|-------------task_3A-------------|......
|--task_1B---task_1C----task_1D|--task_2B---task_2C----task_2D|--task_3B---task_3C----task_3D|......
|-------------stage_1-------------|-------------stage_2-------------|-------------stage_3-------------|......

where we have 4k tasks (in this plot, k=3), and we want to make sure that 1). task_(i+1)A start after task_(i)D finish, and 2). task_iB, task_iC and task_iD are executed in sequential order. A more illustrative plot of the workflow can be found in the figure attached. My current idea is to use a single pipeline, with k stages, and put task_(i)[A,B,C,D] in the same stage, but that means we need to be able to specify the order of task_(i)[B,C,D] within the same stage_i.

Another project which current is formulated without rct has a similar pattern as follows:
pipeline_1:
|--task_1A---task_1B--|--task_1E--|
|--task_1C---task_1D--|
|------stage_1---------|--stage_2--|
pipeline_2:
|--task_2A---task_2B--|--task_2E--|
|--task_2C---task_2D--|
|------stage_1---------|--stage_2--|
More pipelines....

and we have many pipelines. We want to make sure that within the same pipeline_i, task_(i)B is executed after task_(i)A is finished, and task_(i)D is executed after task_(i)C is finished, and task_(i)E is executed after task_(i)[B,D] are finished. Currently this is done by an ugly bash script using the dependency feature of slurm, but it is not potable. We might not use rct for this project later, but I want to use this example to show that order of tasks within the same stage could be really helpful, especially when we have complicated task dependency.

Thanks!
![adv_workflow](https://user-images.githubusercontent.com/17077542/225844685-472bae48-ab67-446a-a4c1-aa37d4386599.JPG)

**Comment by andre-merzky** [comment]
We discussed this again and the answer is no, EnTK will not be able to express or handle task ordering within a single stage.  Thanks for providing the use case in detail, we'll take that into account!

**Comment by shantenujha** [comment]
We might not be able to provide native support in EnTK, but  is there a recommended way to do so? 

Clearly with two use cases documented here, and others that I can imagine, I wonder if this is something that we can advise our users on how to possibly do so, with the usual caveat & caution YMMV and that this isn't an EnTK supported feature (yet, though I hope it is something that should be taken into account).

**Comment by mtitov** [comment]
I would have two possible solutions:
(1) represent such tasks with dependencies as a single task using a wrapper script (in the 1st example: tasks `1B`,`1C`,`1D` will be "merged" into `1BCD` task) - that would be a straightforward if tasks share the same environment, but more complex if not; also important to note, that traces will not distinguish these [sub]tasks (will be up to user to add required tracing events);
(2) have a synchronization flag between stages from different pipelines (in the 1st example: have 2 pipelines, the 2nd pipeline will have stages with a single task, and stages from the 1st pipeline will always wait for a flag from stages `(i)D` from the 2nd pipeline) - not available right now, require development.

**Comment by andre-merzky** [comment]
@GKNB : the RP branch `feature/bragg.py` now contains an example [RP script](https://github.com/radical-cybertools/radical.pilot/blob/feature/bragg.py/examples/misc/bragg.py) which renders the workflow shown above.  The example runs two of those workflows with randomized task runtimes.

Please do have a look if an approach like that would be suitable for your needs.   This is just a crude example really - if you are open to that approach we would recast that into some small framework which would make it easier to specify task types, data dependencies etc.

**Comment by andre-merzky** [comment]
@GKNB : ping :-)

**Comment by andre-merzky** [comment]
@GKNB : ping? :-)

**Comment by GKNB** [comment]
I am really sorry for the late reply. The script works perfectly and did exactly what I want on the local machine. I will test it on the cluster (Polaris) to see how it works there. I will close it when the Polaris tests is successful. 
Just one tiny comment: In the structure diagram, those policies and preliminary_train should be switched, but that does not affect the result. Thanks!

**Comment by andre-merzky** [comment]
Great, thanks for the feedback!  I am going to close this issue then - please don't hesitate to open a new issue if anything comes up!
