### ISSUE TITLE
Review exit codes as inputs for task states

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.entk#671]
Do we need to set task state according to the exit code from RP task (old approach that was eliminated)

```python
                        if deq_task.exit_code == 0:
                             task_state = DONE
                         elif deq_task.exit_code == 1:
                             task_state = FAILED
                         else:
                             task_state = deq_task.state
```

https://github.com/radical-cybertools/radical.entk/pull/670/files#diff-533292a24dcca7077df420cea34fee499637946257b61696ebee74b3858da357L351-L359

Close the ticket after the discussion.

**Comment by andre-merzky** [comment]
Alas no: the ticket this PR is addressing stumbled over failed output staging. That would not be captured by the exit code, the RP task state however does capture that error.

**Comment by mtitov** [comment]
Yeah, got it, thank you!
