### ISSUE TITLE
consistency in naming

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.entk#8]
Antons, Ole,

Please extend this "consistency" drive to the use of "mode 1" in:
       http://radicalensemblemd.readthedocs.org/en/latest/usecases.html

Thanks
Shantenu

On Sun, 7 Sep 2014, Shantenu Jha wrote:

Hi Antons,

It appears to me that the google doc outlining the schemes at:
 https://docs.google.com/document/d/1rfyGLOO0IiFbBNCfNScsjwu94x7sFcHPFMNgEl9be0Q/edit

is now inconsistent with the current documentation that you're asking
us to test with:
  https://github.com/radical-cybertools/RepEx/blob/master/README.md
  https://github.com/radical-cybertools/RepEx/blob/master/TESTING.md

Is that correct? If so, could you please make them consistent. If I'm
mixing something the numbering my apologies.

As you know there are some similarities between RepEx and ASA patterns
in that for the main pattern, there exist variations along two
different dimensions. The first is the overlap of the simulation -
analysis (or exchange) phases, and the second variation is in the
number of cores available (so as to run the full ensemble of
simulations simultaneously, or not).

Can you & Vivek get the terminology consistent across RepEx & ASA
patterns and the numbering consistent, i.e., schemes vs
micro-patterns, scheme 1 vs scheme 1-A (for when the micro-pattern is
the same but number of cores available differ).

**Comment by vivek-bala** [comment]
NA. Closing.
